### ISSUE TITLE
feature request - snapshot cloning support

### ISSUE THREAD

**Issue by rbro** [maxbube/mydumper#10]
Percona Server 5.6 supports a feature where you can start a transaction using the snapshot from another session:

`START TRANSACTION WITH CONSISTENT SNAPSHOT FROM SESSION <session_id>;`

https://www.percona.com/doc/percona-server/5.6/management/start_transaction_with_consistent_snapshot.html

Would it be possible to have mydumper use this method for consistent backups if the server supports it?

Thanks for your help.

**Comment by maxbube** [comment]
Hi, 

Yes, I have that in me head for long time, I will try to get it ready soon. 

Cheers

**Comment by davidducos** [comment]
@rbro looks like this was done with this PR: https://github.com/maxbube/mydumper/pull/188 please let me know if it is not and we will reopen this issue
