### ISSUE TITLE
timestamp column default values will be changed after using mydumper and myloader

### ISSUE THREAD

**Issue by liuguoshun** [maxbube/mydumper#102]
Need add "/*!40103 SET TIME_ZONE='+00:00' */;" at the top of table definition sql file.
how to repeat:
1.
mysql> show variables like 'time_zone';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| time_zone     | +08:00 |
+---------------+--------+
1 row in set (0.00 sec)

2.
mysql> CREATE TABLE `test10` (   `create_time` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '' ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 rows affected (0.01 sec)

3.
[root@mysql-gs-qmduz test]# mydumper --socket=/tmp/mysql3308.sock --user=root --password=root123 --database=test --tables-list=test10 --outputdir=/apps/tmp/test --verbose=3 --threads=5 --long-query-guard=1000 --kill-long-queries --logfile=/apps/tmp/test/exp.log 

4.
[root@mysql-gs-qmduz test]# more test.test10-schema.sql
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

CREATE TABLE `test10` (
  `create_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '????'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

5.
[root@mysql-gs-qmduz test]# myloader --socket=/tmp/mysql3308.sock --user=root --password=root123 --database=test --directory=/apps/tmp/test --overwrite-tables 

** (myloader:30915): CRITICAL **: Error restoring test.test10 from file test.test10-schema.sql: Invalid default value for 'create_time'

** (myloader:30915): CRITICAL **: Error restoring test.test10 from file test.test10.sql: Table 'test.test10' doesn't exist

**Comment by druud** [comment]
Thanks for bringing this up. I also hit this last December.

I have used:
`'SET GLOBAL time_zone='+00:00';`
on the loading box, but then you need to remember to set it back.
(re-enabling puppet, sets it back for me, so no worries here)

Later I switched to putting a line with
`SET TIME_ZONE='+00:00';`
on top of the involved .sql files.

**Comment by maxbube** [comment]
Hi @liuguoshun 

Thanks for the report, I will review this and fix it for the next release
