### ISSUE TITLE
--defaults-file option does not honor port

### ISSUE THREAD

**Issue by 1stone** [maxbube/mydumper#103]
When using the --defaults-file option with an option file, a explicitly set port is not used.

With an defaults-file (`dbconfig`) like this
```
[client]
host=mydb.example.com
port=3307
user=bla
password=fasel
```
an invokation of `mydumper --defaults-file=dbconfig ...` is effectively connecting to port 3306 on that remote host, rather than the specified 3307.

**Comment by maxbube** [comment]
Hi @1stone ,

Thanks for the report, I will review this for the next release
