### ISSUE TITLE
Threads don't shutdown

### ISSUE THREAD

**Issue by silasrm** [maxbube/mydumper#109]
Hi,

I'm using to backup my AWS Aurora and its has 10gb of size. I'm running mydumper with 10 threads, but 6 is finished and the others don't, and the process don't exited. 

I check if create the .gz files of the last dumping of the others threads, and is ok. The size of then don't change.

I'm running with verbose info level. I'm edit the database and tables names:

> ** Message: Thread 1 connected using MySQL connection ID 31285287
> ** Message: Thread 2 connected using MySQL connection ID 31285288
> ** Message: Thread 3 connected using MySQL connection ID 31285295
> ** Message: Thread 4 connected using MySQL connection ID 31285296
> ** Message: Thread 5 connected using MySQL connection ID 31285297
> ** Message: Thread 6 connected using MySQL connection ID 31285299
> ** Message: Thread 7 connected using MySQL connection ID 31285300
> ** Message: Thread 8 connected using MySQL connection ID 31285302
> ** Message: Thread 9 connected using MySQL connection ID 31285306
> ** Message: Thread 10 connected using MySQL connection ID 31285307
> ** Message: Thread 1 dumping data for `DB`.`a...cos`
> ** Message: Thread 6 dumping data for `DB`.`a...tas`
> ** Message: Thread 10 dumping data for `DB`.`a...ias`
> ** Message: Thread 9 dumping data for `DB`.`a...das`
> ** Message: Thread 3 dumping data for `DB`.`a...cos`
> ** Message: Thread 4 dumping data for `DB`.`a...ido`
> ** Message: Thread 7 dumping data for `DB`.`a...cos`
> ** Message: Thread 8 dumping data for `DB`.`a...pos`
> ** Message: Thread 2 dumping data for `DB`.`a...ico`
> ** Message: Thread 5 dumping data for `DB`.`a...ios`
> ** Message: Non-InnoDB dump complete, unlocking tables
> ** Message: Thread 4 dumping data for `DB`.`a...vos`
> ** Message: Thread 9 dumping data for `DB`.`b...ros`
> ** Message: Thread 8 dumping data for `DB`.`b...oes`
> ** Message: Thread 3 dumping data for `DB`.`b...nto`
> ** Message: Thread 6 dumping data for `DB`.`c...ios`
> ** Message: Thread 4 dumping data for `DB`.`c...nto`
> ** Message: Thread 6 dumping data for `DB`.`c...bo`
> ** Message: Thread 3 dumping data for `DB`.`c...iap`
> ** Message: Thread 4 dumping data for `DB`.`c...ias`
> ** Message: Thread 8 dumping data for `DB`.`c...ids`
> ** Message: Thread 4 dumping data for `DB`.`c...oes`
> ** Message: Thread 1 dumping data for `DB`.`c...oes`
> ** Message: Thread 4 dumping data for `DB`.`c...dos`
> ** Message: Thread 3 dumping data for `DB`.`c...oes`
> ** Message: Thread 3 dumping data for `DB`.`c...oes`
> ** Message: Thread 6 dumping data for `DB`.`c...cos`
> ** Message: Thread 1 dumping data for `DB`.`c...oes`
> ** Message: Thread 7 dumping data for `DB`.`c...ios`
> ** Message: Thread 2 dumping data for `DB`.`c...tas`
> ** Message: Thread 8 dumping data for `DB`.`c...tus`
> ** Message: Thread 7 dumping data for `DB`.`c...ens`
> ** Message: Thread 8 dumping data for `DB`.`c...tas`
> ** Message: Thread 3 dumping data for `DB`.`c...iap`
> ** Message: Thread 10 dumping data for `DB`.`c...ids`
> ** Message: Thread 4 dumping data for `DB`.`c...tos`
> ** Message: Thread 3 dumping data for `DB`.`c...ios`
> ** Message: Thread 5 dumping data for `DB`.`c...ios`
> ** Message: Thread 5 dumping data for `DB`.`d...ens`
> ** Message: Thread 5 dumping data for `DB`.`d...ras`
> ** Message: Thread 5 dumping data for `DB`.`d...ida`
> ** Message: Thread 5 dumping data for `DB`.`d...ens`
> ** Message: Thread 10 dumping data for `DB`.`d...ens`
> ** Message: Thread 10 dumping data for `DB`.`d...tas`
> ** Message: Thread 10 dumping data for `DB`.`d...das`
> ** Message: Thread 10 dumping data for `DB`.`d...cos`
> ** Message: Thread 10 dumping data for `DB`.`d...ens`
> ** Message: Thread 10 dumping data for `DB`.`d...cos`
> ** Message: Thread 5 dumping data for `DB`.`d...ues`
> ** Message: Thread 5 dumping data for `DB`.`d...des`
> ** Message: Thread 5 dumping data for `DB`.`d...ste`
> ** Message: Thread 5 dumping data for `DB`.`d...cos`
> ** Message: Thread 4 dumping data for `DB`.`d...ens`
> ** Message: Thread 5 dumping data for `DB`.`d...gas`
> ** Message: Thread 5 dumping data for `DB`.`d...ens`
> ** Message: Thread 4 dumping data for `DB`.`d...oes`
> ** Message: Thread 4 dumping data for `DB`.`e...ros`
> ** Message: Thread 4 dumping data for `DB`.`e...oes`
> ** Message: Thread 4 dumping data for `DB`.`e...cos`
> ** Message: Thread 4 dumping data for `DB`.`e...ais`
> ** Message: Thread 4 dumping data for `DB`.`e...oes`
> ** Message: Thread 4 dumping data for `DB`.`e...pes`
> ** Message: Thread 4 dumping data for `DB`.`e...cos`
> ** Message: Thread 5 dumping data for `DB`.`e...vos`
> ** Message: Thread 5 dumping data for `DB`.`e...cos`
> ** Message: Thread 10 dumping data for `DB`.`e...las`
> ** Message: Thread 10 dumping data for `DB`.`e...dio`
> ** Message: Thread 7 dumping data for `DB`.`e...ipe`
> ** Message: Thread 7 dumping data for `DB`.`e...des`
> ** Message: Thread 5 dumping data for `DB`.`e...ros`
> ** Message: Thread 5 dumping data for `DB`.`e...sas`
> ** Message: Thread 5 dumping data for `DB`.`e...tes`
> ** Message: Thread 7 dumping data for `DB`.`e...ual`
> ** Message: Thread 2 dumping data for `DB`.`e...ual`
> ** Message: Thread 4 dumping data for `DB`.`e...aos`
> ** Message: Thread 5 dumping data for `DB`.`e...vos`
> ** Message: Thread 5 dumping data for `DB`.`e...cos`
> ** Message: Thread 4 dumping data for `DB`.`e...oes`
> ** Message: Thread 4 dumping data for `DB`.`e...tos`
> ** Message: Thread 5 dumping data for `DB`.`f...cos`
> ** Message: Thread 5 dumping data for `DB`.`f...ias`
> ** Message: Thread 5 dumping data for `DB`.`f...gos`
> ** Message: Thread 5 dumping data for `DB`.`f...cos`
> ** Message: Thread 1 dumping data for `DB`.`f...ens`
> ** Message: Thread 3 dumping data for `DB`.`f...ues`
> ** Message: Thread 3 dumping data for `DB`.`f...tes`
> ** Message: Thread 3 dumping data for `DB`.`f...res`
> ** Message: Thread 3 dumping data for `DB`.`f...cos`
> ** Message: Thread 3 dumping data for `DB`.`f...cao`
> ** Message: Thread 3 dumping data for `DB`.`f...cos`
> ** Message: Thread 3 dumping data for `DB`.`g...tos`
> ** Message: Empty table DB.g...tos
> ** Message: Thread 3 dumping data for `DB`.`g...cao`
> ** Message: Empty table DB.g...cao
> ** Message: Thread 3 dumping data for `DB`.`h...rus`
> ** Message: Thread 9 dumping data for `DB`.`i...cos`
> ** Message: Thread 3 dumping data for `DB`.`i...tus`
> ** Message: Thread 3 dumping data for `DB`.`i...oes`
> ** Message: Thread 3 dumping data for `DB`.`i...ids`
> ** Message: Thread 3 dumping data for `DB`.`i...tos`
> ** Message: Thread 3 dumping data for `DB`.`o...tos`
> ** Message: Thread 3 dumping data for `DB`.`o...cos`
> ** Message: Thread 3 dumping data for `DB`.`o...oes`
> ** Message: Thread 3 dumping data for `DB`.`o...oes`
> ** Message: Thread 3 dumping data for `DB`.`o...ios`
> ** Message: Thread 3 dumping data for `DB`.`o...oes`
> ** Message: Thread 3 dumping data for `DB`.`o...pos`
> ** Message: Thread 3 dumping data for `DB`.`p...tos`
> ** Message: Thread 3 dumping data for `DB`.`p...ups`
> ** Message: Thread 9 dumping data for `DB`.`p...ias`
> ** Message: Thread 9 dumping data for `DB`.`p...ual`
> ** Message: Thread 9 dumping data for `DB`.`p...cos`
> ** Message: Thread 4 dumping data for `DB`.`p...tos`
> ** Message: Thread 4 dumping data for `DB`.`p...des`
> ** Message: Thread 4 dumping data for `DB`.`p...cos`
> ** Message: Thread 4 dumping data for `DB`.`p...ais`
> ** Message: Thread 4 dumping data for `DB`.`p...tos`
> ** Message: Empty table DB.p...tos
> ** Message: Thread 4 dumping data for `DB`.`p...cas`
> ** Message: Thread 4 dumping data for `DB`.`p...ico`
> ** Message: Thread 4 dumping data for `DB`.`p...tes`
> ** Message: Thread 4 dumping data for `DB`.`p...cos`
> ** Message: Thread 4 dumping data for `DB`.`p...ros`
> ** Message: Thread 4 dumping data for `DB`.`p...tos`
> ** Message: Thread 4 dumping data for `DB`.`p...ens`
> ** Message: Thread 4 dumping data for `DB`.`p...oes`
> ** Message: Thread 4 dumping data for `DB`.`p...tos`
> ** Message: Thread 4 dumping data for `DB`.`p...ico`
> ** Message: Thread 4 dumping data for `DB`.`p...des`
> ** Message: Thread 4 dumping data for `DB`.`p...oes`
> ** Message: Thread 4 dumping data for `DB`.`p...tos`
> ** Message: Thread 4 dumping data for `DB`.`p...pos`
> ** Message: Thread 4 dumping data for `DB`.`p...xos`
> ** Message: Thread 4 dumping data for `DB`.`p...ios`
> ** Message: Thread 4 dumping data for `DB`.`...do`
> ** Message: Thread 4 dumping data for `DB`.`s...cao`
> ** Message: Thread 4 dumping data for `DB`.`s...pos`
> ** Message: Thread 4 dumping data for `DB`.`s...tos`
> ** Message: Thread 1 dumping data for `DB`.`s...cbo`
> ** Message: Thread 4 dumping data for `DB`.`s...oes`
> ** Message: Thread 4 dumping data for `DB`.`s...oes`
> ** Message: Thread 4 dumping data for `DB`.`s...cos`
> ** Message: Thread 4 dumping data for `DB`.`s...pos`
> ** Message: Thread 4 dumping data for `DB`.`s...tas`
> ** Message: Thread 4 dumping data for `DB`.`s...vos`
> ** Message: Thread 4 dumping data for `DB`.`s...ids`
> ** Message: Thread 4 dumping data for `DB`.`s...oes`
> ** Message: Thread 4 dumping data for `DB`.`s...ens`
> ** Message: Thread 4 dumping data for `DB`.`s...oes`
> ** Message: Thread 4 dumping data for `DB`.`t...ulo`
> ** Message: Thread 4 dumping data for `DB`.`t...ios`
> ** Message: Thread 4 dumping data for `DB`.`t...ulo`
> ** Message: Thread 4 dumping data for `DB`.`t...ulo`
> ** Message: Thread 4 dumping data for `DB`.`t...los`
> ** Message: Thread 4 dumping data for `DB`.`t...tos`
> ** Message: Thread 4 dumping data for `DB`.`t...oes`
> ** Message: Thread 4 dumping data for `DB`.`t...ens`
> ** Message: Thread 4 dumping data for `DB`.`u...vas`
> ** Message: Thread 4 dumping data for `DB`.`u...tes`
> ** Message: Thread 4 dumping data for `DB`.`u...des`
> ** Message: Thread 4 dumping data for `DB`.`u...cos`
> ** Message: Thread 1 dumping data for `DB`.`u...nha`
> ** Message: Thread 1 dumping data for `DB`.`u...ios`
> ** Message: Thread 1 dumping data for `DB`.`u...des`
> ** Message: Thread 1 dumping data for `DB`.`z...pos`
> ** Message: Thread 1 dumping data for `DB`.`z...xos`
> ** Message: Empty table DB.z...xos
> ** Message: Thread 1 dumping data for `DB`.`z...cos`
> ** Message: Thread 1 dumping data for `DB`.`z...nas`
> ** Message: Thread 1 dumping data for `DB`.`z...ses`
> ** Message: Thread 1 dumping schema for `DB`.`a...cos`
> ** Message: Thread 1 dumping schema for `DB`.`a...ios`
> ** Message: Thread 1 dumping schema for `DB`.`a...das`
> ** Message: Thread 1 dumping schema for `DB`.`a...ias`
> ** Message: Thread 1 dumping schema for `DB`.`a...cos`
> ** Message: Thread 1 dumping schema for `DB`.`a...ido`
> ** Message: Thread 1 dumping schema for `DB`.`a...tas`
> ** Message: Thread 1 dumping schema for `DB`.`a...cos`
> ** Message: Thread 1 dumping schema for `DB`.`a...pos`
> ** Message: Thread 1 dumping schema for `DB`.`a...ico`
> ** Message: Thread 1 dumping schema for `DB`.`a...vos`
> ** Message: Thread 1 dumping schema for `DB`.`b...ros`
> ** Message: Thread 1 dumping schema for `DB`.`b...oes`
> ** Message: Thread 1 dumping schema for `DB`.`b...nto`
> ** Message: Thread 1 dumping schema for `DB`.`c...ios`
> ** Message: Thread 1 dumping schema for `DB`.`c...nto`
> ** Message: Thread 1 dumping schema for `DB`.`...bo`
> ** Message: Thread 1 dumping schema for `DB`.`c...iap`
> ** Message: Thread 1 dumping schema for `DB`.`c...ias`
> ** Message: Thread 1 dumping schema for `DB`.`c...ids`
> ** Message: Thread 1 dumping schema for `DB`.`c...oes`
> ** Message: Thread 1 dumping schema for `DB`.`c...oes`
> ** Message: Thread 1 dumping schema for `DB`.`c...dos`
> ** Message: Thread 1 dumping schema for `DB`.`c...oes`
> ** Message: Thread 1 dumping schema for `DB`.`c...oes`
> ** Message: Thread 1 dumping schema for `DB`.`c...cos`
> ** Message: Thread 1 dumping schema for `DB`.`c...oes`
> ** Message: Thread 1 dumping schema for `DB`.`c...ios`
> ** Message: Thread 1 dumping schema for `DB`.`c...tas`
> ** Message: Thread 1 dumping schema for `DB`.`c...tus`
> ** Message: Thread 1 dumping schema for `DB`.`c...ens`
> ** Message: Thread 1 dumping schema for `DB`.`c...tas`
> ** Message: Thread 1 dumping schema for `DB`.`c...iap`
> ** Message: Thread 1 dumping schema for `DB`.`c...ids`
> ** Message: Thread 1 dumping schema for `DB`.`c...tos`
> ** Message: Thread 1 dumping schema for `DB`.`c...ios`
> ** Message: Thread 1 dumping schema for `DB`.`c...ios`
> ** Message: Thread 1 dumping schema for `DB`.`d...ens`
> ** Message: Thread 1 dumping schema for `DB`.`d...ras`
> ** Message: Thread 1 dumping schema for `DB`.`d...ida`
> ** Message: Thread 1 dumping schema for `DB`.`d...ens`
> ** Message: Thread 1 dumping schema for `DB`.`d...ens`
> ** Message: Thread 1 dumping schema for `DB`.`d...tas`
> ** Message: Thread 1 dumping schema for `DB`.`d...das`
> ** Message: Thread 1 dumping schema for `DB`.`d...cos`
> ** Message: Thread 1 dumping schema for `DB`.`d...ens`
> ** Message: Thread 1 dumping schema for `DB`.`d...cos`
> ** Message: Thread 1 dumping schema for `DB`.`d...ues`
> ** Message: Thread 1 dumping schema for `DB`.`d...des`
> ** Message: Thread 1 dumping schema for `DB`.`d...ste`
> ** Message: Thread 1 dumping schema for `DB`.`d...cos`
> ** Message: Thread 1 dumping schema for `DB`.`d...ens`
> ** Message: Thread 1 dumping schema for `DB`.`d...gas`
> ** Message: Thread 1 dumping schema for `DB`.`d...ens`
> ** Message: Thread 1 dumping schema for `DB`.`d...oes`
> ** Message: Thread 1 dumping schema for `DB`.`e...ros`
> ** Message: Thread 1 dumping schema for `DB`.`e...oes`
> ** Message: Thread 1 dumping schema for `DB`.`e...cos`
> ** Message: Thread 1 dumping schema for `DB`.`e...ais`
> ** Message: Thread 1 dumping schema for `DB`.`e...oes`
> ** Message: Thread 1 dumping schema for `DB`.`e...pes`
> ** Message: Thread 1 dumping schema for `DB`.`e...cos`
> ** Message: Thread 1 dumping schema for `DB`.`e...vos`
> ** Message: Thread 1 dumping schema for `DB`.`e...cos`
> ** Message: Thread 1 dumping schema for `DB`.`e...las`
> ** Message: Thread 1 dumping schema for `DB`.`e...dio`
> ** Message: Thread 1 dumping schema for `DB`.`e...ipe`
> ** Message: Thread 1 dumping schema for `DB`.`e...des`
> ** Message: Thread 1 dumping schema for `DB`.`e...ros`
> ** Message: Thread 1 dumping schema for `DB`.`e...sas`
> ** Message: Thread 1 dumping schema for `DB`.`e...tes`
> ** Message: Thread 1 dumping schema for `DB`.`e...ual`
> ** Message: Thread 1 dumping schema for `DB`.`e...ual`
> ** Message: Thread 1 dumping schema for `DB`.`e...aos`
> ** Message: Thread 1 dumping schema for `DB`.`e...vos`
> ** Message: Thread 1 dumping schema for `DB`.`e...cos`
> ** Message: Thread 1 dumping schema for `DB`.`e...oes`
> ** Message: Thread 1 dumping schema for `DB`.`e...tos`
> ** Message: Thread 1 dumping schema for `DB`.`f...cos`
> ** Message: Thread 1 dumping schema for `DB`.`f...ias`
> ** Message: Thread 1 dumping schema for `DB`.`f...gos`
> ** Message: Thread 1 dumping schema for `DB`.`f...cos`
> ** Message: Thread 1 dumping schema for `DB`.`f...ens`
> ** Message: Thread 1 dumping schema for `DB`.`f...ues`
> ** Message: Thread 1 dumping schema for `DB`.`f...tes`
> ** Message: Thread 1 dumping schema for `DB`.`f...res`
> ** Message: Thread 1 dumping schema for `DB`.`f...cos`
> ** Message: Thread 1 dumping schema for `DB`.`f...cao`
> ** Message: Thread 1 dumping schema for `DB`.`f...cos`
> ** Message: Thread 1 dumping schema for `DB`.`g...tos`
> ** Message: Thread 1 dumping schema for `DB`.`g...cao`
> ** Message: Thread 1 dumping schema for `DB`.`h...rus`
> ** Message: Thread 1 dumping schema for `DB`.`i...cos`
> ** Message: Thread 1 dumping schema for `DB`.`i...tus`
> ** Message: Thread 1 dumping schema for `DB`.`i...oes`
> ** Message: Thread 1 dumping schema for `DB`.`i...ids`
> ** Message: Thread 1 dumping schema for `DB`.`i...tos`
> ** Message: Thread 1 dumping schema for `DB`.`o...tos`
> ** Message: Thread 1 dumping schema for `DB`.`o...cos`
> ** Message: Thread 1 dumping schema for `DB`.`o...oes`
> ** Message: Thread 1 dumping schema for `DB`.`o...oes`
> ** Message: Thread 1 dumping schema for `DB`.`o...ios`
> ** Message: Thread 1 dumping schema for `DB`.`o...oes`
> ** Message: Thread 1 dumping schema for `DB`.`o...pos`
> ** Message: Thread 1 dumping schema for `DB`.`p...tos`
> ** Message: Thread 1 dumping schema for `DB`.`p...ups`
> ** Message: Thread 1 dumping schema for `DB`.`p...ias`
> ** Message: Thread 1 dumping schema for `DB`.`p...ual`
> ** Message: Thread 1 dumping schema for `DB`.`p...cos`
> ** Message: Thread 1 dumping schema for `DB`.`p...tos`
> ** Message: Thread 1 dumping schema for `DB`.`p...des`
> ** Message: Thread 1 dumping schema for `DB`.`p...cos`
> ** Message: Thread 1 dumping schema for `DB`.`p...ais`
> ** Message: Thread 1 dumping schema for `DB`.`p...tos`
> ** Message: Thread 1 dumping schema for `DB`.`p...cas`
> ** Message: Thread 1 dumping schema for `DB`.`p...ico`
> ** Message: Thread 1 dumping schema for `DB`.`p...tes`
> ** Message: Thread 1 dumping schema for `DB`.`p...cos`
> ** Message: Thread 1 dumping schema for `DB`.`p...ros`
> ** Message: Thread 1 dumping schema for `DB`.`p...tos`
> ** Message: Thread 1 dumping schema for `DB`.`p...ens`
> ** Message: Thread 1 dumping schema for `DB`.`p...oes`
> ** Message: Thread 1 dumping schema for `DB`.`p...tos`
> ** Message: Thread 1 dumping schema for `DB`.`p...ico`
> ** Message: Thread 1 dumping schema for `DB`.`p...des`
> ** Message: Thread 1 dumping schema for `DB`.`p...oes`
> ** Message: Thread 1 dumping schema for `DB`.`p...tos`
> ** Message: Thread 1 dumping schema for `DB`.`p...pos`
> ** Message: Thread 1 dumping schema for `DB`.`p...xos`
> ** Message: Thread 1 dumping schema for `DB`.`p...ios`
> ** Message: Thread 1 dumping schema for `DB`.`...do`
> ** Message: Thread 1 dumping schema for `DB`.`s...cao`
> ** Message: Thread 1 dumping schema for `DB`.`s...pos`
> ** Message: Thread 1 dumping schema for `DB`.`s...tos`
> ** Message: Thread 1 dumping schema for `DB`.`s...cbo`
> ** Message: Thread 1 dumping schema for `DB`.`s...oes`
> ** Message: Thread 1 dumping schema for `DB`.`s...oes`
> ** Message: Thread 1 dumping schema for `DB`.`s...cos`
> ** Message: Thread 1 dumping schema for `DB`.`s...pos`
> ** Message: Thread 1 dumping schema for `DB`.`s...tas`
> ** Message: Thread 1 dumping schema for `DB`.`s...vos`
> ** Message: Thread 1 dumping schema for `DB`.`s...ids`
> ** Message: Thread 1 dumping schema for `DB`.`s...oes`
> ** Message: Thread 1 dumping schema for `DB`.`s...ens`
> ** Message: Thread 1 dumping schema for `DB`.`s...oes`
> ** Message: Thread 1 dumping schema for `DB`.`t...ulo`
> ** Message: Thread 1 dumping schema for `DB`.`t...ios`
> ** Message: Thread 1 dumping schema for `DB`.`t...ulo`
> ** Message: Thread 1 dumping schema for `DB`.`t...ulo`
> ** Message: Thread 1 dumping schema for `DB`.`t...los`
> ** Message: Thread 1 dumping schema for `DB`.`t...tos`
> ** Message: Thread 1 dumping schema for `DB`.`t...oes`
> ** Message: Thread 1 dumping schema for `DB`.`t...ens`
> ** Message: Thread 1 dumping schema for `DB`.`u...vas`
> ** Message: Thread 1 dumping schema for `DB`.`u...tes`
> ** Message: Thread 1 dumping schema for `DB`.`u...des`
> ** Message: Thread 1 dumping schema for `DB`.`u...cos`
> ** Message: Thread 1 dumping schema for `DB`.`u...nha`
> ** Message: Thread 1 dumping schema for `DB`.`u...ios`
> ** Message: Thread 1 dumping schema for `DB`.`u...des`
> ** Message: Thread 1 dumping schema for `DB`.`z...pos`
> ** Message: Thread 1 dumping schema for `DB`.`z...xos`
> ** Message: Thread 1 dumping schema for `DB`.`z...cos`
> ** Message: Thread 1 dumping schema for `DB`.`z...nas`
> ** Message: Thread 1 dumping schema for `DB`.`z...ses`
> ** Message: Thread 1 shutting down
> ** Message: Thread 2 shutting down
> ** Message: Thread 7 shutting down
> ** Message: Thread 8 shutting down
> ** Message: Thread 5 shutting down
> ** Message: Thread 3 shutting down

**Comment by silasrm** [comment]
All lost threads last table dump has size of 800MB, 1.1GB, 3GB and 4GB.

**Comment by maxbube** [comment]
Hi @silasrm are you connecting to a specific node or reader endpoint?

**Comment by silasrm** [comment]
I'm trying in reader and cluster endpoints.

**Comment by maxbube** [comment]
Hi @silasrm you need to connect directly to a db node endpoint, if you use cluster endpoints connections could go to different ones.

**Comment by silasrm** [comment]
Ok. Thks
