### ISSUE TITLE
Savepoint failed: MySQL server has gone away

### ISSUE THREAD

**Issue by verwilst** [maxbube/mydumper#111]
Using Mydumper 0.9.3, around 40 minutes into my backup, suddenly this happens:

** Message: Empty table mydb.opentafeldet
** Message: Thread 5 dumping data for `mydb`.`postcodes`
** Message: Thread 5 dumping data for `mydb`.`printers`
** Message: Thread 5 dumping data for `mydb`.`printspool`
** Message: Empty table mydb.printspool
** Message: Thread 5 dumping data for `mydb`.`rapport`
** Message: Thread 5 dumping data for `mydb`.`users`
** Message: Thread 5 shutting down
** Message: Thread 3 dumping data for `mydb2`.`voorraad_ref`

** (mydumper:27563): CRITICAL **: Savepoint failed: MySQL server has gone away

** (mydumper:27563): CRITICAL **: Error dumping table (mydb2.voorraad_ref) data: MySQL server has gone away 
** Message: Empty table mydb2.voorraad_ref

** (mydumper:27563): CRITICAL **: Rollback to savepoint failed: MySQL server has gone away
** Message: Thread 3 dumping data for `mydb3`.`voorraad_ref`

** (mydumper:27563): CRITICAL **: Savepoint failed: MySQL server has gone away

** (mydumper:27563): CRITICAL **: Error dumping table (mydb3.voorraad_ref) data: MySQL server has gone away 
** Message: Empty table mydb3.voorraad_ref

** (mydumper:27563): CRITICAL **: Rollback to savepoint failed: MySQL server has gone away
** Message: Thread 3 dumping data for `mydb3`.`inv_voorraad`

** (mydumper:27563): CRITICAL **: Savepoint failed: MySQL server has gone away

<snip>

The other threads are still backing up, only ( in this case ) thread 3 encountered the error and races through all tables, returning "MySQL has gone away" immediately.

I'm using automydumper, which uses "--less-locking --triggers --events --routines --use-savepoints" by default. 

Removing "--use-savepoints" allows the backup to complete without issues.

**Comment by davidducos** [comment]
We need feedback to proceed. closing it
https://github.com/maxbube/mydumper/wiki/Support
