### ISSUE TITLE
Cannot create a JSON value from a string with CHARACTER SET 'binary'

### ISSUE THREAD

**Issue by niyunjiu** [maxbube/mydumper#112]
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
INSERT INTO `user` VALUES
(1,"lucy","{\"ip\": \"192.168.1.1\", \"time\": \"2015-01-01 13:00:00\", \"result\": \"fail\"}"),
(2,"bobo","{\"ip\": \"192.168.1.0\", \"time\": \"2015-10-07 06:44:00\", \"result\": \"success\"}"),
(3,"jianhaiqing","{\"ip\": \"192.168.1.1\", \"time\": \"2017-10-25 17:10:44.000000\", \"result\": \"fail\"}");

i think the exported *.sql which included data should use the names from creating statement;

e.g.
CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `name` varchar(20) DEFAULT NULL,
  `lastlogininfo` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

the exported sql could be :
/*!40101 SET NAMES utf8mb4*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
INSERT INTO `user` VALUES
(1,"lucy","{\"ip\": \"192.168.1.1\", \"time\": \"2015-01-01 13:00:00\", \"result\": \"fail\"}"),
(2,"bobo","{\"ip\": \"192.168.1.0\", \"time\": \"2015-10-07 06:44:00\", \"result\": \"success\"}"),
(3,"jianhaiqing","{\"ip\": \"192.168.1.1\", \"time\": \"2017-10-25 17:10:44.000000\", \"result\": \"fail\"}");

but the error only caused by json type.

**Comment by maxbube** [comment]
Hi @niyunjiu , 

I was not able to reproduce this issue, in my case mydumper is generating this output

```
INSERT INTO `t2` VALUES
(CONVERT("{\"key1\": \"value1\", \"key2\": \"value2\"}" USING UTF8MB4));
```
which myloader is able to restore.

I will release soon the next version. Please if your problem persists send me a reproducible case.

**Comment by niyunjiu** [comment]
the error is on the first line：
/!40101 SET NAMES binary/;
the binary is wrong，should be utf8mb4
