### ISSUE TITLE
mysql-0.9.3-el6 is built against outdated libpcre

### ISSUE THREAD

**Issue by UnixRonin** [maxbube/mydumper#114]
Max,
First, thanks for putting up current official binaries!
That said, your mydumper-0.9.3-41.el6.x86_64.rpm is built against libpcre.so.0, while current available pcre2 packages for RHEL6 install libpcre.so.1.  I don't even see any pcre1 package available any more for RHEL6.  It seems to WORK fine if I create a symlink /usr/lib64/libpcre.so.0 -> libpcre.so.1, but it'd probably be better linked against libpcre.so.1 in the first place.

**Comment by maxbube** [comment]
Hi @UnixRonin thanks for the report!!!, I will get it fixed on next release

**Comment by maxbube** [comment]
Hi @UnixRonin , latest el6 (6.9) with base repos only has libpcre.so.0 by pcre-7.8-7.el6.i686. There is not any other base package providing .1

```
[vagrant@localhost mydumper]$ yum whatprovides */libpcre.so.1
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
 * base: mirror.globo.com
 * extras: mirror.globo.com
 * updates: mirror.globo.com
No Matches found
[vagrant@localhost mydumper]$ cat /etc/centos-release
CentOS release 6.9 (Final)
```
