### ISSUE TITLE
--no-locks is sometimes ignored 

### ISSUE THREAD

**Issue by nataliezeller1** [maxbube/mydumper#115]
This issue happens occasionally - 
I'm running mydumper 0.9.3 with --no-locks. Sometimes getting this error, although this verification should be ignored when running with --no-locks:
(mydumper:569): CRITICAL **: There are queries in PROCESSLIST running longer than 60s, aborting dump, use --long-query-guard to change the guard value, kill queries (--kill-long-queries) or use different server for dump

**Comment by tanji** [comment]
It is already fixed here:
https://github.com/maxbube/mydumper/pull/90

**Comment by nataliezeller1** [comment]
Thanks, when is your next official release?

**Comment by maxbube** [comment]
Hi @nataliezeller1 I hope to have it released by the next month

**Comment by nataliezeller1** [comment]
Ok, Thank you
