### ISSUE TITLE
security against program parameters

### ISSUE THREAD

**Issue by flobee** [maxbube/mydumper#117]
hi
Maybe i dont know better but using mydumper -u user -p 1234 and anyone can see e.g. root credentials when tracking/seeing the process list?
Or does it source a .my.cnf ?
Kind regards Florian

**Comment by maxbube** [comment]
Hi @flobee mydumper can use credentials from .my.cnf and also you can use --defaults-file if is not a default location

**Comment by flobee** [comment]
Thx for reply. As good as i tested .my.cnf wasn't sourced :( 
mydumper 0.9.1 (debian stable) !? maybe thats why?

I'll give it a next try using --defaults-file. Arrrg. not in in that version yet, so thats why :(
thx, Kind regards Florian
