### ISSUE TITLE
Implement negative regex matching option

### ISSUE THREAD

**Issue by 64kramsystem** [maxbube/mydumper#119]
Mydumper currently supports positive table matching via regex (`--regex`), and requires negative groups for excluding tables. I think it would be cleaner to have a negation regex feature (mirroring tools like mysqldump/pump, which have mirrored include/exclude filtering).

**Comment by davidducos** [comment]
We could add option --nregex, don't think that will be hard to implement and it won't cause any harm.

**Comment by davidducos** [comment]
Hi @64kramsystem,

I already developed this enhancement, could be possible for you to test it? as I would like to test a real case scenario.

**Comment by 64kramsystem** [comment]
> Hi @64kramsystem,
> 
> I already developed this enhancement, could be possible for you to test it? as I would like to test a real case scenario.

Hello! First, thanks :smiley: 

Sure, I'll do this week. We actually have in plan to use MyDumper at my company, and this would be a very nice addition.

**Comment by 64kramsystem** [comment]
Hi there!

I've just tested it, from the branch `regex`. It works as intended. Specifically, I've used the option:

```
--nregex '^mydb.(prefix1|name2$|name3$|name4$|name5$|name6$|name7$|name8$|name9$)'
```

Thanks, this is a very useful addition :smile:

**Comment by davidducos** [comment]
@64kramsystem, 
In the PR there is a comment form Max, that says that this can be done with --regex and there is no need to use a negative. 

I review a bit more about it, and I found [this link](https://stackoverflow.com/questions/5313896/help-with-regex-include-and-exclude) which explains how to include and exclude using a single regex.
