### ISSUE TITLE
Table list and regex excluding each other?

### ISSUE THREAD

**Issue by fcolope** [maxbube/mydumper#12]
Hi,

When executing this command, no dump is done:
 `mydumper -c -B dbname -o /tmp/dbname -T table1,table2,table3 --regex "^dbname.table4"`

By removing regex or tables list option, dump is done correctly. 
Mydumper version is mydumper 0.9.1, built against MySQL 5.5.44-MariaDB

In mydumper help page, tables list option says:
`-T, --tables-list           Comma delimited table list to dump (does not exclude regex option)`

So, my question is simple. 
Can we use both options to include in dump some tables via list and regex or both optiones are really excluding each other? 
Is it a bug?

Regards.

**Comment by maxbube** [comment]
Hi, 

Help page is wrong, if you use both -T take precedence and --regex is ignored. I will fix the documentation.

Thanks for report!!
