### ISSUE TITLE
Is the description about include/exclude in readme correct?

### ISSUE THREAD

**Issue by Fanduzi** [maxbube/mydumper#123]
In the README , not to dump mysql and test database command is 
mydumper --regex '^(?!(mysql|test))'
 
But in my test, if i have a database test1, the test1 is also not dumped
maybe the command should be 
mydumper --regex '^(?!(mysql\.|test\.))'

**Comment by maxbube** [comment]
Hi @Fanduzi , you are right. 

I will get that clear in the documentation.

Thanks!
