### ISSUE TITLE
Skip data from FEDERATED tables

### ISSUE THREAD

**Issue by gkotr** [maxbube/mydumper#124]
I think that was very helpful to be a parameter on mydumper to skip taking FEDERATED data.

**Comment by maxbube** [comment]
Hi @gkotr 

mydumper has that for long time already, you can use `--ignore-engines`

**Comment by gkotr** [comment]
Thank you for your response!
I know the --ignore-engines but i want to take the schema and not the data. If i use --ignore-engines then i don't have the table schema.
