### ISSUE TITLE
Will mydumper support --where options in future releases?

### ISSUE THREAD

**Issue by danghuagood** [maxbube/mydumper#129]
Will mydumper support --where options(like mysqldump --where option) in future releases?

**Comment by maxbube** [comment]
Hi @danghuagood , 

Is possible, also mydumper/myloader is open to community PRs.

**Comment by vkingnew** [comment]
@maxbube  when to release the feature? It's  important to bakcuo the super big tables ,such as a table holds million rows,I just want to backup part of the table.

**Comment by zolech** [comment]
+1 for this

**Comment by geshan** [comment]
+1

**Comment by jmbkeyes** [comment]
+1 for this
