### ISSUE TITLE
Generated columns query disable check option

### ISSUE THREAD

**Issue by charles-001** [maxbube/mydumper#138]
Hello,

I've noticed that in 0.9.5, there was a new check added for generated columns. It runs a SELECT query like this:
select COLUMN_NAME from information_schema.COLUMNS where TABLE_SCHEMA='$table_schema' and TABLE_NAME='$table_name' and extra like '%GENERATED%'

The problem I have with this is that our database servers have millions of tables on them. We also do not have any generated columns and do not plan to add any. So, I propose there be an option to disable the check to not waste time running a useless query.

Thanks,

Charles

**Comment by davidducos** [comment]
We should check the amount of tables before selecting over information_schema.tables.
