### ISSUE TITLE
0.9.5:  Configure failure on Gentoo Linux

### ISSUE THREAD

**Issue by UnixRonin** [maxbube/mydumper#139]
Max,
I'm getting the following configuration failure on Gentoo Linux:

>>> Configuring source in /var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5_build"
cmake -C /var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DOCS=yes -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5
loading initial cache file /var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/libmysqlclient.so;/usr/lib64/libpthread.so;/usr/lib64/libz.so;/usr/lib64/libm.so;/usr/lib64/librt.so;MYSQL_LIBRARIES_atomic-NOTFOUND;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;/usr/lib64/libdl.so
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11")
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "0.29.2")
-- Checking for one of the modules 'glib-2.0'
-- Checking for one of the modules 'gthread-2.0'
-- Checking for module 'libpcre'
--   Found libpcre, version 8.41
-- Found PCRE: /usr/include
1
-- ------------------------------------------------
-- MYSQL_CONFIG = /usr/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr
-- BUILD_DOCS = yes
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -Wall -Wno-deprecated-declarations -Wunused -Wwrite-strings -Wno-strict-aliasing -Wextra -Wshadow -march=amdfam10 -O2 -pipe -mfpmath=sse -mcx16 -mpopcnt -I/usr/include/mysql
C++             -march=amdfam10 -O2 -pipe -mfpmath=sse -mcx16 -mpopcnt
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed
Module          -Wl,-O1 -Wl,--as-needed
Shared          -Wl,-O1 -Wl,--as-needed

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQL_LIBRARIES_atomic
    linked by target "mydumper" in directory /var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5
    linked by target "myloader" in directory /var/tmp/portage/dev-db/mydumper-0.9.5/work/mydumper-0.9.5

-- Configuring incomplete, errors occurred!

Any insights on this?

(Specifically:  It's clearly found MySQL/MariaDB and found libmysqlclient.so — what is it looking for and not finding that should satisfy MYSQL_LIBRARIES_atomic?)

**Comment by davidducos** [comment]
@UnixRonin 
Do you still need help on this? can you test with latest version?

**Comment by davidducos** [comment]
I investigated a bit more, and I use this commands to compile mydumper on gentoo:

```
emerge dev-vcs/git
git clone https://github.com/maxbube/mydumper.git
cd mydumper
emerge cmake
gentoo ~/mydumper # cat /etc/portage/package.use/zz-autounmask
# package.use
>=dev-libs/libxml2-2.9.10-r4 python_targets_python3_8
emerge  dev-libs/glib
emerge mysqlclient
cmake .
make
```
Please, let me know if that works for you.

**Comment by UnixRonin** [comment]
I'm using a Gentoo ebuild of my own creation that looks like this:

`EAPI=6

inherit cmake-utils

DESCRIPTION="A high-performance multi-threaded backup (and restore) toolset for MySQL"
HOMEPAGE="https://github.com/maxbube/mydumper"
SRC_URI="https://github.com/maxbube/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"
LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="doc"

CDEPEND="dev-libs/glib:=
	dev-libs/libpcre:=
	dev-libs/openssl:=
	sys-libs/zlib:=
	virtual/mysql"
DEPEND="${CDEPEND}
	virtual/pkgconfig
	doc? ( dev-python/sphinx )"
RDEPEND="${CDEPEND}"

# PATCHES=( "${FILESDIR}/${PN}-mariadb-include-fix.patch" )

src_prepare() {
	# respect user cflags; do not expand ${CMAKE_C_FLAGS} (!)
	sed -i -e 's:-Werror -O3 -g:${CMAKE_C_FLAGS}:' CMakeLists.txt || die

	# fix doc install path
	sed -i -e "s:share/doc/mydumper:share/doc/${PF}:" docs/CMakeLists.txt || die

	cmake-utils_src_prepare
}

src_configure() {
	local mycmakeargs=("-DBUILD_DOCS=$(usex doc)")

	cmake-utils_src_configure
}`

So it should be performing fundamentally the same operations.

I just tried it again and it is working today, but I do need to check that it is fully up to date.

**Comment by UnixRonin** [comment]
I just updated my ebuild from 0.10.1 to 0.10.3, and that builds fine as well.  There is just one issue, a warning that comes up three times during compilation when invoking Sphinx:

`cd /var/tmp/portage/dev-db/mydumper-0.10.3/work/mydumper-0.10.3_build/docs && /usr/bin/sphinx-build -q -b man -c /var/tmp/portage/dev-db/mydumper-0.10.3/work/mydumper-0.10.3_build/docs/_build -d /var/tmp/portage/dev-db/mydumper-0.10.3/work/mydumper-0.10.3_build/docs/_doctrees /var/tmp/portage/dev-db/mydumper-0.10.3/work/mydumper-0.10.3_build/docs/_sources /var/tmp/portage/dev-db/mydumper-0.10.3/work/mydumper-0.10.3_build/docs/man
WARNING: html_static_path entry '/var/tmp/portage/dev-db/mydumper-0.10.3/work/mydumper-0.10.3/docs/_static' does not exist
`

Any insights into this and what I can do to fix it?  Other than making the ebuild manually create the directory?

(whoa.  going to see if I can fix the mangled formatting on the previous.)

**Comment by UnixRonin** [comment]
Never mind, I've resolved it.

**Comment by davidducos** [comment]
I'm using the vagrant box: "generic/gentoo"

The sphinx issue is because you don't have installed the package, but it is just needed to build the documentation.

Closing this issue now! Thanks!

**Comment by UnixRonin** [comment]
(Just a footnote:  I DO have sphinx installed, that wasn't the problem, but it was resolved by an update to the mainstream Gentoo ebuild.)
