### ISSUE TITLE
Table checksums?

### ISSUE THREAD

**Issue by stephenreay** [maxbube/mydumper#141]
I’ve tried searching and read various versions of the man page but I can’t find a Mydumper option (or even an external solution short of using a node without any write activity) to write out the results of `checksum table` once the transaction has started, to allow for easier verifying following a restore.

**Comment by maxbube** [comment]
Hi @stephenreay is maybe pt-table-checksum what you need after a restore? you can find it here https://www.percona.com/doc/percona-toolkit/LATEST/pt-table-checksum.html

**Comment by stephenreay** [comment]
Hi @maxbube I'm not sure how that would really work in a backup/restore scenario.

If `mydumper` could store the result of `checksum table` on each table it's dumping, *after* it has started the transaction (and store it in a file alongside the dump), either a custom tool, (or ideally `myloader`) could then use that to ensure the restored table matches the original one, even if the original is lost.

**Comment by stephenreay** [comment]
Hi @maxbube,

Let me preface this by saying: I don't consider C or C++ to be things "in my wheelhouse".

Despite the above, I've managed to get this minimally working (i.e. it generates a new `db.table.checksum` file with the appropriate value in it, unless `--no-checksums` option is given).

Would you consider a PR for this feature (and forewarning, I absolutely expect some of what I've added will need attention to make it acceptable to include in upstream)?

The obvious (to me at least) next step would be support for reading the checksum values in `myloader` and throwing an error if a table doesn't match the stored checksum after loading the data. I haven't even looked at the `myloader.{c,h}` files yet, (so far, I'm quite honestly just happy that it still compiles with my changes and works), but if you'd consider merging this PR I'm happy to have a go at getting it to check them when loading too.

**Comment by davidducos** [comment]
Hi @stephenreay, I found a bug and push a PR with the fix. 
I realized of the bug when I was working on the testings... looks like the testings worked in this case! 🎉 🎉

**Comment by stephenreay** [comment]
Nice work.

I don't think it ever occurred to me that compression would be expected on those files, due to their fixed, small size. But I guess it makes sense for consistency.
