### ISSUE TITLE
add progress for mydumper/myloader

### ISSUE THREAD

**Issue by tsolodov** [maxbube/mydumper#143]
Is it possible to add a flag that will add progress of loading/dumping to stdout? 
for example
53/100 tables restored

**Comment by UnixRonin** [comment]
I second this request.  Right now it's very difficult to determine progress, particularly load progress, **ESPECIALLY** when using chunking.  I have a test restore right now that,s been running for 71 hours, against a 500GB database with multiple tables in the 300-400 million rows range, chunked every ten million rows, and I can devise absolutely no useful way to determine how close to complete the restore is.  I can see what myloader is working on **right now** by doing something like the following:

watch 'date; echo; lsof | grep myloader | grep <dump directory pathname>'

But that tells me absolutely nothing about how much has already been done or how much more still remains to do, especially if using a chunked dump, in which there appears to be no guarantee whatsoever that even chunks of the same table will be loaded in numerical order.  (On the restore job I have running right now, at one point three different threads were loading chunks 5, 9, and 20 of the same table.)

Even just a simple estimate of percentage complete, or data files loaded/total data files, would help.

**Comment by druud** [comment]
I generally check things like the size of files it writes, both at dumping and loading, in a second screen window.

**Comment by npinchot** [comment]
I think this would be a great feature.

For a workaround, I was able to get a rough estimate of completion by doing the following.
1. When restoring, enable verbose 3 (`--verbose=3`).
2. Get a total count of the number of files in the export directory.
3. Copy the output lines, paste into your favorite editor and count the lines.

It's a very rough estimate, especially if some tables take longer to restore than others, but it's better than nothing.
