### ISSUE TITLE
on multithreaded slaves  when gtid_mode is off  the slave status could be inconsistence

### ISSUE THREAD

**Issue by liuguoshun** [maxbube/mydumper#144]
Please refer doc about "gap-free low-watermark position".
https://dev.mysql.com/doc/refman/5.7/en/replication-features-transaction-inconsistencies.html

on multithreaded slaves when gtid_mode is off ,need print an error info or abort the backup.

**Comment by davidducos** [comment]
Can you explain a bit more about this scenario? as from what I understood, you are trying to take a backup from a multithreaded database and the position saved in metadata file might be no correct. Am i right?

**Comment by liuguoshun** [comment]
Yes, mydumper use "FLUSH TABLES WITH READ LOCK"  and "SHOW SLAVE STATUS" to get the Exec_master_log_pos.
Pos of "SLAVE STATUS" maybe not correct in metadata file, when backup multithreaded replica database.

**Comment by davidducos** [comment]
Ok, we are going to show a warning so users can disregard that info and start the replication from the replica where they are taking the backup instead of the source of the replication.

**Comment by davidducos** [comment]
@liuguoshun please, let me know if #417 is ok, so we can merge to master. 

Thank you!!

**Comment by liuguoshun** [comment]
Great!   :-)
