### ISSUE TITLE
Limit long query guard watching to dumped databases

### ISSUE THREAD

**Issue by kalumkalac** [maxbube/mydumper#147]
From my understanding of the code, the long query guard option will watch the whole server for *any* queries longer than X seconds.

But if I want to dump the database A, this option must only watch (and abort or kill) queries on the database A, not the B and C and so on.

Is that relevant or am I missing something?

Thanks

**Comment by maxbube** [comment]
Hi @kalumkalac, 

You are missing that FTWRL will be blocked by any transaction no matter what are you trying to dump.
