### ISSUE TITLE
ERROR 3144 (22032): Cannot create a JSON value from a string with CHARACTER SET 'binary'

### ISSUE THREAD

**Issue by bajrang0789** [maxbube/mydumper#151]
MyDumper converts the CHARSET to binary while dumping 
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

/*!40103 SET TIME_ZONE='+00:00' */;

The issue is only when we have a VIRTUAL GENERATED COLUMN from a json field, we seem to have ERROR while Loading through MyLOADER

 ** (myloader:27658): CRITICAL **: Error restoring test_db.tbl_data_info from file test_db.tbl_data_info.00000.sql.gz: **Cannot create a JSON value from a string with CHARACTER SET 'binary'.**

Sample Table structure: - 
```
CREATE TABLE `tbl_data_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `some_id` bigint(20) NOT NULL,
  `number` bigint(20) NOT NULL,
  `text` json NOT NULL,
  `object_id` bigint(20) GENERATED ALWAYS AS (json_unquote(json_extract(`text`,'$.ObjID'))) VIRTUAL NOT NULL,
  `status` smallint(6) NOT NULL,
  `effective_from` date NOT NULL,
  `effective_to` date NOT NULL,
  `created_at` bigint(20) NOT NULL,
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
The Source and Destination have the same CHARSET and Collations as below: 
MySQL version : 5.7.17-13-log (Source)
MySQL version : 5.7.22-22-log (Dest)

```
mysql> show variables like '%collation%' ;
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_unicode_ci |
| collation_database   | utf8mb4_unicode_ci |
| collation_server     | utf8mb4_unicode_ci |
+----------------------+--------------------+
3 rows in set (0.01 sec)

mysql> show variables like '%chara%' ;
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

```

Is there a way to change the Name while dumping using mydumper? Instead, use 
`/*!40101 SET NAMES utf8mb4*/;
`
Checked the dump file data the actual logical dump SQL is in `CONVERT("{...}" USING UTF8MB4)`

Went through the Bugs Reports: 
https://bugs.mysql.com/bug.php?id=88288
https://bugs.mysql.com/bug.php?id=86709 (Appears to be fixed on MySQL 8)

**Comment by bajrang0789** [comment]
It works for normal json fields only issue whenever we have Virtual Generated Columns in the tables to be restored. 
Any workaround or suggestions on the above will be really helpful. 

Thanks,

**Comment by Broutard** [comment]
is this solution viable?
why isn't it  merged? 

Thanks

**Comment by maxbube** [comment]
Hi, 
Thanks for the report and comments!!!

Changing NAMES directly to utf8mb4 is not viable for all use cases, this needs to be optional.

**Comment by maxbube** [comment]
Closing as duplicate #198
