### ISSUE TITLE
column charset is ignored once it's different from table charset.

### ISSUE THREAD

**Issue by jianhaiqing** [maxbube/mydumper#156]
* precondition:
`mydumper 0.9.5, built against MySQL 5.7.21-21`
`mysql  Ver 14.14 Distrib 5.7.19-17, for Linux (x86_64) using  6.2`
* MySQL character set
| Variable_name            | Value                                               |
| :-------- | --------:|
| character_set_client     | utf8mb4                                             |
| character_set_connection | utf8mb4                                             |
| character_set_database   | utf8mb4                                             |
| character_set_filesystem | binary                                              |
| character_set_results    | utf8mb4                                             |
| character_set_server     | utf8mb4                                             |
| character_set_system     | utf8                                                |
| character_sets_dir       | /usr/local/percona-server-5.7.19-17/share/charsets/ |

* source data definition structure:
```
CREATE TABLE `t_charset_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `exec_info` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```
* mydumper-schema
```
CREATE TABLE `t_charset_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `exec_info` varchar(512) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4;
```

**Comment by davidducos** [comment]
Hi @jianhaiqing,
I tested with 
```
root@ubuntu-focal:~# mydumper --version
mydumper 0.10.5, built against MySQL 5.7.33-36
```
And it is working as expected
```
mysql> use issue_156
mysql> CREATE TABLE `t_charset_test` (   `id` int(11) NOT NULL AUTO_INCREMENT,   `exec_info` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',   PRIMARY KEY (`id`) ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
Query OK, 0 rows affected (0.01 sec)

root@ubuntu-focal:~# mydumper -B issue_156 -o issue_156
root@ubuntu-focal:~# cat issue_156/issue_156.t_charset_test-schema.sql
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

/*!40103 SET TIME_ZONE='+00:00' */;
CREATE TABLE `t_charset_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `exec_info` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```
Please, can you check it again?
