### ISSUE TITLE
(myloader:37144) MySQL has not gone away yet

### ISSUE THREAD

**Issue by xuclachina** [maxbube/mydumper#157]
when i using myloader version 0.9.5 to restore my database,suddenly this happens:

** (myloader:37144): CRITICAL **: Error restoring mydb.mytable from file mydb.mytable.sql.gz: MySQL server has gone away
actually, MySQL has not gone away yet

my MySQL database version is MySQL-5.7.23,I don't know if it has anything to do with the MySQL version

**Comment by maxbube** [comment]
Hi @xuclachina I would guess that you have tables with large rows, please review on the mysql server `max_allowed_packet`

**Comment by davidducos** [comment]
Hi @xuclachina, can you test with latest version and tell me if you still have this issue?
