### ISSUE TITLE
[myloader] Add option to disable Galera Cluster (Wsrep) replication before importing

### ISSUE THREAD

**Issue by joffrey92** [maxbube/mydumper#159]
Hello,

by default myloader does set sql_log_bin = 0, which is useful.

When you use Galera Cluster (MySQL and Percona), setting sql_log_bin = 0 also disables wsrep replication.

When you use Galera Cluster (MariaDB), setting sql_log_bin = 0 doesn't disable wsrep replication. See: https://mariadb.com/kb/en/library/replication-and-binary-log-server-system-variables/#sql_log_bin

Could you please add an option in myloader, to support disabling (and/or enabling) wsrep replication ?

The command is:
`set session wsrep_on = 0`

Thanks in advance,
Joffrey

**Comment by davidducos** [comment]
We are going to be able to do this after merge: #370

**Comment by davidducos** [comment]
Please, can you check again as #370 has ben merged
