### ISSUE TITLE
Add complete-insert feature

### ISSUE THREAD

**Issue by mtxd** [maxbube/mydumper#16]
Why there is no equivalent of _mysqldump_ **--complete-insert** feature? It is necessary when moving data between databases with different structure. I have seen a patch provided early in 2014, however looks like it has never been merged.

**Comment by maxbube** [comment]
Hi,

I didn't see that patch, but I will check and include it. If not but we have more votes for this feature I can work on this.

Thanks

**Comment by mtxd** [comment]
https://code.launchpad.net/~ochedru/mydumper/complete-insert

**Comment by maxbube** [comment]
Hey, I created a PR for testing when completed I will merge it to master

**Comment by Ases** [comment]
@maxbube, I think this bug was fixed by https://github.com/maxbube/mydumper/commit/ca44245c33b714e939dd80f71f20170137011a95 in https://github.com/maxbube/mydumper/pull/18, so it can be closed.
