### ISSUE TITLE
equivalent option --ignore-table=database_name.table

### ISSUE THREAD

**Issue by arbabnazar** [maxbube/mydumper#160]
I just came across to this project and didn't find `--ignore-table=database_name.table` or might be missing it. Can somebody point it what is the equivalent option` --ignore-table=database_name.table` in mydumper. 

My scenario is really simple:
```
mysqldump --no-data database_name > db-structure.sql
mysqldump database_name --no-create-info --ignore-table=database_name.table1 --ignore-table=database_name.table2 > db-data.sql
```
How I can achieve the same thing with `mydumper`.

**Comment by maxbube** [comment]
Hi @arbabnazar mydumper has the --regex option for this. In your case would be something like to skip only table1 and table2 from database_name

`mydumper --regex '^(?!(database_name\.table[1-2]))'`

**Comment by davidducos** [comment]
Hi @arbabnazar, 
You can use also --omit-from-file to ignore tables. I'm closing this for now. Let me know if there is any other question.
