### ISSUE TITLE
[myloader] Add option to disable foreign key checks during load (enhancement)

### ISSUE THREAD

**Issue by UnixRonin** [maxbube/mydumper#163]
I have a test dump/reload running on a customer server right now.  The database contained just less than 500GB of table data and a little more than 300GB of indexes, has several tables with over 300 million rows, and makes extensive use of foreign key constraints.  Mydumper took slightly less than 2 hours to dump the data, with a chunk size of 10 million rows.  Myloader (with options -oed) has at this time been running for 69 hours.

Myloader currently lacks any option to disable foreign keys during load.  It is known that disabling foreign keys makes a very large difference in load time using mysqldump on this database.

**Comment by maxbube** [comment]
Hi @UnixRonin that is already present on myloader, I think the only improvement still to be added is to get advantage from fast index creation, but that would take some time to be implemented in the right way.
