### ISSUE TITLE
Could not read data from BASE: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by pilot513** [maxbube/mydumper#167]
Hello.
When dumping base BASE from MySQL NDB engine with prog. [ 0.9.5, built against MySQL 5.7.21-21] pagameters:
 -c -e -R -G -E -r 5000000 -t 12 -v 3 --lock-all-tables --kill-long-queries --long-query-guard 720
get error:

`(mydumper:38577): CRITICAL **: Could not read data from BASE.Property: Lock wait timeout exceeded; try restarting transaction`

Can you help me to resolve problem ?
Thanks!

**Comment by pilot513** [comment]
The table structure is:
`Property | CREATE TABLE `Property` (   
  `EntityId` bigint(20) NOT NULL DEFAULT '0',
  `Value` varchar(1000) NOT NULL DEFAULT '',             
  `EntityIds` varbinary(800) DEFAULT NULL,               
  PRIMARY KEY (`EntityId`,`Value`) USING HASH
) ENGINE=ndbcluster DEFAULT CHARSET=utf8 `

**Comment by maxbube** [comment]
Hi @pilot513 , hard to tell, did you check what is holding the lock while mydumper is waiting on it?

**Comment by pilot513** [comment]
Yes. What is the maximum value of --long-query-guard can be set?

**Comment by maxbube** [comment]
2147483647
