### ISSUE TITLE
parallel schema restore?

### ISSUE THREAD

**Issue by tsolodov** [maxbube/mydumper#169]
I understand that probably it works as designed, but what stops from parallel schema creation for myloader? In some cases it can save a lot of time...

Example:
I started myloader and I see that ony one thread is restoring schema. 
myloader --verbose 3  -d ./__FOLDER__/  -t 7 --enable-binlog --host=[HOST]

I am asking for I have 500K tables to be restored.... According to my calculations it will take 16 hours only to create schemas.

**Comment by maxbube** [comment]
Hi @tsolodov. I never benchmark it but there is not a global lock for this? In that case I won't expect much improvements.

**Comment by davidducos** [comment]
I reviewed the code, there are 2 things to consider:
* In this [PR](https://github.com/maxbube/mydumper/pull/286) there is an implementation of SYNC, in that case it stops until all the data jobs finished. In this case we need to SYNC until all the schema files are completed. 
* We also need to establish a way that we name functions in myloader, as we have add_schema and add_table on function restore_databases. I think that we need to rename add_table to push_table_into_queue and add_schema must be reimplemented and names as push_[table_]schema_into_queue, and use the add_schema in on each process_queue.

So, I'm going to postpone this implementation to 0.10.9, as I want to see #286 released on 0.10.7

**Comment by davidducos** [comment]
#286 was good, but not enough, we learn several things and now we implemented #352 which is much better and will allow us to implement this. 
I reschedule this implementation to 0.10.11 as we need to see how 0.10.9 goes. 
I will keep you posted

**Comment by davidducos** [comment]
#399 implemented the parallel table creation.
