### ISSUE TITLE
triggers restore(wrong pattern?)

### ISSUE THREAD

**Issue by tsolodov** [maxbube/mydumper#172]
step on a bug:

folder with multiple DB backups.
db naming:
XXXX_YYY_1000
XXXX_YYY_1001
XXXX_YYY_1000000000000000094

When you do restore:
of XXXX_YYY_1000:
myloader -o --source-db=XXXX_YYY_1000 --verbose 3  -d ./_FOLDER_WITH_BACKUP_/  -t 3 --enable-binlog --host=MySQL_is_amazing.org

what I found:

** (myloader:13412): CRITICAL **: Error restoring XXXX_YYY_1000000000000000094.table from file XXXX_YYY_1000000000000000094.table-triggers.sql: This version of MySQL doesn't yet support 'multiple triggers with the same action time and event for one table'.

My guess: after restoring data looks like myloader trying to load all triggers with "XXXX_YYY_1000*" pattern, so XXXX_YYY_1000000000000000094 database is matched.

**Comment by tsolodov** [comment]
Created & tested fix: 
https://github.com/tsolodov/mydumper/commit/ae9f08d3b64a08315e168235f017d88b6b7f7eed

**Comment by maxbube** [comment]
Thanks for PR @tsolodov!
