### ISSUE TITLE
load  Generated Columns    error

### ISSUE THREAD

**Issue by casanovaauyeung** [maxbube/mydumper#175]
we have some Generated Columns .report an error .when load the data .
** (myloader:361620): CRITICAL **: Error restoring hro.bbbbb from file hro.bbbbb.sql.gz: The value specified for generated column 'dtime' in table 'bbbbb' is not allowed.

thank you!

**Comment by maxbube** [comment]
Hi @casanovaauyeung this is not supported by the tool yet.

**Comment by davidducos** [comment]
Hi @casanovaauyeung , Can you check your issue again? as we currently support generated columns. 

Please, let me know so I can close this issue.
