### ISSUE TITLE
Differential backup only for tables that failed backup. : feature request

### ISSUE THREAD

**Issue by Yuutakasan** [maxbube/mydumper#178]
Hi. mydumper is a great software.

It is a situation that the Mysql server restarts every 15 minutes now, and I have to take a backup at the fastest speed before the Mysql server restarts. mydumper worked very fast, I could back up to about 80%, but after 20% I can not back up.

So I plan to create a shell script that restarts from the table data which I failed to backup and gets data but does Mydumper have such a function, too?

**Comment by maxbube** [comment]
Hi @Yuutakasan I would rather start from troubleshooting mysql restart/crash.

Also what you are requesting or trying to script is not an option as is impossible to ensure a consistent backup.

**Comment by Yuutakasan** [comment]
thank you for comment.
I understood.
