### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by leshalv** [maxbube/mydumper#182]
执行msql远程导出命令提示Segmentation fault (core dumped)错误
![](https://user-images.githubusercontent.com/30397655/54181766-8d8e8e00-44da-11e9-94c4-9814c7b1ebd0.png)

**Comment by 799983050** [comment]
你的是阿里云的RDS吗？我的是报** (mydumper:22117): WARNING **: 11:21:33.693: Executing in no-locks mode, snapshot will notbe consistent
Segmentation fault

**Comment by Esysteme** [comment]
same there :

```
7:28:28	bash: line 1:     6 Segmentation fault      (core dumped) mydumper -h $RD_NODE_HOSTNAME -G -R -E -u backup -p $RD_OPTION_BACKUP_PASSWORD -v 3 -r 100000 -o /export/$BACKUP_DATE
```


mydumper 0.9.1, built against MySQL 10.1.20-MariaDB

**Comment by Esysteme** [comment]
this problem happen on : 
MariaDB [(none)]> select version();
+---------------------------------------------+
| version()                                   |
+---------------------------------------------+
| 10.3.12-MariaDB-1:10.3.12+maria~stretch-log |
+---------------------------------------------+
1 row in set (0.000 sec)

+ Galera Cluster

**Comment by dupondje** [comment]
Any chance to test this against the current git + have a coredump?

**Comment by shijiunv** [comment]
When exporting a table with commas with mydumper, system prompt that Segmentation fault (core dumped) .

**Comment by shijiunv** [comment]
When I run mydumper for more than 1 hour,  Segmentation fault.

**Comment by fredricj** [comment]
> 
> 
> When exporting a table with single quotes, system prompt that Segmentation fault (core dumped) .
Could you provide a test case for this?

**Comment by davidducos** [comment]
We need feedback to proceed. Closing it.
https://github.com/maxbube/mydumper/wiki/Support
