### ISSUE TITLE
In the recovery from the slave backup to another slave , the master and slave are inconsistent

### ISSUE THREAD

**Issue by liuqian1990** [maxbube/mydumper#183]
s-master
   s1-slave1

I want to build another slave s2-slave.

  ./mydumper --trx-consistency-only --complete-insert --compress --threads=8 -hs1-slave1  -u  -p   --rows 500000  --logfile=/tmp/mydumper.log --outputdir=mydumper_backup/
But the data is inconsistent after recovery.

**Comment by davidducos** [comment]
Hi @liuqian1990,

I did this to try to simulate your issue:
`for i in $(seq 1 600); do echo 'insert into test (val) values ("12345678901234567890123456789012345678901234567890");' | mysql load2; sleep 0.1; done;
`
while I run a mydumper similar to yours:
`mydumper --trx-consistency-only --complete-insert --compress -B load2 -v 3 --rows 50000 --outputdir=mydumper_backup/
`
But data is consistent:
```
root@ubuntu-focal:~/mydumper_backup# gzip -cd load2.test.00030.sql.gz | tail -2
(1834993,"12345678901234567890123456789012345678901234567890"),
(1834994,"12345678901234567890123456789012345678901234567890");
```
According to the metadata position
```
root@ubuntu-focal:~/mydumper_backup# cat metadata
Started dump at: 2021-03-17 14:56:30
SHOW MASTER STATUS:
	Log: binlog.000001
	Pos: 34774117
```
And binlog:
```
### INSERT INTO `load2`.`test`
### SET
###   @1=1834995 /* INT meta=0 nullable=0 is_null=0 */
###   @2='12345678901234567890123456789012345678901234567890' /* VARSTRING(50) meta=50 nullable=1 is_null=0 */
# at 34774397
#210317 14:56:30 server id 1  end_log_pos 34774428 CRC32 0xb769bed6     Xid = 2498
```
Please, provide a test case so I can troubleshoot this issue.

**Comment by davidducos** [comment]
Closing this issue based on this: https://github.com/maxbube/mydumper/wiki/Support
