### ISSUE TITLE
How can I exclude the following tables in mydumper 

### ISSUE THREAD

**Issue by montes2012** [maxbube/mydumper#184]
How can I exclude the following tables in mydumper

database name : W_ACAM$HDF$CM
Table: 
ACAM$HDF$CM$$2016_12_09
ACAM$HDF$CM$$H2016_12_09

how to build regex for this case ?

**Comment by maxbube** [comment]
Hi @montes2012, something like this must do it

```
./mydumper --regex '^(?!(W_ACAM\$HDF\$CM\.ACAM\$HDF\$CM\$\$2016_12_09|W_ACAM\$HDF\$CM\.ACAM\$HDF\$CM\$\$H2016_12_09))'
```
