### ISSUE TITLE
critical error if column names are a keyword

### ISSUE THREAD

**Issue by caffeinejolt** [maxbube/mydumper#196]
If you have tables or columns named with one of these names: https://dev.mysql.com/doc/refman/8.0/en/keywords.html

It fails to dump that table.

Possibly use backticks around names to get around this - this is what mysqldump does

**Comment by caffeinejolt** [comment]
this is solved (with limited testing) by tweaking GString * get_insertable_fields:

 gchar *query = g_strdup_printf("select CONCAT('`', COLUMN_NAME, '`') as COLUMN_NAME from information_schema.COLUMNS where TABLE_SCH
EMA='%s' and TABLE_NAME='%s' and extra not like '%%GENERATED%%'", database, table);

**Comment by caffeinejolt** [comment]
github auto-formatting borked above - but you get the idea

**Comment by caffeinejolt** [comment]
the same handling should really be applied to table names - but at least that is less common

**Comment by fredricj** [comment]
Should be fixed by #216

**Comment by maxbube** [comment]
Fixed by #216
