### ISSUE TITLE
speeding up dump/restore

### ISSUE THREAD

**Issue by tsolodov** [maxbube/mydumper#197]
Hi.

My case:
1. 4.5K + DBs.
2. 90K+ stored procedures
3. dumping all databases
4. MySQL 5.6

1. show procedure status where db = 'XXX' takes 4-5 secs(it's using filesort every time, can't improve it)
show procedure status where db = 'XXXX';
### 7 rows in set (5.05 sec)
So only dumping Stored procedures will be ~ 6-7 hours. Can it be done with approach:
1.  read it once and keep in memory to avoid selecting data for every DB? As I understand you need "DB"->"Stored procedure name" mapping to build show create procedure statement.
2.  table schemas dump is done using single thread. Can it be changed? 
3.  table schemas restore is done using single thread. Can it be changed?

**Comment by dupondje** [comment]
https://github.com/maxbube/mydumper/commit/95d39619bd12687d2d8e6cc328c3df7f3b091b1b

Fixes all/some of these issues.

**Comment by tsolodov** [comment]
will test, thanks for update!
