### ISSUE TITLE
mydumper interrupt replication, json data type

### ISSUE THREAD

**Issue by msj12** [maxbube/mydumper#198]
mysql 5.7.16.
we have a VIRTUAL GENERATED COLUMN from a json field,  When using mydumper for backup, the replication will be interrupted.
slave SQL thread error: `Error 'Cannot create a JSON value from a string with CHARACTER SET 'binary'.' on query.`  if I restart sql thread,  Everything is normal again.

**Comment by pendledt** [comment]
Pull request to fix this issue is here https://github.com/maxbube/mydumper/pull/154
