### ISSUE TITLE
Slow mydumper table dump

### ISSUE THREAD

**Issue by agolev** [maxbube/mydumper#200]
Hello
I have a table with 25000000 rows that takes up 3Gb of space.
Here the table info
![table_info](https://user-images.githubusercontent.com/45493699/63337213-41792c80-c349-11e9-8dd0-1c395181657a.png)

And dumping this table with mydumper takes over 12 minutes, while musqldump do it for 3 minutes
Mydumper is 4 times slower than mysqldump 
And I can not understand why
Using chunks, locks, queries per transaction not saving the situation

**Comment by maxbube** [comment]
I can't tell whats the reason, but I would look into IO saturation due to multiple threads that you disk layer cant handle.
