### ISSUE TITLE
myloader needs disk space in /tmp

### ISSUE THREAD

**Issue by LiohMoeller** [maxbube/mydumper#202]
While trying to import a database using myloader, I got an error message like: Error writing to /tmp/XadW23 - no space left on device. Which part of myloader tries to write/cache in /tmp? Is there a way to configure a different tempdir?

![myloader](https://user-images.githubusercontent.com/1267594/64153665-9af45780-ce2f-11e9-8dbc-3cb4de474e9f.png)

**Comment by tanji** [comment]
That's a MySQL error, change the `tmpdir` directive in `my.cnf` to point to a partition with more disk space.
