### ISSUE TITLE
Flush logs

### ISSUE THREAD

**Issue by stefanhipfel** [maxbube/mydumper#203]
Hi,

in mysqldump there is an option to flush the logs, right  before the dump is created.
https://dev.mysql.com/doc/refman/5.5/en/mysqldump.html#option_mysqldump_flush-logs

How would one achieve the same with mydumper? Lock the tables and call flush via mysqladmin before running mydumper?

Thanks in advance

**Comment by tsolodov** [comment]
could you please explain your case? May be I can suggest something after understating whole process.

**Comment by maxbube** [comment]
Hi Im closing this as there were no feedback on a valid use case. In any case a new ticket can be opened  with the details.

Cheers
