### ISSUE TITLE
Compile failed: error: implicit declaration of function 'g_sequence_lookup'

### ISSUE THREAD

**Issue by kevinbin** [maxbube/mydumper#205]
OS: rhel 6.5 
Compile failed:  /tmp/mydumper-master/mydumper.c:418: error: implicit declaration of function 'g_sequence_lookup'

oot@Mysql-mdb02b mydumper-master]# cmake .
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/mysql/libmysqlclient_r.so;/usr/lib64/libz.so;/usr/lib64/libpthread.so;/usr/lib64/libcrypt.so;/usr/lib64/libnsl.so;/usr/lib64/libm.so;/usr/lib64/libpthread.so;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Found ZLIB: /lib64/libz.so.1
-- checking for one of the modules 'glib-2.0'
--   found glib-2.0, version 2.26.1
-- checking for one of the modules 'gthread-2.0'
--   found gthread-2.0, version 2.26.1
-- checking for module 'libpcre'
--   found libpcre, version 7.8
-- Found PCRE: /usr/include

WARNINGUnable to find Sphinx documentation generator
-- ------------------------------------------------
-- MYSQL_CONFIG = /usr/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/mydumper-master

[root@Mysql-mdb02b mydumper-master]# make && make install
Scanning dependencies of target mydumper
[ 12%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
cc1: warnings being treated as errors
/tmp/mydumper-master/mydumper.c: In function 'check_skiplist':
/tmp/mydumper-master/mydumper.c:418: error: implicit declaration of function 'g_sequence_lookup'
make[2]: *** [CMakeFiles/mydumper.dir/mydumper.c.o] Error 1
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
make: *** [all] Error 2
[root@Mysql-mdb02b mydumper-master]# make
[ 12%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
cc1: warnings being treated as errors
/tmp/mydumper-master/mydumper.c: In function 'check_skiplist':
/tmp/mydumper-master/mydumper.c:418: error: implicit declaration of function 'g_sequence_lookup'
make[2]: *** [CMakeFiles/mydumper.dir/mydumper.c.o] Error 1
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
make: *** [all] Error 2

**Comment by fredricj** [comment]
PR #82 (commit 5a3fc191354e64657edc45a610dabeea75e42544) implicitly increased the requirement of glib to 2.28
