### ISSUE TITLE
when --source-db specified routines are not restored.

### ISSUE THREAD

**Issue by tsolodov** [maxbube/mydumper#206]
Hi, Subj.

https://github.com/maxbube/mydumper/blob/2cdd78599ea7e13f36c6e8a09051814f6bd1564a/myloader.c#L338

I think in 0.9.5 there is not such issue:
9.5:    if (!source_db || g_str_has_prefix(filename, source_db)){
10:     if (!source_db ||
       g_str_has_prefix(filename, g_strdup_printf(“%s.“, source_db))) {
Filename is DBNAME-schema-post.sql,
not DBNAME.schema-post.sql

myloader 0.10.0

**Comment by tsolodov** [comment]
BTW, I've validated that after the fix stored procedures have been restored.

**Comment by tsolodov** [comment]
Please validate summited fix.(552b57d) I was able to test it on my environment. 

p.s. please ignore pull request 31f9fd1

**Comment by maxbube** [comment]
Thanks @tsolodov I will review it and if OK will be included in the next release.
