### ISSUE TITLE
CentOS + mydumper

### ISSUE THREAD

**Issue by Esysteme** [maxbube/mydumper#209]
yum install https://github.com/maxbube/mydumper/releases/download/v0.9.5/mydumper-0.9.5-1.el7.x86_64.rpm

this file seem doesn't exist

**Comment by stefangabos** [comment]
It's a `-2` instead of `-1`
so
`yum install https://github.com/maxbube/mydumper/releases/download/v0.9.5/mydumper-0.9.5-2.el7.x86_64.rpm`

**Comment by Esysteme** [comment]
thx, one idea with ?  (on CentOs 8)
mydumper: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

dnf search libss
Aucune correspondance trouvée.

**Comment by emersonmartins8** [comment]
Hello @Esysteme.
I have the same error in MySQL in CentOs 8. Could be resolved it?
