### ISSUE TITLE
myloader segmentation faults if directory contains sql file with 1 dot in filename

### ISSUE THREAD

**Issue by fredricj** [maxbube/mydumper#210]
myloader segmentation faults if the directory contains a file *.sql without 2 dots in it

#0  0x00007ffff5521457 in ____strtoull_l_internal () from /lib64/libc.so.6
#1  0x00000000004027bd in add_table (filename=<optimized out>, conf=0x7fffffffde40) at /home/fredric/mydumper-0.9.5/myloader.c:410
#2  0x00000000004034a6 in restore_databases (conf=conf@entry=0x7fffffffde40, conn=conn@entry=0x62d810) at /home/fredric/mydumper-0.9.5/myloader.c:237
#3  0x0000000000402410 in main (argc=1, argv=0x7fffffffdf78) at /home/fredric/mydumper-0.9.5/myloader.c:178

(gdb) l myloader.c:410
405             rj->filename= g_strdup(filename);
406             j->type= JOB_RESTORE;
407             gchar** split_file= g_strsplit(filename, ".", 0);
408             rj->database= g_strdup(split_file[0]);
409             rj->table= g_strdup(split_file[1]);
410             rj->part= g_ascii_strtoull(split_file[2], NULL, 10);
411             g_async_queue_push(conf->queue, j);
412             return;
413     }
414

**Comment by davidducos** [comment]
https://github.com/maxbube/mydumper/issues/179
