### ISSUE TITLE
Myloader: Prevent multiple threads from restoring chunks to same table

### ISSUE THREAD

**Issue by fredricj** [maxbube/mydumper#211]
When using myloader with multi threads to restore a chunked backup sometimes more than 1 thread try to load chunks to the same table causing a lot of table locks instead of working on different tables which slows down the restore.

Extreme example:
$myloader -d /path/to/dump/ -o -a -u root --threads 8 --verbose 3 -s archive
Enter MySQL Password:
** Message: 11:42:35.008: 8 threads created
** Message: 11:42:35.009: Dropping table or view (if exists) `archive`.`events`
** Message: 11:42:36.793: Creating table `archive`.`events`
** Message: 11:42:36.809: Thread 1 restoring `archive`.`events` part 3
** Message: 11:42:36.810: Thread 2 restoring `archive`.`events` part 1
** Message: 11:42:36.810: Thread 3 restoring `archive`.`events` part 4
** Message: 11:42:36.810: Thread 4 restoring `archive`.`events` part 6
** Message: 11:42:36.810: Thread 5 restoring `archive`.`events` part 2
** Message: 11:42:36.810: Thread 6 restoring `archive`.`events` part 5
** Message: 11:42:36.810: Thread 7 shutting down
** Message: 11:42:36.810: Thread 8 shutting down
...

**Comment by maxbube** [comment]
Hi @fredricj the reason to use chunks is to able able to restore a single table with multiple threads, if in your case is slowing down the restore you can just not use `--rows` in mydumper.

Cheers
