### ISSUE TITLE
LOCK BINLOG FOR BACKUP not valid on Percona Server 8.0

### ISSUE THREAD

**Issue by macboy012** [maxbube/mydumper#218]
As of Percona Server 8.0 `LOCK BINLOG FOR BACKUP` has been removed. See the **Removed Syntax** section [Changed in Percona Server 8.0](https://www.percona.com/doc/percona-server/LATEST/changed_in_version.html#features-removed-from-percona-server-version)

They say it's been replaced by the `log_status` table.

I'd offer to submit a pull request but I'd need some guidance to understand how the `log_status` table would replace the existing locking and accessing binlog information, at least to me, it doesn't look like an obvious 1 to 1 mapping. That and it'd need to read feature flags from to even know which to use.

**Comment by maxbube** [comment]
Hi @macboy012 `log_status` can't replace LBFB in several scenarios. We need to fail back to FTWRL unless Percona reintroduce that locks for PS8.
