### ISSUE TITLE
Replication broken on slave after using mydumper

### ISSUE THREAD

**Issue by aleksystasiak** [maxbube/mydumper#219]
Mydumper version: mydumper 0.9.5, built against MySQL 5.7.21-21
Mysql version: Server version: 5.7.28-31-log Percona Server (GPL), Release '31', Revision 'd14ef86'
Switches used: mydumper -u $user -p $pass -t $threads --triggers --routines --events -v 3 --rows=25000 --trx-consistency-only --logfile /var/log/backup/dumper_$timestart.log -B $db -c -e -o $DIR
After dumping database and stopping replication, replication fails after starting slave.

> Last_SQL_Errno: 3144
>                Last_SQL_Error: Error 'Cannot create a JSON value from a string with CHARACTER SET 'binary'.' on query.

I was able to reproduce this behaviour on freshly created slaves

**Comment by maxbube** [comment]
Duplicate by #224
