### ISSUE TITLE
suggestions for huge tables and multiple threads

### ISSUE THREAD

**Issue by jdanilson** [maxbube/mydumper#220]
We are dealing with a need to dump and load a large database consisting of 200+ tables.  Most tables are reasonable, but six are huge with hundreds of millions of rows.  They range in size from 160G to 700G.  

Running with 20 threads, I end up with all threads but a few exhausted after processing the smaller tables, so that by the time it's been running 3+ hours I only have a few threads processing these huge tables.    Optimally I think it would be beneficial to allocate lots of threads (all!)  to these huge tables first in descending order by size.  

Is the only way to do that by listing the tables on an include list in the order that I want them dumped?  

Thanks
John

**Comment by maxbube** [comment]
Hi @jdanilson, 

If the huge tables have numeric primary keys you can use the `--rows` option.

Cheers
