### ISSUE TITLE
Change of column extra values in the INFORMATION_SCHEMA COLUMNS table in MySQL 8.0

### ISSUE THREAD

**Issue by huangzhiyong** [maxbube/mydumper#221]
In MySQL 8.0, expressions were introduced, causing the COLUMNS table column extra to change. Using mydumper would drop some columns, which caused problems.
refer: https://dev.mysql.com/doc/refman/8.0/en/columns-table.html#extra

example:
CREATE TABLE `b` (
    ->   `id` int(11) NOT NULL,
    ->   `aAt` datetime NOT NULL,
    ->   `cAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ->   `uAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ->   PRIMARY KEY (`id`)
    -> ) ENGINE=InnoDB;

select COLUMN_NAME,extra from information_schema.COLUMNS where  table_name='b';
+-------------+-------------------+
| COLUMN_NAME | EXTRA             |
+-------------+-------------------+
| aAt         |                   |
| cAt         | DEFAULT_GENERATED |
| id          |                   |
| uAt         | DEFAULT_GENERATED |
+-------------+-------------------+

**Comment by huangzhiyong** [comment]
mydumper detect generated fields code:
gboolean detect_generated_fields(MYSQL *conn, char *database, char *table) {
...
  gchar *query = g_strdup_printf(
      "select COLUMN_NAME from information_schema.COLUMNS where "
      "TABLE_SCHEMA='%s' and TABLE_NAME='%s' and extra like '%%GENERATED%%'",
      database, table);
  mysql_query(conn, query);
  g_free(query);
...
}

**Comment by sundysundy** [comment]
mysql 8.0          like '%%VIRTUAL GENERATED%%'

**Comment by fredricj** [comment]
In mysqldump the related check only looks for "virtual generated" and "stored generated" perhaps mydumper should do the same?

**Comment by davidducos** [comment]
This was fixed on 0.10.3
