### ISSUE TITLE
Add libatomic1 in dependencies of deb

### ISSUE THREAD

**Issue by mioux** [maxbube/mydumper#222]
When installing from deb (stretch version), and you want to run mydumper, there is an error message 

    mydumper: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

You can solve this by installing libatomic1

FYI : I use mariadb 10.4 from mariadb repo, I don't know if the debian version of mariadb comes with this dependence

**Comment by matthewlenz** [comment]
Not sure why this was labeled as an enhancement.  It's a bug.

**Comment by davidducos** [comment]
Hi @matthewlenz,

I tested what you mentioned:
```
root@stretch:~# dpkg -r libperconaserverclient20 libgcc-6-dev percona-server-server-5.7 percona-server-client-5.7 libatomic1 libperconaserverclient20 libstdc++-6-dev gcc-6 g++-6 g++ gcc libperconaserverclient20-dev 
root@stretch:~# mydumper --version
mydumper: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```
So, yes, if I removed all the packages that libatomic depends, I see the same error that you reported. I will be investigating this and let you know what is the outcome. btw, yes, it is a bug.

**Comment by matthewlenz** [comment]
@davidducos thanks!  As far as I know you just need to add libatomic as a dependency in package/deb/control

**Comment by davidducos** [comment]
Yes, I saw that, but it will take some time to test it, as I'm starting to build the 0.10.3 which will be released this month. 

Stay tune, I will let you know how it goes. 

BTW, this is issue, is related to the mydumper_builder, currently I'm using this repo: https://github.com/davidducos/mydumper_builder. I have the idea of made it a submodule of mydumper... but not sure yet... I will see.
