### ISSUE TITLE
can the tool support where condition like mysqldump?

### ISSUE THREAD

**Issue by jmbkeyes** [maxbube/mydumper#223]
Can the tool support where condition like mysqldump? or will support later?

**Comment by davey** [comment]
+1!
We'd need that as well.
Use case: we have a huge database (14 TB) with lots of time series data. For emergency recovery, we'd only like to have e.g. the latest two months of data in a special dump - this speeds up emergency recovery (which does not need all data right away) a lot - main interest then would be to get all systems up and running as fast as possible.
