### ISSUE TITLE
Cannot create a JSON value from a string with CHARACTER SET 'binary'.

### ISSUE THREAD

**Issue by segedunum** [maxbube/mydumper#224]
I'm still getting this problem when restoring with 0.9.5 on Ubuntu. https://github.com/maxbube/mydumper/issues/46

`Error restoring ias_production.ias_note from file database.table.sql: Cannot create a JSON value from a string with CHARACTER SET 'binary'.`

mydumper seems to be OK as previous version flagged this up, but myloader is still throwing this error.

**Comment by Yuutakasan** [comment]
me too.

**Comment by dongdongvs6** [comment]
get the same problem with myloader.

**Comment by Yuutakasan** [comment]
@dongdongvs6 
It works if you modify it in this way as a workaround.

gzip --decompress <<mydumper_output_dir>>/<<target_schema>>.<target_table>>.sql.gz --stdout | sed '1,1 s/SET NAMES binary/SET NAMES utf8mb4/g' | gzip -c > <<mydumper_output_dir>>/<<target_schema>>.<target_table>>.sql.gz

In short, it can be avoided by changing the first line of the table dump containing the json type as follows.

SET NAMES binary
↓
SET NAMES utf8mb4

**Comment by dongdongvs6** [comment]
why not support a param in mydumper, that can help us specify the charset for table?

**Comment by dongdongvs6** [comment]
I think binary is OK for most case, and it is safe. So I think if mydumper support --charset is much better.

**Comment by Yuutakasan** [comment]
It's open source, so if you need it, you should modify the code and send a pull request.
I'm not a developer and I'm not good at C, so I can only offer workarounds.

**Comment by maxbube** [comment]
Hi, this is a known issue, and as it seems it could be a simple fix Im worried about all other implications on changing the charset. I think it need to be set based on the source, but the effort on doing it that way is above my actual available time.

**Comment by maxbube** [comment]
Closing as duplicate for #198
