### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mkraibt** [maxbube/mydumper#229]
Is there any method with with i can access this feature in windows environment??

**Comment by maxbube** [comment]
Hi @mkraibt maybe the easiest option would be to use docker, there are plenty of images in dockerhub https://hub.docker.com/search?q=mydumper&type=image

**Comment by Dibbyo456** [comment]
Or you can use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).
