### ISSUE TITLE
CentOS Error

### ISSUE THREAD

**Issue by obissick** [maxbube/mydumper#23]
Got this error when installed from rpm package.
`mydumper: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory`

**Comment by mathnode** [comment]
From where did you download an RPM? You should contact the maintainer of the RPM package with details of your Linux Distribution version and the error message.

**Comment by nkadel-skyhook** [comment]
Mydumper was probably compiled with default MySQL 5.7 libraries. Not evil and of itself, but you should be able to use "yum install filename" and get these dependencies resolved.

**Comment by maxbube** [comment]
You can install mydumper for the releases section, I added rpm files. Just run 

`sudo yum install https://github.com/maxbube/mydumper/releases/download/v0.9.3/mydumper-0.9.3-41.el7.x86_64.rpm`

**Comment by nkadel-skyhook** [comment]
Fabulous! Thank you!

**Comment by nkadel-skyhook** [comment]
Is there an SRPM to go with it?
