### ISSUE TITLE
Mydumper: suggested improvements

### ISSUE THREAD

**Issue by sjmudd** [maxbube/mydumper#231]
Having used `mydumper` for the first time recently a couple of improvements come to mind:
* show periodic progress of loads or dumps in `verbose 3` mode e.g. show table name, number of rows read or written so far and do so every 60 seconds. That helps provide an indication of progress.
* when shutting down a thread as it has no work to do indicate how many are left running. This makes it easier towards the end of a run to see how much work is left to do.
* final but maybe harder suggestion. Chunk dumps or loads of larger tables in parallel if possible. I had a last table 5x bigger than the rest so ended up with mydumper dumping this single threaded with all other threads being idle. If there's a way to handle this dumping in parallel you'll allow for the dump and loads to be faster.

Other points
* also clarify default behaviour with `--enable-binlog` when loading data. I think this has to be enabled explicitly so important if using replication that this is clear.
* documentation is not 100% clear about behaviour when loading data if the tables already exist. Would be good to say that the create table will fail but data will be loaded anyway which was what I wanted for the specific use case I had.

Other than that thanks for the tool. It worked nicely.

**Comment by maxbube** [comment]
Hi @sjmudd thanks for the feedback!

I will take in account this, also want to clarify the 3rd point. mydumper already does that if you set `--rows` the only limitation is that the PK needs to be a numeric value.
