### ISSUE TITLE
--rows SMALLINT support

### ISSUE THREAD

**Issue by ihanick** [maxbube/mydumper#237]
16-bit integers are still could be useful to produce a specific amount of --rows in output files:
For example in case of: `create table t(id1 smallint, id2 int, c char(200), primary key(id1,id2));`
we can create a backup with:
~~~
mydumper --user=root --password=secret --regex '^test[.]t$' --rows 60000

wc -l export-20200306-034008/test.t.0*sql|head
   72824 export-20200306-034008/test.t.00000.sql
   70853 export-20200306-034008/test.t.00001.sql
~~~
Could be done after a trivial patch:
~~~
diff --git a/mydumper.c b/mydumper.c 
index 903d816..b0a2ba6 100644 
--- a/mydumper.c 
+++ b/mydumper.c 
@@ -2217,6 +2217,7 @@ GList *get_chunks_for_table(MYSQL *conn, char *database, char *table, 
   case MYSQL_TYPE_LONG: 
   case MYSQL_TYPE_LONGLONG: 
   case MYSQL_TYPE_INT24: 
+  case MYSQL_TYPE_SHORT: 
     /* static stepping */ 
     nmin = strtoll(min, NULL, 10); 
     nmax = strtoll(max, NULL, 10);
~~~

**Comment by maxbube** [comment]
Hi @ihanick , I guess is not a problem to include it. could you please send a PR? If not don't worry I will do it for next release.

Cheers

**Comment by VMEMachuca** [comment]
This change was not included in v0.10.1

**Comment by davidducos** [comment]
@VMEMachuca this will be included in v0.10.3

**Comment by VMEMachuca** [comment]
@davidducos it seems like this change would be available on v.0.10.3 which is expected to be out on March

**Comment by davidducos** [comment]
@VMEMachuca you are right, yesterday I have been working on the packages, so it might be released next week.

**Comment by VMEMachuca** [comment]
@davidducos - Is the release still on schedule? If yes, where would I be able to find it?

**Comment by davidducos** [comment]
Hi @VMEMachuca, the draft of the new release is already prepared. As soon as I get a review, I will be publishing. I take the opportunity to [ask for collaborators](https://github.com/maxbube/mydumper/issues/284), I'm trying to keep the project as updated as possible, so, any help is welcome!

**Comment by VMEMachuca** [comment]
Hi @davidducos, I had never participated in such an effort but, would you mind to elaborate for me? I would love to be able to collaborate with you.

**Comment by davidducos** [comment]
@VMEMachuca, we need people that want to:
- review the code on PR which also implies to test it.
- review issues and give support to other users or create PR with fixes.
- implement feature requested or internal projects based on alignments that we want for MyDumper. For instance, currently, we don't have a good testing platform, would be nice to discuss what is the best approach.
If you want to help, you might need to start reviewing issues and giving your opinion, it will be much appreciated!!
