### ISSUE TITLE
How i can hide "password" when mydumper worked (in process list) ?

### ISSUE THREAD

**Issue by pilot513** [maxbube/mydumper#238]
Hello.
When mydymper/myloader worken, i see 'password' as unprotected parameter in process list. (ps, top,htop etc.) 
How i can hide "password" when mydumper worked ?

Thanks!

**Comment by maxbube** [comment]
Hi mydumper/myloader can read credentials from ~/.my.cnf as any mysql client.

Cheers

**Comment by pilot513** [comment]
Thanks!
Will he use this file himself if it is created, or should it be transferred in the command line?

**Comment by maxbube** [comment]
you just need to create it under the user's home directory which is running mydumper
