### ISSUE TITLE
output the resulting SQL to stdout

### ISSUE THREAD

**Issue by drzraf** [maxbube/mydumper#24]
If possible (maybe at the user-defined price of reducing parallelism?), it would be more "pipe-friendly" facilitating ssh and more generally remote-use.

**Comment by maxbube** [comment]
Hi @drzraf we have already mysqldump for that. What I could try to do in some future :) is to allow a destination db server to be set. That would help in use cases like mysqldump | mysql.

**Comment by drzraf** [comment]
but mysqldump does not support `PCRE for specifying database and tables inclusions and exclusions` (which is IMHO the whole selling-point of mydumper)
