### ISSUE TITLE
mydumper-load-data-local-security BUG

### ISSUE THREAD

**Issue by 99yun** [maxbube/mydumper#242]
Attacker msyql-server can use this bug to read all files on the mydumper client machine!

**Comment by 99yun** [comment]
![image](https://user-images.githubusercontent.com/33450817/80470929-4466fb00-8975-11ea-90cd-864ce0f09d39.png)

**Comment by dupondje** [comment]
More information please? This doesn't really give much information to do anything about it ...

**Comment by davidducos** [comment]
Closing as it is incomplete.
