### ISSUE TITLE
EL 8 package for MyDumper

### ISSUE THREAD

**Issue by dfisek** [maxbube/mydumper#246]
RHEL 8 has been out there for more than a year now.

It would be nice to have an el8 package.

**Comment by bampolsk** [comment]
I agree.... we are migrating a large database from CentOS 6 to CentOS 8, and it would be very nice to be able to do with mydumper, myloader.

**Comment by davidducos** [comment]
Latest release has a package for CentOS8. We had to remove support for CentOS6
