### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by dupondje** [maxbube/mydumper#247]
Hi,

Are we waiting for something to tag a new release?
Some quite important fixes are added since the previous release, and it would be nice to have them tagged into a new release. Which we can then ship to debian for example.

Also, please build package for debian 10 :)

Would be nice to get some pull requests added also. But ok :)

**Comment by verwilst** [comment]
bump

**Comment by dupondje** [comment]
@maxbube : Any status? Eventually I could assist a bit in reviewing/fixing issues.

**Comment by maxbube** [comment]
Hey! Hope next week I would have some time to run tests so I can do release and build the packages.

**Comment by dupondje** [comment]
@maxbube: Any ETA?

I see tons of pull requests open etc. But everything seems to be stalled ...
Would be nice to get some action here !

**Comment by richlv** [comment]
Noticed a few issues that could be closed, but not sure how to initiate that.
@maxbube, perhaps it's worth taking up the offer from @dupondje to help?

**Comment by verwilst** [comment]
@maxbube I can appreciate the fact that maintaining mydumper is currently too much effort for you personally, but please allow other people to take a more active role on this project, since in its current state it's becoming less and less an option for reliable backups.

**Comment by davidducos** [comment]
Hi @verwilst, @maxbube asked me a couple of months ago to start taking some responsibilities of this project. My intention is to help as much as possible. I'm already working on the next release which I was trying to deliver before the year ends but I it won't be possible, I will be able to do it on January next year. 
I will ask a bit of patience here, as once that I deliver the first, the idea is to stat to release more often. Any comment or suggestions are always welcome.

**Comment by richlv** [comment]
Thank you both so much, sounds very promising :)

A bit offtopic for this issue, but issues #277 (resolved request for help) and #266 (bug in external library) might be closable.

**Comment by verwilst** [comment]
Are we still on for a January release?

**Comment by davidducos** [comment]
Hi @verwilst, I worked on it last week, @maxbube reviewed on Friday and I will be releasing today.

Cheers

**Comment by verwilst** [comment]
That's an awesome present for 2021! :-)
Looking forward to it and thanks for the headsup!

**Comment by davidducos** [comment]
New release tagged, I think that March will be available version 0.10.3. Closing this now as no need to keep it open.
