### ISSUE TITLE
mydumper: Possible deadlock and downtime with Galera Cluster and Consistent reads (wsrep_sync_wait / wsrep_causal_reads)

### ISSUE THREAD

**Issue by joffrey92** [maxbube/mydumper#253]
Hello,

With Galera replication and wsrep_sync_wait enabled, it can happen that mydumper threads wait for another write to complete before releasing flush tables with read lock (FTWRL). This can create a deadlock and downtime:

- FTWRL is hold by one mydumper thread.
- new write coming from other galera node is waiting after FTWRL.
- first query from mydumper is waiting after write (wsrep_sync_wait)
- all queries are stacking.
- FTWRL is not released.
- mydumper needs to be stopped to resolve situation.

As wsrep_sync_wait is a session variable, mydumper could disable it. Consistency is ensured via InnoDB snapshot.

https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-sync-wait
Old variable name is deprecated and was named wsrep_causal_reads:
https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-causal-reads

I will try if I can do a Test case and PR for this issue,

Cheers,
Joffrey

**Comment by davidducos** [comment]
The fix will be to check if the server is using Galera then send a `SET SESSION wsrep_sync_wait = 0;` per thread, right? looks something simple... do you think that you could implement it and push a PR?

**Comment by davidducos** [comment]
Ok, I did some testings:
```
[root@pxc571 ~]# while true ; do echo 'insert into issues_253 (val) values (ceiling(rand()*100));' | mysql issues_253; sleep 0.01; done
^C

[root@pxc572 ~]# rm -rf issues_253; mydumper --no-backup-locks -B issues_253 -o issues_253 -v 4
** Message: Server version reported as: 5.7.32-35-57-log
** Message: Connected to a MySQL server
** Message: Started dump at: 2021-04-30 19:13:33

** Message: Written master status
** Message: Thread 1 connected using MySQL connection ID 203
** Message: Thread 2 connected using MySQL connection ID 204

** (mydumper:17219): CRITICAL **: Failed to start consistent snapshot: Lock wait timeout exceeded; try restarting transaction
```
I had to set --no-backup-locks, as the FTWRL is not send to the database if it is not required. However, the issue that I found was trying to execute:
```
START TRANSACTION /*!40108 WITH CONSISTENT SNAPSHOT */
```
