### ISSUE TITLE
mydumper dump big table failed, because of dumping time longer than max_execution_time

### ISSUE THREAD

**Issue by dba-kit** [maxbube/mydumper#257]
ERROR content is: 
```
[ERROR] - Could not read data from ****.***: Query execution was interrupted, maximum statement execution time exceeded
```
To fix it, Now I must login a Super User, and `set global max_execution_time=0`, but In fact
we only need set the variable with SESSION scope;
So I suggest add a new argument, like `--max_execution_time`, and set the variable with SESSION scope at the beginning , like:
```
set session max_execution_time=0;
```

**Comment by davidducos** [comment]
Hi @ting425, 

I think that it is better to have a file with all the variable that we want to use for SET SESSION statements, instead of having one per variable or we could have a list of variables, something like --set-session="max_execution_time=0,other_variable=2", What do you think?

**Comment by dba-kit** [comment]
That's wonderful!

**Comment by davidducos** [comment]
Check #370, it is already merged into master. We can close it.
