### ISSUE TITLE
error in your SQL syntax

### ISSUE THREAD

**Issue by nucfisher** [maxbube/mydumper#262]
Mydumper throws muliple errors like followig:

`** (mydumper:598994): CRITICAL **: 12:40:22.658: Error dumping table (phpmyadmin.pma__history) data: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'table,username FROM `phpmyadmin`.`pma__history`' at line 1 `

Ubuntu 20.04
mysql 8.0.21
phpmadmin 4.4.1.1 (if it matters)
php-fpm 5.6 (if i matters)

**Comment by fredricj** [comment]
Partly a duplicate of #221 and partly a duplicate of #215.

**Comment by nucfisher** [comment]
So what?
One of them is closed as a duplicate, another is open.
Any forecasts?

**Comment by h3y0n9** [comment]
fixed in #216 
u can build mydumper from the latest code

**Comment by davidducos** [comment]
Should be fixed by the latest code. If you still have this issue, paste the table structure.
