### ISSUE TITLE
connection.c: In function ‘configure_connection’

### ISSUE THREAD

**Issue by qt-pay** [maxbube/mydumper#264]
make
[ 12%] Building C object CMakeFiles/mydumper.dir/connection.c.o
/root/mydumper/connection.c: In function ‘configure_connection’:
/root/mydumper/connection.c:47: error: ‘SSL_MODE_REQUIRED’ undeclared (first use in this function)
/root/mydumper/connection.c:47: error: (Each undeclared identifier is reported only once
/root/mydumper/connection.c:47: error: for each function it appears in.)
/root/mydumper/connection.c:49: error: ‘SSL_MODE_DISABLED’ undeclared (first use in this function)
/root/mydumper/connection.c:53: error: ‘MYSQL_OPT_SSL_MODE’ undeclared (first use in this function)
make[2]: *** [CMakeFiles/mydumper.dir/connection.c.o] Error 1
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
make: *** [all] Error 2

**Comment by keithyzk** [comment]
same mistake

**Comment by Sharethings** [comment]
same mistake

**Comment by zihuaVeryGood** [comment]
I found a temporary solution in readme:
> To build against mysql libs < 5.7 you need to disable SSL adding -DWITH_SSL=OFF

so, it needs to be modified "WITH_SSL" in CMakeCache.txt, change to off:
```
WITH_SSL:BOOL=OFF
```
then recompile:
```
cmake .
make
```

**Comment by davidducos** [comment]
It is already documented in the https://github.com/maxbube/mydumper#how-to-build-it.
