### ISSUE TITLE
Use bulk API instead of flocks of INSERTs for data files

### ISSUE THREAD

**Issue by davidfetter** [maxbube/mydumper#265]
Per subject, this pretty much has to be faster because the cost of sending a row is lower on the dumping side (no INSERT there) and the cost of parsing is much lower on the loading side.

It should also make it much simpler to parallelize loading of single files because of the simplicity of seeking to the next N records, for whatever N people (or possibly myloader itself) could choose.

**Comment by davidducos** [comment]
Hi @davidfetter, can you elaborate a bit more your idea? 

from what I understood, you prefer to have files (or a single file) per table without the INSERT INTO statement. Then myloader will be able to take that file/s and split into chunks to parallelize. Am I right?

If it is so, I will not remove the INSERT INTO statement, but I don't see why myloader will not be able to split the files into chunks.

I will try to make a PR with this feature request

**Comment by davidfetter** [comment]
What I had in mind using the [LOAD DATA]( https://dev.mysql.com/doc/refman/5.7/en/load-data.html) syntax rather than the [INSERT](https://dev.mysql.com/doc/refman/5.7/en/insert-optimization.html) syntax for the data files, as it averages, according to the MySQL documentation, 20x the throughput for the single-threaded case, and could reasonably expected to be higher if multiple execution threads were operating at once.

**Comment by davidducos** [comment]
Hi @davidfetter, thanks for the clarification.
It might be possible to implement it, but this will need a lot of testing.

**Comment by davidducos** [comment]
@davidfetter, I was working on PR #145 and I found that if we implement the LOAD DATA there, it will do what you expect here.
