### ISSUE TITLE
Segmentation fault with libmysqlclient.so >8.0.19

### ISSUE THREAD

**Issue by gerion0** [maxbube/mydumper#266]
When executing mydumper with libmysqlclient.so > 8.0.19 (mysql-connector-c in my distribution), I get a segmentation fault:
```
# mydumper -v 3 -u root -p ... -h localhost -o tmp
** Message: 16:03:12.937: Connected to a MySQL server
** Message: 16:03:12.940: Started dump at: 2020-08-14 16:03:12

** Message: 16:03:12.940: Written master status
** Message: 16:03:12.940: Multisource slave detected.
** Message: 16:03:12.941: Thread 1 connected using MySQL connection ID 4932
** Message: 16:03:12.942: Thread 2 connected using MySQL connection ID 4933
** Message: 16:03:12.942: Thread 3 connected using MySQL connection ID 4934
** Message: 16:03:12.943: Thread 4 connected using MySQL connection ID 4935
** Message: 16:03:12.969: Thread 2 dumping data for `mysql`.`column_stats`
...
** Message: 16:03:13.147: Non-InnoDB dump complete, unlocking tables
** Message: 16:03:13.148: Thread 4 shutting down
** Message: 16:03:13.148: Thread 1 shutting down
** Message: 16:03:13.148: Thread 2 shutting down
** Message: 16:03:13.163: Thread 3 shutting down
** Message: 16:03:13.163: Finished dump at: 2020-08-14 16:03:13

zsh: segmentation fault  mydumper -v 3 -u root -p ... -h localhost -o tmp
```

I have [reported this](https://bugs.gentoo.org/737002) in my distribution already and it is reproducible.

**Comment by hydrapolic** [comment]
The segfault is reproduced with mysql-connector-c versions 8.0.20 and 8.0.21.

**Comment by pegro** [comment]
If you using libmysqlclient (from MySQL) against a MariaDB server, then this could be related to https://bugs.launchpad.net/ubuntu/+source/mysql-8.0/+bug/1884809 which is fixed for at least me with [this patch](https://git.launchpad.net/ubuntu/+source/mysql-8.0/plain/debian/patches/charset_file_crash.patch) against libmysqlclient (mysql-connector-c)

**Comment by hydrapolic** [comment]
Just tested the patch with mysql-connector-c-8.0.21 and the segfault is gone.
