### ISSUE TITLE
Installation instruction for Debian / Ubuntu

### ISSUE THREAD

**Issue by sufehmi** [maxbube/mydumper#268]
Hi, first , thank you so much for this project. It's really great.
Thanks again !

Second, the installation instruction is a bit incomplete for Debian / Ubuntu

Currently : apt-get install libglib2.0-dev libmysqlclient15-dev zlib1g-dev libpcre3-dev libssl-dev

Should be : sudo apt-get ; sudo apt-get install libglib2.0-dev libmysqlclient-dev zlib1g-dev libpcre3-dev libssl-dev cmake build-essential git

That's all really.

Seems simple - but for newbies in those OS, this can be pretty confusing.

cheers, HS

**Comment by flanger001** [comment]
This had `git` twice. The command should be: `sudo apt install build-essential cmake git libglib2.0-dev libmysqlclient-dev libpcre3-dev libssl-dev zlib1g-dev`

**Comment by flanger001** [comment]
I also wanted to note I ended up needing `libssl1.0.0`

```bash
echo "deb http://archive.ubuntu.com/ubuntu/ bionic-security main restricted" | sudo tee /etc/apt/sources.list.d/bionic-security.list
sudo apt update
sudo apt install libssl1.0.0
```

**Comment by davidducos** [comment]
I will be working on the this based on this repo: https://github.com/davidducos/mydumper_builder which is what I'm going to use for new releases and testings
