### ISSUE TITLE
Not able to restore procedures using myloader

### ISSUE THREAD

**Issue by Aliya55** [maxbube/mydumper#270]
Hi, I have been trying to restore data using myloader , everything worked fine except 2 procedures which didn't restore. Can i get some help on this?

**Comment by richlv** [comment]
Please post details on what exactly was attempted and how it failed.

When the dump was created, was the `--routines` / `-R` flag used?

**Comment by davidducos** [comment]
I followed the standard procedure and found no issue. Please, give more detail and we are going to re open this issue.
