### ISSUE TITLE
bug for overwrite-tables option 

### ISSUE THREAD

**Issue by recall704** [maxbube/mydumper#272]
i have two table in one db, name like `xxx` and `xxx.bak`, when i use `--overwrite-tables` for myloader, `DROP TABLE IF EXISTS` for `xxx.bak` will be ignore

**Comment by recall704** [comment]
![image](https://user-images.githubusercontent.com/7451408/94357842-e3338700-00ce-11eb-85e7-90ef734a5d7d.png)

**Comment by recall704** [comment]
if table name is `xxx.bak`, the value of `split_file[1]` will `xxx` but not `xxx.bak`

**Comment by davidducos** [comment]
The solution for this kind of issue, is to check the amount of elements in the split_file variable and concat again to get the real table name OR you could avoid using '.' (dot) in your table names. Pull request fixing it are welcome.

**Comment by davidducos** [comment]
We are going to start a project which is not going to allow problematic filenames for myloader. It will be a check function on mydumper, other issue releated to this: #212
