### ISSUE TITLE
We hope to add parameters and support custom SQL mode and character configuration

### ISSUE THREAD

**Issue by albert0807** [maxbube/mydumper#274]
We hope to add two parameters to support SQL mode and default character set configuration. These two configurations can improve the power of the tool and make the tool more flexible

**Comment by david-ducos-percona** [comment]
Hi @albert0807, 

I need clarification about this request.
1- This is just for myloader, right? if not, can you clarify when this is useful on mydumper?
2- If we want to be flexible, we should be able to set not just SQL_MODE or character_set_* , we should be able to configure others, per file? per execution?

Will be useful your use case to understand what is the best approach.

**Comment by davidducos** [comment]
The default character set can be set with the --defaults-file in mydumper and myloader.

And about the SQL_MODE, I think that will be more interesting to develop hook files.

**Comment by michaelcoburn** [comment]
`mydumper` needs this set as well - if you are in `sql_mode=ANSI` then you won't export tables correctly - they will be missing `ENGINE=InnoDB DEFAULT CHARSET=` entries.   So both binaries need to support `sql_mode`.

An idea is to check for `ANSI` or `ANSI_QUOTES` and then strip them from the session `sql_mode`.

**Comment by davidducos** [comment]
There are 2 ways of setting SQL_MODE, I recommend to use the #370 solution.
