### ISSUE TITLE
Does mydumper not chunk if fields in table is too long？

### ISSUE THREAD

**Issue by yonglezhu** [maxbube/mydumper#281]
Does mydumper not chunk if fields in table is too long？
eg，threre are some text or blob or varchar(4000) fileds to make the record off-page

mydumper version: mydumper-0.9.5-2.el7.x86_x64.rpm
mysql version: 5.7.24

**Comment by davidducos** [comment]
Hi @yonglezhu,

I don't see why this could happen. Are you experiencing an issue? what is the error?
MyDumper is doing a SELECT to get the data and then it is creating a INSERT statement. So, should be no issue if the fields are longer than the page size.

**Comment by yonglezhu** [comment]
@davidducos thanks for comment
I gathered some information about chunked table and not chunked table，tables are in the same schema.
the dump comand is:
  mydumper --user root --password **** --host x.x.x.x --port 3306 --threads 4 --rows 10000 --triggers --events --routines --no-locks --logfile /data/output/mydumper.log --database mydb --outputdir /data/output/

chunked tables:
--count:377439
--table_rows:199107
CREATE TABLE `t_his_task_notify` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `biz_id` varchar(64) DEFAULT NULL,
  `task_item_id` varchar(64) NOT NULL,
  `notify_time` datetime DEFAULT NULL,
  `mail_title` varchar(512) DEFAULT '',
  `mail_message` varchar(4000) DEFAULT '',
  `sms_content` varchar(4000) DEFAULT NULL,
  `send_type_flag` varchar(20) DEFAULT '',
  `notify_status` int(11) DEFAULT NULL,
  `suspend_time` datetime DEFAULT NULL,
  `actual_notify_time` datetime DEFAULT NULL,
  `notify_group_codes` varchar(512) DEFAULT NULL,
  `notify_user_ids` varchar(512) DEFAULT '',
  `notify_type` varchar(100) DEFAULT NULL,
  `on_delegate_both_recive` bit(1) NOT NULL DEFAULT b'0',
  `workday_send_only` bit(1) NOT NULL DEFAULT b'0',
  `worktime_send_only` bit(1) NOT NULL DEFAULT b'0',
  `actual_notify_users` varchar(4000) DEFAULT NULL,
  `national_workday_send_only` bit(1) DEFAULT NULL,
  `national_worktime_send_only` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `taskId_index` (`task_item_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=386963 DEFAULT CHARSET=utf8;


--count:546487
--table_rows:65403
CREATE TABLE `t_his_task_comment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `comment_type` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `user_id` varchar(100) DEFAULT NULL,
  `user_name` varchar(255) DEFAULT NULL,
  `depart_id` varchar(100) DEFAULT NULL,
  `depart_name` varchar(255) DEFAULT NULL,
  `job_name` varchar(255) DEFAULT NULL,
  `is_call_backed` bit(1) DEFAULT NULL,
  `message` text,
  `target_key` varchar(255) DEFAULT NULL,
  `task_id` varchar(64) DEFAULT NULL,
  `biz_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `taskId_index` (`task_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=575219 DEFAULT CHARSET=utf8;

not chunked tables:
--count:208214
--table_rows:212411
CREATE TABLE `t_form_data` (
  `biz_id` varchar(64) NOT NULL DEFAULT '',
  `field_name` varchar(255) NOT NULL DEFAULT '',
  `field_value` longtext,
  `app_id` varchar(64) DEFAULT NULL,
  `task_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`biz_id`,`field_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--count:5969688
--table_rows:3352521
CREATE TABLE `ACT_HI_VARINST` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin NOT NULL,
  `VAR_TYPE_` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `REV_` int(11) DEFAULT NULL,
  `BYTEARRAY_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DOUBLE_` double DEFAULT NULL,
  `LONG_` bigint(20) DEFAULT NULL,
  `TEXT_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TEXT2_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_TIME_` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TIME_` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_PROCVAR_PROC_INST` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_PROCVAR_NAME_TYPE` (`NAME_`,`VAR_TYPE_`),
  KEY `ACT_IDX_HI_PROCVAR_TASK_ID` (`TASK_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--count:7511734
--table_rows:3872263
CREATE TABLE `ACT_HI_DETAIL` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin NOT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ACT_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin NOT NULL,
  `VAR_TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `REV_` int(11) DEFAULT NULL,
  `TIME_` datetime(3) NOT NULL,
  `BYTEARRAY_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DOUBLE_` double DEFAULT NULL,
  `LONG_` bigint(20) DEFAULT NULL,
  `TEXT_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TEXT2_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_DETAIL_PROC_INST` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_DETAIL_ACT_INST` (`ACT_INST_ID_`),
  KEY `ACT_IDX_HI_DETAIL_TIME` (`TIME_`),
  KEY `ACT_IDX_HI_DETAIL_NAME` (`NAME_`),
  KEY `ACT_IDX_HI_DETAIL_TASK_ID` (`TASK_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


ps: count for select count(*) from table_name;table_rows from table_rows field of information_schema.tables

**Comment by yonglezhu** [comment]
I did some test，and found it has relations with primary key.
I added a autoincrement key to the table ,and found it can be chunked


mysql> desc t_chunked;
+-----------------------------+---------------+------+-----+---------+----------------+
| Field                       | Type          | Null | Key | Default | Extra          |
+-----------------------------+---------------+------+-----+---------+----------------+
| id                          | int(11)       | NO   | PRI | NULL    | auto_increment |
| biz_id                      | varchar(64)   | YES  |     | NULL    |                |
| task_item_id                | varchar(64)   | NO   | MUL | NULL    |                |
| notify_time                 | datetime      | YES  |     | NULL    |                |
| mail_title                  | varchar(512)  | YES  |     |         |                |
| mail_message                | varchar(4000) | YES  |     |         |                |
| sms_content                 | varchar(4000) | YES  |     | NULL    |                |
| send_type_flag              | varchar(20)   | YES  |     |         |                |
| notify_status               | int(11)       | YES  |     | NULL    |                |
| suspend_time                | datetime      | YES  |     | NULL    |                |
| actual_notify_time          | datetime      | YES  |     | NULL    |                |
| notify_group_codes          | varchar(512)  | YES  |     | NULL    |                |
| notify_user_ids             | varchar(512)  | YES  |     |         |                |
| notify_type                 | varchar(100)  | YES  |     | NULL    |                |
| on_delegate_both_recive     | bit(1)        | NO   |     | b'0'    |                |
| workday_send_only           | bit(1)        | NO   |     | b'0'    |                |
| worktime_send_only          | bit(1)        | NO   |     | b'0'    |                |
| actual_notify_users         | varchar(4000) | YES  |     | NULL    |                |
| national_workday_send_only  | bit(1)        | YES  |     | NULL    |                |
| national_worktime_send_only | bit(1)        | YES  |     | NULL    |                |
+-----------------------------+---------------+------+-----+---------+----------------+

mysql> desc t_unchunked;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| biz_id      | varchar(64)  | NO   | PRI |         |       |
| field_name  | varchar(255) | NO   | PRI |         |       |
| field_value | longtext     | YES  |     | NULL    |       |
| app_id      | varchar(64)  | YES  |     | NULL    |       |
| task_id     | varchar(64)  | YES  |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+

mysql> select table_name,table_rows from information_schema.tables where table_schema='mydb';
+-------------+------------+
| table_name  | table_rows |
+-------------+------------+
| t_chunked   |     345022 |
| t_unchunked |     241124 |
+-------------+------------+

$ mydumper --user root --password ****** --host 127.0.0.1 --port 3306 --threads 4 --rows 100000 --triggers --events --routines --no-locks --logfile /data/output/mydumper.log --database mydb --outputdir /data/output/
$ ll
-rw-rw-r-- 1 appuser appuser       179 1月  27 13:43 metadata
-rw-rw-r-- 1 appuser appuser        63 1月  27 13:43 mydb-schema-create.sql
-rw-rw-r-- 1 appuser appuser 117513467 1月  27 13:43 mydb.t_chunked.00000.sql
-rw-rw-r-- 1 appuser appuser 119534318 1月  27 13:43 mydb.t_chunked.00001.sql
-rw-rw-r-- 1 appuser appuser  99619165 1月  27 13:43 mydb.t_chunked.00002.sql
-rw-rw-r-- 1 appuser appuser      2436 1月  27 13:43 mydb.t_chunked-schema.sql
-rw-rw-r-- 1 appuser appuser       514 1月  27 13:43 mydb.t_unchunked-schema.sql
-rw-rw-r-- 1 appuser appuser 554982674 1月  27 13:43 mydb.t_unchunked.sql
-rw-rw-r-- 1 appuser appuser        91 1月  27 13:43 mydumper.log


mysql> create table t_unchunked_autoinc_pk(id int not null auto_increment primary key,biz_id varchar(64),field_name varchar(255),field_value longtext,app_id varchar(64),task_id varchar(64));
Query OK, 0 rows affected (0.04 sec)
mysql> insert into t_unchunked_autoinc_pk(biz_id,field_name,field_value,app_id,task_id) select * from t_unchunked;
Query OK, 216303 rows affected (16.05 sec)
Records: 216303  Duplicates: 0  Warnings: 0

mysql> desc t_unchunked_autoinc_pk;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| biz_id      | varchar(64)  | YES  |     | NULL    |                |
| field_name  | varchar(255) | YES  |     | NULL    |                |
| field_value | longtext     | YES  |     | NULL    |                |
| app_id      | varchar(64)  | YES  |     | NULL    |                |
| task_id     | varchar(64)  | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+

$ mydumper --user root --password ****** --host 127.0.0.1 --port 3306 --threads 4 --rows 100000 --triggers --events --routines --no-locks --logfile /data/output/mydumper.log --database mydb --outputdir /data/output/
$ ll
-rw-rw-r-- 1 appuser appuser       180 1月  27 14:05 metadata
-rw-rw-r-- 1 appuser appuser        63 1月  27 14:05 mydb-schema-create.sql
-rw-rw-r-- 1 appuser appuser 117513467 1月  27 14:05 mydb.t_chunked.00000.sql
-rw-rw-r-- 1 appuser appuser 119534318 1月  27 14:05 mydb.t_chunked.00001.sql
-rw-rw-r-- 1 appuser appuser  99619165 1月  27 14:05 mydb.t_chunked.00002.sql
-rw-rw-r-- 1 appuser appuser      2436 1月  27 14:05 mydb.t_chunked-schema.sql
-rw-rw-r-- 1 appuser appuser 191574523 1月  27 14:05 mydb.t_unchunked_autoinc_pk.00000.sql
-rw-rw-r-- 1 appuser appuser 364818111 1月  27 14:05 mydb.t_unchunked_autoinc_pk.00001.sql
-rw-rw-r-- 1 appuser appuser       444 1月  27 14:05 mydb.t_unchunked_autoinc_pk-schema.sql
-rw-rw-r-- 1 appuser appuser       514 1月  27 14:05 mydb.t_unchunked-schema.sql
-rw-rw-r-- 1 appuser appuser 554982674 1月  27 14:05 mydb.t_unchunked.sql
-rw-rw-r-- 1 appuser appuser        91 1月  27 14:05 mydumper.log

**Comment by yonglezhu** [comment]
@davidducos Can you tell me what's the problem?

**Comment by davidducos** [comment]
The problems is that MyDumper doesn't support non integer primary keys with the --rows option. I will be adding a message to inform during the backup. If you know how to fix it and you want to share, feel free to submit a pull request and I will be reviewing and testing.

**Comment by yonglezhu** [comment]
It's all right to use size to split to multiple chunks,but it seams that a big table is chunked but not be spreaded to multiple threads to speed up.

**Comment by davidducos** [comment]
@yonglezhu why don't you use a lower value for --rows ? it will create smaller files and if you increase the --threads on myloader, you might get a better performance.

**Comment by yonglezhu** [comment]
I have a big table ,about 30 millions.with a value of 10000 for --rows,and a value of 8 for --thread,there still is only one thread conneting to mysqld for dumping,as the primary key of the table is not integer.

the other way,I use --chunk-filesize and --threads, only one thread conneting to mysqld for dumping too.

**Comment by davidducos** [comment]
@yonglezhu MyDumper will only be able to use more than one thread to dump the data if there is an integer primary key.

**Comment by yonglezhu** [comment]
yes, I known it's limit now,thanks.

**Comment by yonglezhu** [comment]
yes，I know it‘s limits now，thanks.
