### ISSUE TITLE
Add Debian releasename to package version

### ISSUE THREAD

**Issue by jeremymaes** [maxbube/mydumper#283]
Hi

Would it be possible to add the debian releasename (stretch, buster, ...) or an alternative indicating the release to the package version, instead of only the package filename?

We host the new mydumper 0.10 packages on our own repositories, but as the packages for all releases have the same name and version, reprepro sees these as the same package and refuses to use any but the first one we add. Example error (after adding the buster package, I tried to add the stretch package):

```
reprepro includedeb stretch ~/mydumper_10.1-1.stretch_amd64.deb
ERROR: '~/mydumper_10.1-1.stretch_amd64.deb' cannot be included as 'pool/main/m/mydumper/mydumper_10.1-1_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 9e27372d4889265a605699a062d4cdec, got: dc1577964b58e97b5d3ec48e049999eb
sha1 expected: 306fec9822d67c189c1ff853907ace745d4eae3d, got: f71ec9d89ae1dffedea4f81968427829144ca2d1
sha256 expected: ac6e1031fdbd1bf8f91f2c2591cfeb6dd772cb3c332b019bc1f4d5d38e22bef3, got: e93eaf98d29db74dc3ecc335e91778cc99e6f396424d21541de1e33a884ce791
size expected: 862716, got: 862796
There have been errors!
```

Example of what the version field looks like in the official debian repos for mydumper 0.9.5:
`0.9.5-1+deb10u1`

But the "deb10" part could be anything indicating the release. Some packagers use "deb10", others use "debian10", and others use "buster".

**Comment by davidducos** [comment]
@jeremymaes 
I'm using this repo https://github.com/davidducos/mydumper_builder to build the packages, if you can indicate me what I have to change, I will appreciate an upload the new files.
Thanks!

**Comment by davidducos** [comment]
@jeremymaes 
I've updated the latest release, please check the files and confirm that it work for you. I have updated the builder repo to do what you asked. Please, let me know so I can close this issue and I will upload the script to the repo with the updates. 
Thanks!!

**Comment by jeremymaes** [comment]
@davidducos
Thank you the speedy rebuild! The new version strings work perfectly for adding them to different release repositories.
I see you've also fixed the version number in the filename, which is also a nice thing.

So from my perspective you can close this issue.

**Comment by davidducos** [comment]
Yes, I noticed that because you reported this issue! thanks!
