### ISSUE TITLE
[enhancement] optimized data loading order

### ISSUE THREAD

**Issue by biberesser** [maxbube/mydumper#285]
Using this tool for continuously dumping/restoring schemas with hundreds of tables, views etc.,
with gigabytes of data in each schema, mostly concentrated in a few large data tables, sometimes with a FULLTEXT index etc.

Currently tables are restored naively in order of their name, ascending.
For us, the largest tables taking the longest to restore are executed almost last,
leading to a lot of time wasted in the whole restore process.
The slowest of the restore threads determines the total time.

**Suggestion:**
**When restoring, start with the tables which probably will take the longest to restore.**

When dumping, use the tables metadata to heuristically define some rough estimate of how long it would take to restore the table.
Some criteria could be:
* no. of rows in the table
* number of NOT NULL columns
* number of large BLOB/TEXT columns (which may or may not be NOT NULL)
* FULLTEXT indexes on columns
* INDEXES, FOREIGN KEYS situation in general

**Comment by davidducos** [comment]
Hi @biberesser,
This is a really interesting topic, as what you are talking about is "Import Strategies"!! this is something that I would like to add on next releases but we need to add it to the Wiki and it should be only on myloader, not in mydumper. I'm agree that we should add in mydumper a logic to export metadata about the number of rows per table and row size which might be hard to do over the backup directory ( a wc -l on a compressed file over a backup of gigabytes makes no sense to me). 

So, YES! I would like to do this in upcoming releases, it will be on myloader and we need to think more about the logic. Please, let me know your thoughts.

**Comment by biberesser** [comment]
Idea:
1. calculate estimated priorities while dumping, using table metadata etc.
  A first quick'n'dirty heuristic would be simply use the **data file size** and the number of table INDEXes (especially FULLTEXT) on the table.
2. create tables list text file, sorted by descending "costs"
3. evaluate the optimized load order file when importing, but be resilient to errors,
   e.g. missing tables in the optimized load order should not cause a broken import!
   use the load order merely as a completely optional optimization hint

**Comment by davidducos** [comment]
Now, that we have [fast index creation](#286 ), we need to focus on 2 things:
- Order of the tables for insert:
There might be a couple of ways of doing this:
- mydumper could get the information needed (data_length and amount of rows ) and save it in the metadata file
- myloader could sum the size of the files per table, but the amount of rows will be expensive.
- myloader could load the table order from a parameter 
Every option has pros and cons, but we need to investigate is the difference in timings between amount of rows and row size, as I'm not sure about the best order in that case. 
- As soon as a large table perform the latest insert, we need to trigger the index creation:
I have the impression that the resources used for INSERT and CREATE INDEX are not (heavily) competing each other. So, we might be able to create a defined amount of indexes during the data insertion, which I think will reduce the overall process.

**Comment by davidducos** [comment]
I think that [this branch](https://github.com/maxbube/mydumper/tree/fic_sync) will be the new way of import
