### ISSUE TITLE
mydumper does not read credentials from --defaults-file

### ISSUE THREAD

**Issue by Phillip85** [maxbube/mydumper#290]
Hi,
i would like to save my credentials in a file,
but it looks like --defaults-file does not accept credentials:

```
slr@shmysql1:~/backup$ mysql --defaults-extra-file=/etc/mysql/.backup-user.cnf
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 21
Server version: 8.0.22-13 Percona Server (GPL), Release '13', Revision '6f7822f'

Copyright (c) 2009-2020 Percona LLC and/or its affiliates
Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ^DBye
slr@shmysql1:~/backup$ sh -x ./backup.sh test
+ hostname
+ date +%F_%H
+ dirname=/mnt/backup_diskstation/shmysql1-test-2021-03-01_16Uhr
+ mkdir -p /mnt/backup_diskstation/shmysql1-test-2021-03-01_16Uhr
+ mydumper --defaults-file=/etc/mysql/.backup-user.cnf --no-locks --triggers --events --routines -v 3 --threads=6 --chunk-filesize=1024 --regex ^(?!(mysql\.|information_shema\.|sys\.)) --logfile=/mnt/backup_diskstation/shmysql1-test-2021-03-01_16Uhr/logfile.log --outputdir=/mnt/backup_diskstation/shmysql1-test-2021-03-01_16Uhr
```
Logfile contains:
`2021-03-01 16:27:23 [ERROR] - Error connecting to database: Access denied for user 'xxx'@'localhost' (using password: NO)
`
the credentials working on the normal mysql shell, but not for mydumper

**Comment by davidducos** [comment]
@Phillip85 

Can you execute this command:
`mysql --defaults-file=/etc/mysql/.backup-user.cnf` ??

It is just to confirm that all the information needed is in that file as:
`--defaults-extra-file=# Read this file after the global files are read.
`
and 
`--defaults-file=#       Only read default options from the given file #.
`

**Comment by Phillip85** [comment]
Hi @davidducos 

yes i can:

```
slr@shmysql1:~/backup$ mysql --defaults-file=/etc/mysql/.backup-user.cnf
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 23
Server version: 8.0.22-13 Percona Server (GPL), Release '13', Revision '6f7822f'

Copyright (c) 2009-2020 Percona LLC and/or its affiliates
Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ^DBye
slr@shmysql1:~/backup$                           
```

**Comment by davidducos** [comment]
I did some testings and the user and password is not being loaded from the --defaults-file. 
I will review the PR that added that feature.

**Comment by matthewlenz** [comment]
That's really odd because I am using a defaults file with mydumper/loader with the following format without issue:

--
[client]
user  = username
password = password

**Comment by davidducos** [comment]
@Phillip85  I rechecked, @matthewlenz is right and I was wrong in my previous message, this is working correctly but I think that I found the issue that I had, I used my_mydumper.cnf instead of /root/test/my_mydumper.cnf. That is not your case but during my review, I saw that mydumper is using its own section in the configuration file, so you should be using [mydumper], and [client] is the default for mysql, so you can use that either.

**Comment by Phillip85** [comment]
ok, 

the [mydumper] entry makes the defaults-file work.
Thanks for the help.
