### ISSUE TITLE
Myloader throw error: the specified directory is not a mydumper backup

### ISSUE THREAD

**Issue by aakashmuthuramalingam** [maxbube/mydumper#291]
Hi,
   I take the dump of a table using Mydumper of version 0.10.1, it was successful. I tried to restore it using Myloader of version 0.10.1, but it is saying 

`** (myloader:26471): CRITICAL **: the specified directory is not a mydumper backup`

Logs for reference:

Dumper Command (Successful):

```
time mydumper --no-schemas  --host=127.0.0.1 --user='sbtest' --password='sbtest' --port=5644 -t 8 --rows=100000 --compress --triggers --routines --events -v 3 --compress --trx-consistency-only --complete-insert -B sbtest1 -T sbtest1 --outputdir ~/test2/ --logfile ~/test2_log/dump.log

real  1m47.217s
user  6m28.104s
sys 0m5.106s

2021-03-07 04:05:09 [INFO] - Thread 4 dumping data for `sbtest1`.`sbtest1` where (`id` >= 19898509 AND `id` < 20000032)
2021-03-07 04:05:09 [INFO] - Thread 2 shutting down
2021-03-07 04:05:09 [INFO] - Thread 7 shutting down
2021-03-07 04:05:09 [INFO] - Thread 8 shutting down
2021-03-07 04:05:10 [INFO] - Thread 5 shutting down
2021-03-07 04:05:11 [INFO] - Thread 6 shutting down
2021-03-07 04:05:11 [INFO] - Thread 3 shutting down
2021-03-07 04:05:11 [INFO] - Thread 1 shutting down
2021-03-07 04:05:11 [INFO] - Thread 4 shutting down
2021-03-07 04:05:11 [INFO] - Finished dump at: 2021-03-07 04:05:11
```

Loader Command (Unsuccessful):

```
myloader --host=127.0.0.1 --user='sbtest' --password='sbtest' --port=5644  --directory=~/test2/ -B load2 --threads=8 --verbose=3 -e 2> ~/restore2_logs/restore.log

** (myloader:26488): CRITICAL **: the specified directory is not a mydumper backup
```

But the metadata file exists on directory

```
ls -lrth ~/test2/ | grep metadata
-rw-r--r--. 1 root root  154 Mar  7 04:05 metadata

cat ~/test2/metadata
Started dump at: 2021-03-07 04:03:24
SHOW MASTER STATUS:
        Log: mysql_sandbox5644-bin.000008
        Pos: 350310047
        GTID:

Finished dump at: 2021-03-07 04:05:11
```
Versions:

```
mydumper --version
mydumper 0.10.1, built against MySQL 5.7.32-35

myloader --version
myloader 0.10.1, built against MySQL 5.7.32-35
```

Downloaded and installed using yum repo

`yum install https://github.com/maxbube/mydumper/releases/download/v0.10.1/mydumper-0.10.1-2.el7.x86_64.rpm -y`

cat /etc/*release
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)

As per the code, it should throw this error when the metadata file does not exists.

`else {
    char *p = g_strdup_printf("%s/metadata", directory);
    if (!g_file_test(p, G_FILE_TEST_EXISTS)) {
      g_critical("the specified directory is not a mydumper backup\n");
      exit(EXIT_FAILURE);
    }`

Do let me know is it a bug or I did something wrong ?

**Comment by david-ducos-percona** [comment]
Looks like the issue is related to the usage of `~`
```
root@ubuntu-focal:/tmp/mydumper# myloader  --directory=~/test2/ -B load2 --threads=8 --verbose=3 -e

** (myloader:355035): CRITICAL **: 17:10:09.308: the specified directory is not a mydumper backup

root@ubuntu-focal:/tmp/mydumper# myloader  --directory=/root/test2/ -B load2 --threads=8 --verbose=3 -e
** Message: 17:10:17.415: 8 threads created
** Message: 17:10:17.416: Thread 4 shutting down
** Message: 17:10:17.416: Thread 3 shutting down
** Message: 17:10:17.416: Thread 6 shutting down
** Message: 17:10:17.416: Thread 1 shutting down
** Message: 17:10:17.416: Thread 8 shutting down
** Message: 17:10:17.416: Thread 2 shutting down
** Message: 17:10:17.418: Thread 5 shutting down
** Message: 17:10:17.420: Thread 7 shutting down
```
Let me see how we can fix it

**Comment by davidducos** [comment]
This is not a bug at MyDumper, this is how expansion works in bash/sh. I added a line where prints the Directory path, and as you can see, this works:
```
root@ubuntu-focal:/tmp/mydumper# ./myloader  --directory ~/test2/ -B load2 --threads=8 --verbose=3 -e
** Message: 17:19:52.773: Directory: /root/test2//metadata
** Message: 17:19:52.780: 8 threads created
** Message: 17:19:52.780: Thread 4 shutting down
** Message: 17:19:52.780: Thread 6 shutting down
** Message: 17:19:52.780: Thread 8 shutting down
** Message: 17:19:52.781: Thread 3 shutting down
** Message: 17:19:52.781: Thread 2 shutting down
** Message: 17:19:52.781: Thread 1 shutting down
** Message: 17:19:52.781: Thread 5 shutting down
** Message: 17:19:52.781: Thread 7 shutting down
```
And this doesn't:
```
root@ubuntu-focal:/tmp/mydumper# ./myloader  --directory=~/test2/ -B load2 --threads=8 --verbose=3 -e
** Message: 17:21:57.356: Directory: ~/test2//metadata

** (myloader:355702): CRITICAL **: 17:21:57.356: the specified directory is not a mydumper backup
```

**Comment by fredricj** [comment]
While I agree on this is a user error, I think it would be a good idea to separate the error into two different errors. 1) The specified directory does not exist 2) The specified directory is not a mydumper backup. 
What's your thoughts on this?

**Comment by davidducos** [comment]
My thoughts? :D PR created!! lol

**Comment by davidducos** [comment]
and THANKS!!
