### ISSUE TITLE
FTWLR caused by error in condition

### ISSUE THREAD

**Issue by mielas** [maxbube/mydumper#293]
it looks like there is a problem with  unnecessary FTWRL, mydumper.c:

  if (!no_locks && (detected_server != SERVER_TYPE_TIDB)) {
    // Percona Server 8 removed LOCK BINLOG so backup locks is useless for
    // mydumper now and we need to fail back to FTWRL
    mysql_query(conn, "SELECT @@version_comment, @@version");
    MYSQL_RES *res2 = mysql_store_result(conn);
    MYSQL_ROW ver;
    while ((ver = mysql_fetch_row(res2))) {
      if (!g_str_has_prefix("Percona", ver[0]) &&
          !g_str_has_prefix("8.", ver[1])) {
        g_message("Disabling Percona Backup Locks for Percona Server 8");
        no_backup_locks = 1;
      }
    }

and as a result on e.g. mysql percona 5.7 there is FTWRL used instead of backup locks -- a total disaster on busy systems ;)

**Comment by davidducos** [comment]
Hi @mielas, 
I toke a glance of the code that you paster and I found that there is a bug in it which has been fixed with https://github.com/maxbube/mydumper/pull/288. 
You have 2 options, use the master and compile mydumper yourself, or wait a couple of days when v0.10.3 will be released.
Please, let me know if latest version fix your issue. keep me posted!

**Comment by mielas** [comment]
you're right. i was searching the issues before sending this one but forgot about closed ones, sorry... i will probably wait couple of days. i was trying to get rid of compilation tasks while installing mydumper and all my ansible roles recently stopped using sources in installation tasks. so i will try to have a strong will and won't revert back the change :) meanwhile -- welcome back good old 0.9.5


keep up good work!

**Comment by mielas** [comment]
i've checked latest codes from master branch and it works as it should. tnx

**Comment by davidducos** [comment]
Thanks @mielas !! I will be closing this now.
