### ISSUE TITLE
mydumper --no-lock option is not working in cronjob and when call from another script

### ISSUE THREAD

**Issue by piyushsonigra** [maxbube/mydumper#298]
We have created the script using mydumper and used option --no-lock, It's working fine when we directly execute the script but when adding a script in crontab or execute mydumper script from another script, it starts generating errors `Deadlock found when trying to get lock; try restarting transaction.`
OS: Ubuntu 18.04.3 LTS 

`mydumper -u $MYSQL_USER -p $MYSQL_PASS -h $DBHOST -P $DBPORT --database #DB_NAME --no-locks --omit-from-file ./mydumper_omit_tables -o $backup_name --threads $threads`

**Comment by davidducos** [comment]
Hi @piyushsonigra,
Can you test the script with the absolute path to the file `mydumper_omit_tables` ? it might be possible that it is not being found, you should see a critical message with `cannot read/open` when this happens.

**Comment by piyushsonigra** [comment]
Hi @davidducos,
there is no issue with the `--omit-from-file` argument file.

**Comment by davidducos** [comment]
@piyushsonigra can you use option -L on both cases and share the log file?

**Comment by davidducos** [comment]
Hi @piyushsonigra, 
Can you share more info, so we can troubleshoot this issue?

**Comment by piyushsonigra** [comment]
No one more working on it, so unable to do further troubleshooting and proving logs.
Thanks for your response.
