### ISSUE TITLE
how can I make mydumper --lock-tables = false myisam

### ISSUE THREAD

**Issue by montes2012** [maxbube/mydumper#301]
It can be executed in mydumper --lock-tables=false I am working with myisam in production. at the moment I am using myslqdump --lock-tables=false

**Comment by davidducos** [comment]
Hi @montes2012 
You have the -k / --no-locks parameter to get inconsistent backups
```
root@ubuntu-focal:/tmp/mydumper# ./mydumper --help | grep "lock"
  -k, --no-locks                  Do not execute the temporary shared read lock.  WARNING: This will cause inconsistent backups
```
BTW, do now use MyISAM tables on prod.

**Comment by montes2012** [comment]
lock the table and don't insert

**Comment by montes2012** [comment]
Is the issue on mydumper

the tables were locked and did not insert

I have only table myisam

only mydumper works but it is slow. the data 2TB

**Comment by davidducos** [comment]
@montes2012 

mydumper doesn't execute INSERT statements. Are you using --no-locks options? are you using multiple threads per table? what are the select statements that you see in the show processlist?

**Comment by montes2012** [comment]
The inserts are made by another application is that I need to make the backup in production.

mysqldump -uroot -p -h 192.168... -P3306 --insert-ignore --no-create-info --lock-tables=false --skip-add-drop-table database > bk.sql

mydumper --database=database --host=192.168. --port=3306 --user=root --password= --no-locks --insert-ignore --no-schemas -o /mnt/bk --verbose=3 --kill-long-queries

**Comment by davidducos** [comment]
@montes2012 ,

Ok, it is a performance issue then. You need to increase the amount of threads, or use -r to split the files and take into account that the tables must have an integer PK so mydumper can chunk the data in multiple files and export the data in parallel.

**Comment by montes2012** [comment]
For each day there are 2 tables that contain 

Table one 
10141 records

Table two
86277

the computer where I am running mydumper has 8 cores

What do you recommend
amount of threads?
-r, --rows                  Try to split tables into chunks of this many rows. This option turns off --chunk-filesize?

**Comment by davidducos** [comment]
Why don't you try this?
`mydumper --database=database --host=192.168. --port=3306 --user=root --password= --no-locks --insert-ignore --no-schemas -o /mnt/bk --verbose=3 --kill-long-queries -r 10000
`
You didn't answer if the tables have integer primary keys.

**Comment by montes2012** [comment]
mysql> use W_BISM$ELZ$CM;

mysql> desc BISM$ELZ$CM$$H2021_03_30;
+--------+---------+------+-----+---------+-------+
| Field  | Type    | Null | Key | Default | Extra |
+--------+---------+------+-----+---------+-------+
| j2ksec | double  | NO   | PRI | NULL    |       |
| smin   | int(11) | YES  |     | NULL    |       |
| smax   | int(11) | YES  |     | NULL    |       |
| rcnt   | int(11) | YES  |     | NULL    |       |
| rsam   | double  | YES  |     | NULL    |       |
+--------+---------+------+-----+---------+-------+
5 rows in set (0,02 sec)

mysql> desc BISM$ELZ$CM$$2021_03_30;
+----------+---------+------+-----+---------+-------+
| Field    | Type    | Null | Key | Default | Extra |
+----------+---------+------+-----+---------+-------+
| st       | double  | NO   | PRI | NULL    |       |
| et       | double  | YES  |     | NULL    |       |
| sr       | double  | YES  |     | NULL    |       |
| datatype | char(3) | YES  |     | NULL    |       |
| tracebuf | blob    | YES  |     | NULL    |       |
+----------+---------+------+-----+---------+-------+
5 rows in set (0,01 sec)



mysql> select * from  BISM$ELZ$CM$$H2021_03_30 limit 2;
+-----------+------+------+------+-----------+
| j2ksec    | smin | smax | rcnt | rsam      |
+-----------+------+------+------+-----------+
| 670334400 |   23 |  124 |   99 | 17.710857 |
| 670334401 |   -3 |  121 |  101 | 21.144188 |
+-----------+------+------+------+-----------+
2 rows in set (0,14 sec)

mysql> select st,et,sr,datatype from  BISM$ELZ$CM$$2021_03_30 limit 2;
+-----------+-----------+------+----------+
| st        | et        | sr   | datatype |
+-----------+-----------+------+----------+
| 670334401 | 670334411 |  100 | i4       |
| 670334411 | 670334421 |  100 | i4       |
+-----------+-----------+------+----------+
2 rows in set (0,30 sec)

**Comment by davidducos** [comment]
Double is not an integer type... that is why you don't get the performance that we expect

**Comment by montes2012** [comment]
osea que se debe de utilizar mysqldump?

**Comment by davidducos** [comment]
If you use mydumper the export time should be lower than mydumper as you will be exporting both tables at the same time. 

The differences will be noticeable when you import the data, as if you use --chunk-filesize you will be able to import the data in parallel.

**Comment by montes2012** [comment]
excute run: 

mydumper --database=database --host=192.168.... --port=3306 --user=root --password= --no-locks --insert-ignore --no-schemas -o /mnt/bk --verbose=3 --kill-long-queries -r 10000 

the inserts are not made from the other application

**Comment by davidducos** [comment]
Hi @montes2012,

I tried to reproduce your scenario but I was not able to succeed. I reviewed the general log and there is no command that could block the insert made by the application using --no-locks. Actually, I saw the blocking behavior without using --no-locks. Are you using the latest version?

**Comment by davidducos** [comment]
Closing this issue based on https://github.com/maxbube/mydumper/wiki/Support
