### ISSUE TITLE
0.10.3 broke mydumper --chunk-filesize for use with myloader

### ISSUE THREAD

**Issue by matthewlenz** [maxbube/mydumper#304]
When I mydumper a db using -F 128 and then attempt to myloader that db to a new server I get "Column count doesn't match value count at row 1" on one of the tables.  If I skip chunk-filesize it works just fine.

**Comment by davidducos** [comment]
Hi @matthewlenz, 
I need more information about this issue:
- Table structure
- Insert statement or file that is failing 
- Execute the mydumper and myloader with -v 4 and upload the log

**Comment by matthewlenz** [comment]
@davidducos sorry for the delays on providing this info.  This is a big job that only runs once per day.  I've been playing around with some changes to insure it's nothing I'm doing to cause the issue.  I'll report back soon.

**Comment by matthewlenz** [comment]
I made some changes and it's no longer failing.
