### ISSUE TITLE
Is mydumper do both  "trx-consistency-only" and  inconsistent backups by default ?

### ISSUE THREAD

**Issue by WatchLucky** [maxbube/mydumper#321]
mydumper version: 0.10.3 
mysql version:  mysql-5.7.26
backup commands:   
`/usr/bin/mydumper --defaults-file=./m.conf --omit-from-file=./omit.conf -D -l 120 -c -C --skip-tz-utc --less-locking -L mydumper.log`

cat m.conf 
[mydumper]
user=xxx
password=xxxx
host=10.x.x.x
port=3306
threads=12

output directory : 
```
 # ll -h export-20210427-103537
total 388K
drwx------ 2 root root 232K Apr 27 14:47 0
drwx------ 2 root root  84K Apr 27 14:47 1
lrwxrwxrwx 1 root root    1 Apr 27 10:43 last_dump -> 0


du -sh  export-20210427-103537/0
2.8G    export-20210427-103537/0

du -sh  export-20210427-103537/1
2.8G    export-20210427-103537/1
```

 there is a file named "medata" in director  0 ,and a file named "medata.partial" in directory 1 , so  is mydumper do both  "trx-consistency" backups and  inconsistent backups by default ?

**Comment by davidducos** [comment]
Hi @WatchLucky, 
When you use the -D option, you are running in daemon mode. mydumper will create 2 directories and a link to the last dump. Both directories will have a dump of the database. Take into consideration that initially mydumper creates a metadata.partial file which after complete the backup, is renamed to metadata.
So, if you find a metadata.partial in a directory, could mean 2 things:
- That the backup is running at the moment that you checked.
- That the backup failed. 
For both scenarios, you will find information in the log or running `ps -elf | grep mydumper`
Please, let me know how it goes.

**Comment by WatchLucky** [comment]
Thanks 。

**Comment by davidducos** [comment]
Hi @WatchLucky, your welcome!
