### ISSUE TITLE
innodb_online_alter_log_max_size is not large enough

### ISSUE THREAD

**Issue by davidducos** [maxbube/mydumper#324]
Hi @davidducos,
Am also getting this error on two tables:
```
2021-04-27 05:26:44 [ERROR] - Error restoring 35k_020_cba_perfhw_3681_vm_mysql_3326.tabular_wid from file (null): Creating index 'IDX_WID' required more than 'innodb_online_alter_log_max_size' bytes of modification log. Please try again.
ALTER TABLE `35k_020_cba_perfhw_3681_vm_mysql_3326`.`tabular_wid`
 ADD  UNIQUE KEY `IDX_WID` (`wid`);
```
...
```
2021-04-27 05:59:54 [ERROR] - Error restoring 35k_020_cba_perfhw_3681_vm_mysql_3326.audited_instance from file (null): Creating index 'upd_txn' required more than 'innodb_online_alter_log_max_size' bytes of modification log. Please try again.
ALTER TABLE `35k_020_cba_perfhw_3681_vm_mysql_3326`.`audited_instance`
 ADD  KEY `upd_txn` (`upd_txn`);
2021-04-27 05:59:54 [INFO] - Thread 5 shutting down
```
...

_Originally posted by @VMEMachuca in https://github.com/maxbube/mydumper/issues/284#issuecomment-827789971_

**Comment by davidducos** [comment]
@VMEMachuca, take into consideration that you are using an online alter, so, you will need to increase innodb_online_alter_log_max_size at DB level.

**Comment by davidducos** [comment]
I'm closing it as this is a consequence of execute an online alter on a database with heavy workload. I don't see any solution at MyDumper level as innodb_online_alter_log_max_size needs to be tune.

**Comment by bato3** [comment]
@davidducos I have this error on table with 3 indexes, when last is reversed first. 
In this table I have 164504937  rows. 

Perhaps the solution would be to split this operation into parts so that each key is added separately? 

And I think it would be worth adding a warning that such a problem may occur. (Estimate needs at the line insertion stage and issue a warning.)

Besides, `innodb_online_alter_log_max_size` is a dynamic variable, so I think it can be increased before adding indexes. 

```sql
Creating index 'fk_watched_episodes_animes1_idx' required more than 'innodb_online_alter_log_max_size' bytes of modification log. Please try again.
ALTER TABLE `m1040_strona`.`watched_episodes`
 ADD  UNIQUE KEY `we_unique` (`user_id`,`episode_id`),
 ADD  KEY `fk_watched_episodes_episodes1_idx` (`episode_id`),
 ADD  KEY `fk_watched_episodes_animes1_idx` (`title_id`,`user_id`) USING BTREE,
```

**Comment by davidducos** [comment]
Hi @bato3 
MySQL documentation says about innodb_online_alter_log_max_size: `This log file stores data inserted, updated, or deleted in the table during the DDL operation`. So, the issue is happening because the table is being used during the ALTER TABLE that adds the indexes. 
Makes no sense to me to split the operation in parts, it will make the import to take longer and you might end up having the same issue. 
It is up to you to set innodb_online_alter_log_max_size as there is no way that myloader could know before starting the import how large the log should be.
