### ISSUE TITLE
MySQL 8

### ISSUE THREAD

**Issue by notRuslan** [maxbube/mydumper#328]
Time to time block all tables (InnoDB).
Version 0.10.3.
v0.9.5 - hasn't that bug.

**Comment by davidducos** [comment]
Hi @notRuslan, 
The issues is on SHOW TABLE STATUS: https://jira.percona.com/browse/PS-7183

On version v0.9.5 was the main connection which executes the show table status, but newer version is a thread the one that executes it. I still investigating.

**Comment by davidducos** [comment]
Looks like #176 introduced this behavior.

**Comment by davidducos** [comment]
To reproduce the issue:
```
service mysql stop 
rm /var/lib/mysql/* -rf 
service mysql start
echo "create database issues_328; create table issues_328.issues_328 (id int auto_increment primary key, val int);" | mysql
for i in $(seq 1 100) ; do 
echo 'insert into issues_328 (val) values (ceiling(rand()*100));' | mysql issues_328; sleep 0.01; 
done; 
mydumper -B issues_328 -o issues_328
```

**Comment by davidducos** [comment]
This issue is not present in latest version of MySQL Server.
