### ISSUE TITLE
Could not execute query: Unknown error

### ISSUE THREAD

**Issue by DevOpserzhao** [maxbube/mydumper#335]
Could not execute query: Unknown error

**Comment by DevOpserzhao** [comment]
Broken table detected, please review: sys.x$schema_table_statistics_with_buffer

**Comment by davidducos** [comment]
Can you share more information? At least we need the command executed and the log file

**Comment by DevOpserzhao** [comment]
nohup mydumper --regex '^(?!(mysql|test|performance_schema|sys|information_schema))'  -u root -p g   -h 127.0.0.1 -P 3306  -G -E -R -t 16   -o /data/mydumper/ &

**Comment by DevOpserzhao** [comment]
This database instance is recovered from alicloud RDS physical files

**Comment by davidducos** [comment]
And the mydumper log file?

**Comment by DevOpserzhao** [comment]
> And the mydumper log file?

Broken table detected, please review: sys.x$schema_table_statistics_with_buffer

**Comment by DevOpserzhao** [comment]
if (!is_view && row[ecol] == NULL) {
      g_warning("Broken table detected, please review: %s.%s", database,
                row[0]);
      dump = 0;
    }

**Comment by DevOpserzhao** [comment]
I have used regular expressions to block the sys database, but why do I still report sys errors?

**Comment by davidducos** [comment]
Can you test with latest version?

**Comment by davidducos** [comment]
@DevOpserzhao, please let us know if you need more help on it.
