### ISSUE TITLE
Mydumper Backup failed ,Point Out Segmentation Fault (core dumped) 

### ISSUE THREAD

**Issue by xiaobing0508** [maxbube/mydumper#338]
The log shows [error] - could not read data from XXX.XXX: Lost connection to MySQL server during query.
This has happened many times.
Back up again on the original backup directory?

**Comment by xiaobing0508** [comment]
My parameters is  -G -E -R -l 90 -K -e --less-locking -t 4 -r 1000

**Comment by fredricj** [comment]
I cant reproduce this locally.
The lost connection is probably due to the data.
The segmentation fault should be possible to fix if we get a stack trace, either by running it through gdb or from the core dump (how will depend on you distribution).

**Comment by davidducos** [comment]
Hi @xiaobing0508, 

I'm agree with @fredricj, I saw in the past that some tablename causes segmentation faults. Can you review if the table names has dot, or any other special char?

**Comment by davidducos** [comment]
No answer for over a month.

**Comment by xiaobing0508** [comment]
table name have _ and . 
Is it because of this ?

**Comment by xiaobing0508** [comment]
Table name or database name ?

**Comment by davidducos** [comment]
Hi @xiaobing0508, the _ might not be the issue, but the . for sure is causing the problem... there are other issues reporting and we are going to be solving all those issue in v0.10.9 which will be released on August.

**Comment by xiaobing0508** [comment]
But my table name not have . ,It's just that the table name is longer.

**Comment by davidducos** [comment]
Can you share the table name?

**Comment by xiaobing0508** [comment]
Such as TOPIC_WEIBO_AUTHOR_45f0a86d566d43ec833712d30b2ab645 , Mysql parameters  net_read_timeout and net_write_timeout,Is it because of this ?
