### ISSUE TITLE
Error message don't show thread no.

### ISSUE THREAD

**Issue by bato3** [maxbube/mydumper#344]
I have 
```
** Message: 14:21:16.379: Thread 14 restoring indexes `db`.`table`
```
But error don't report it
```
** (myloader:3495801): CRITICAL **: 14:21:16.380: Error restoring db.table from file (null): 
```

And  I noticed, that `db.table` are not quoted. (My OCD XD)

**Comment by davidducos** [comment]
Adding the quotes will be simple, but adding the thread number... that will not, I will need to add the thread_id to several functions. I will need some time to think how to implement this simpler.
