### ISSUE TITLE
Mydumper --outputdir directory rights 

### ISSUE THREAD

**Issue by bato3** [maxbube/mydumper#345]
I believe that the default rights should be used when creating a directory. Access control should be done through the parent directory.
In my case, another user is backing up and another is uploading the data to an external server. 

I told about: [`g_mkdir(new_directory, 0700)`](https://github.com/maxbube/mydumper/blob/master/mydumper.c#L2409)

**Comment by davidducos** [comment]
Hi @bato3  What do you think about adding --outputdir-mode ?

**Comment by bato3** [comment]
It't good and bad option. 

- It is good because we give you a choice.
- It is bad because too many options make it difficult to find them.

In my opinion, the most sensible option is to inherit rights from a parent. But I think `g_mkdir` requires` mode`, so doing it this way can be a pain. g_stat (, .st_mode)

And then there is the problem of old scripts.

After thinking, I propose to choose one of the options:
- strong breaking changes: 0755
- soft breaking changes: mode from parent
- rejection of this suggestion

**Comment by fredricj** [comment]
I agree with @bato3 on this. Adding a new option might not be the best course of action

**Comment by davidducos** [comment]
Hi @bato3 ,
I don't want to reject this suggestion. 
Strong breaking change with 0750 will be simplest way to proceed.
