### ISSUE TITLE
[loader] drop all tebles before import / specify the restore order 

### ISSUE THREAD

**Issue by bato3** [maxbube/mydumper#356]
As I wrote in https://github.com/maxbube/mydumper/issues/342#issuecomment-849592202I have a table that references a column that isn't PRIMARY KEY. When I use `--innodb-optimize-keys`, the key in this column is not created and the import process reports an error: A foreign key from another table must refer to an index (which is not there)

This could be fixed by intelligent key parsing (checking to see if any foreign keys refer to a custom column) or by deleting the tables with those foreign keys beforehand. Or specifying tables to which fast-index should not be applied, eg. `--skip-optymize`
The fastest option would be to delete all tables before importing.

Though I dream of another option: to specify a list of tables to be restored first. Something like `--restore-order`.

**Comment by bato3** [comment]
or change order to 
```
** Message: 15:36:34.019: Dropping table or view (if exists) `m1040_strona`.`pool_vote`
** Message: 15:36:34.122: Dropping table or view (if exists) `m1040_strona`.`rate_recommendations`
** Message: 15:36:34.196: Dropping table or view (if exists) `m1040_strona`.`staff_versions`
** Message: 15:36:34.287: Dropping table or view (if exists) `m1040_strona`.`chapters`
** Message: 15:36:34.043: Creating table `m1040_strona`.`pool_vote`
** Message: 15:36:34.139: Creating table `m1040_strona`.`rate_recommendations`
** Message: 15:36:34.218: Creating table `m1040_strona`.`staff_versions`
** Message: 15:36:34.330: Creating table `m1040_strona`.`chapters`
```

**Comment by davidducos** [comment]
We are setting FOREIGN_KEY_CHEKS to all connections, so there should be no worries about the drop or creation of the constraints. The issue that you are explaining, it is not sufficient to implement any new parameter or this new behavior. Take into consideration that implementing DROP and then CREATE stage, means that we need to sync between operations, which is something that I would like to avoid.
