### ISSUE TITLE
Enabling MAX_EXECUTION_TIME option 

### ISSUE THREAD

**Issue by grassil-mmfg** [maxbube/mydumper#368]
**MyDumper**
It is possible to introduce this parameter to manage the "Query execution was interrupted, maximum statement execution time exceeded".

Many thanks,
Luca

**Comment by davidducos** [comment]
Hi @grassil-mmfg , I think that this will be possible when we merge https://github.com/maxbube/mydumper/tree/config_file
Can you test that branch?

**Comment by davidducos** [comment]
Hi @grassil-mmfg, #370 has been merged. Can you test again?

**Comment by davidducos** [comment]
Closing without confirmation
