### ISSUE TITLE
Release 0.10.7 shows wrong version number

### ISSUE THREAD

**Issue by 3eka** [maxbube/mydumper#371]
**Describe the bug**
Downloaded mydumper-master.zip (on that page is written Lastest release is 0.10.7).
However, when compiled:
```
:; mydumper --version
mydumper 0.10.6, built against MySQL 5.7.33
```

**To Reproduce**
download mydumper-master.zip (from https://github.com/maxbube/mydumper) and compile it
Click on `Latest release` button on page https://github.com/maxbube/mydumper/releases/latest opens https://github.com/maxbube/mydumper/releases/tag/v0.10.7

**Expected behavior**
Expecting version 0.10.7

**Log**

**Backup**

**Environment (please complete the following information):**
 - OS version: CentOS 6.10, CentOS 7.9 (and relevant MySQL Community 5.7.33 versions)
 - MyDumper version: mydumper 0.10.6, built against MySQL 5.7.33

**Additional context**

**Comment by davidducos** [comment]
Hi @3eka, this is undesirable but expected. To fix it, I will need 2 PR on each release to avoid it. I will take this into account for future releases but this won't be fix in the near future. 
We need more people involve in the project to be able to do it smoothly. Nowadays, it is mostly me, if you (or anyone) want to get involved, just let me know! We need developers, testers and release managers!! Any idea is welcome!!
