### ISSUE TITLE
improve estimated_step

### ISSUE THREAD

**Issue by huangzhiyong** [maxbube/mydumper#373]
func **get_chunks_for_table**  is used to calculate the size of each chunk. In some special cases, the value of **estimated_step** (`estimated_step = (nmax - nmin) / estimated_chunks + 1`) will be very large. It is recommended to add a global parameter. When **estimated_step** is greater than the global parameter, the block size will use the global parameter.

**Comment by davidducos** [comment]
Hi @huangzhiyong , 100% agree with you!! I saw this in the past but didn't find the time to work on a solution. I really appreciate if you can add the code needed, if not, don't worry I will do it for next release. BTW, I would like to use  estimated_step as the name of the global variable and change to: `local_estimated_step = (nmax - nmin) / estimated_chunks + 1)` for the function calculation.

**Comment by huangzhiyong** [comment]
Hi @davidducos, C is not my strong point, I tried to push a RP #376
