### ISSUE TITLE
[Question] how to use mydumper to backup 2 tables with different where conditions?

### ISSUE THREAD

**Issue by jmbkeyes** [maxbube/mydumper#377]
Right now, mydumper supports backup several tables at one time, and also support --where condition.  
If I want to dump 2 tables, each table with different where conditions, so need  I have to use two mydumper commands to dump the tables with its own where condition？

**Comment by davidducos** [comment]
Hi @jmbkeyes, yes, --where means that you expect a partial backup, running 2 or more commands if needed should not be a problem. However, will be nice to have where clause per table if you want to load dev/testing/QA environments or if you want incremental backups. If you like, you could implement this feature, but I recommend to wait until release of https://github.com/maxbube/mydumper/pull/370, as it would be nice to have something like:
```
[db.table]
where = column > 20
```

**Comment by jmbkeyes** [comment]
@davidducos  I'm not familiar with C, but I  appreciate your suggestion “where cause per table in config file”.

**Comment by jmbkeyes** [comment]
BTW, does where condition support sub query?

**Comment by TracyBin** [comment]
Hi, what is your command when backup 1 table?

**Comment by TracyBin** [comment]
Hi, what is your command when backup 1 table?After we use where clause, a large number of files are generated, and the contents of the files are repeated


> BTW, does where condition support sub query?

**Comment by jmbkeyes** [comment]
@TracyBin 
my command is very simple as below.
mydumper --host 10.0.0.12 --port 3306 --user root -p test --database bocai --tables-list trainee_sub_center_info --outputdir /root/test --no-schemas --complete-insert --where centerId=1

There're about 2.5 millions records in the table, and only 8000 records match the where condition.

**Comment by davidducos** [comment]
@jmbkeyes there are no restrictions to use sub queries. You can try and let me know.

@TracyBin you are using OR, you need to enclose the whole condition in a (), try this and let me know:
`
mydumper -u root --password='123456' -S /data/mysql2/socket/mysql.sock -B test -T change_detail2 --triggers --events --routines --rows=50000 -t 8 --trx-consistency-only --where="create_time >=' ( 2020-11-06' or change_type in ('4','5') )" --outputdir /nvdata/change_detail2`

**Comment by jmbkeyes** [comment]
@davidducos  sub query works, but I have to give the database name in subquery. Otherwise I'll receive a critical  error log ( No database selected)

**Comment by davidducos** [comment]
@jmbkeyes Thank you for sharing!! makes total sense that you have to add the database name... I will try to include your feature request earlier than v0.10.11, but I'm not sure that it might be possible...

**Comment by TracyBin** [comment]
> @jmbkeyes there are no restrictions to use sub queries. You can try and let me know.
> 
> @TracyBin you are using OR, you need to enclose the whole condition in a (), try this and let me know:
> ` mydumper -u root --password='123456' -S /data/mysql2/socket/mysql.sock -B test -T change_detail2 --triggers --events --routines --rows=50000 -t 8 --trx-consistency-only --where=" ( create_time >=' 2020-11-06' or change_type in ('4','5') )" --outputdir /nvdata/change_detail2`

@davidducos    Yes,you are right.  And I found answer in the source code.
If no()，where condition like this:
```
 where change_id >a and change_id <(a+row_per_file) and create_time < '2021-04-18' or change_type in ('4','5'); 
```
> The above SQL will generate a large number of duplicate files
with(),where condition like this:
```
where change_id >a and change_id <(a+row_per_file) and （create_time < '2021-04-18' or change_type in ('4','5')）; 
``
