### ISSUE TITLE
[QUESTION] Increase CPU usage Tuning restore

### ISSUE THREAD

**Issue by roni-estein** [maxbube/mydumper#380]
I may be reading this wrong, but it appears that my loader is bot using much of the CPU, I'm running this on an Apple M1

Here is a baseline, using mysqldump the basic restore

```bash
Restoring Database riu_dev
206.62s user 17.66s system 25% cpu 14:56.19 total
```

using mydumper / myloader is faster but seems to not use much of the CPU. 

```bash
time myloader -u root -B riu_dev -d ~/backups/mydumper/riu_dev -t 12 -o -q 500 
myloader -u root -B riu_dev -d ~/backups/mydumper/riu_dev -t 12 -o -q 500  
11.56s user 19.28s system 5% cpu 9:37.60 total
```

I created the backup as follows:

```bash
time mydumper -u root -e -B riu_dev -o ~/backups/mydumper/riu_dev -t 14 -F 5
```

Are there any strategies to increase the speed get and get it to use more of the CPU

macos 11.4 apple M1
Version 10.7

Database is approximately 12G

**Comment by davidducos** [comment]
Hi @roni-estein, 

Were the DB is running? is it in your laptop? if not, then, the db (or db resources) or network might be the bottleneck. You are not going to be able to use more CPU if CPU is not needed...

**Comment by roni-estein** [comment]
Its all local. I'm trying to find something thats kind of closer to percona xtrabackup speeds. I've had 0 luck trying to just restore 1 DB from percona you need to do the whole system. And it's brittle. So if I take an xbstream from one server onto my dev machine I have to blow away the rest of the databases.

I thought this might be there if I gave it enough sauce. xtrabackup can handle a complete restore ridiculously fast, using file IO and more resources. But it has so many other issues. 

Thanks for taking the time. If you know of better strategies I'd be happy to chase them down.

**Comment by davidducos** [comment]
Did you tried [partial backups](https://www.percona.com/doc/percona-xtrabackup/2.3/innobackupex/partial_backups_innobackupex.html) ?

you can increase the amount of threads depending in the amount of files taht you are processing. Don't forget to use -v 3 to see the progress, that might give you and idea which is the file/table that is taking longer.

**Comment by roni-estein** [comment]
You sir are awesome!

All the demo's leave out critical steps or have some issues however this one and I only found it to explain the issue got my first test working! Although I still need to follow up with more depth.

https://www.percona.com/blog/2020/04/10/percona-xtrabackup-backup-and-restore-of-a-single-table-or-database

There are two tricks to anyone finding this discussion.

1. Don't stop your mysql server as they tell you too in every single article. There is no way back from that, you need to start mysql in innodb safe mode at least level 4 and tablespaces are locked! Skipping that step allows you to continue.

2. Make sure you have an empty mysql dump, and build the empty database or database table before trying to restore into it! also not really mentioned anywhere. But since it has the whole reference issue it's keeping a ton of meta data on the tables and if there is even a slight difference, the whole thing appears to blow up.

3. Make sure you are only dropping your table space right before you add that specific file, then import the new table space. That made it work for me.

I'll experiment more but thanks @davidducos I had given up. But I jsut restored a 2 GB table in under a min. Which is pretty helpful for transform test failures.

**Comment by davidducos** [comment]
@roni-estein you can also check [this page](https://github.com/maxbube/mydumper/wiki/Restore-optimizations) to improve the restoration times.

**Comment by fredricj** [comment]
@roni-estein you could also try mysqlsh's util.dumpSchemas() and util.loadDump() https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-utilities-dump-instance-schema.html https://mysqlserverteam.com/mysql-shell-8-0-21-speeding-up-the-dump-process/
