### ISSUE TITLE
Explicitly set client and server charset to binary

### ISSUE THREAD

**Issue by oakad** [maxbube/mydumper#385]
Not sure if it's an issue, but mydumper emits the following line into its data dump: `"/*!40101 SET NAMES binary*/"`.

I believe, this may break on some configurations and can be mitigated by explicitly passing `MYSQL_SET_CHARSET_NAME  "binary" ` to mysql connection options.

**Comment by davidducos** [comment]
Hi @oakad, you can set names with --set-names which has been added in v0.10.5. If you need more info about it, check https://github.com/maxbube/mydumper/pull/154. 
Please, let me know if there is an issue or a feature request that I'm not reading from your comment.

**Comment by oakad** [comment]
Currently we are facing an issue, with a database configured to be "utf8mb4", but the actual text columns in it contain binary data (legacy dbs are like that). This results in totally botched escaping in the sql mydumper's dump (dumping from `mysql` command works fine, btw).

We will do some further experimenting with "--set-names" and such and report.

**Comment by davidducos** [comment]
From my understanding, we should test a database with utf8mb4 and columns with binary, what db version?

**Comment by oakad** [comment]
5.7

From documentation it follows that `mysql_real_escape_string` uses the charset set on connection. Right now, no charset is explicitly set. But one matching the `--set-names` should probably be.

**Comment by druud** [comment]
Please show an example of how these values look, in every stage.
- the table definition and the column definition
- the value in the column (also as HEX())
- the way it looks like in: mysql -BNe 'SELECT id, mycol FROM MyTable WHERE id = N'
- the way it looks in mysqldump's dump.

**Comment by ssgoburdhun** [comment]
Same issue encountered.

At the import level using myloader, the following characters are seen:

```sql
INSERT INTO `mytable` VALUES\x0A(1,2,'2016-05-09 14:53:00','com...' at line 2996 : INSERT INTO `mytable` VALUES
```

Version: mydumper_0.10.7-2.buster_amd64.deb
Import command: 
```bash
myloader -h <remote_ip> -u importuser -p $pass -P 3307 -v 3 -d . -o -s mydb --innodb-optimize-keys --sync-before-add-index -t 10
```
Table: latin1 with no converted charset/collation
DB: utf8mb4

**Comment by oakad** [comment]
Sorry for the late reply. We don't copy databases too often. :-)

I've attached an excerpt from the dump:
[dump.txt](https://github.com/maxbube/mydumper/files/7207337/dump.txt)

Notice how many unescaped non-safe characters are there. Those break mysql import quite substantially.

The table is defined as following:

```
CREATE TABLE `stringlookup` (
  `nStringLookupId` int(11) NOT NULL AUTO_INCREMENT,
  `sStringValue` varchar(127) NOT NULL,
  PRIMARY KEY (`nStringLookupId`),
  UNIQUE KEY `idx_sStringValue` (`sStringValue`)
) ENGINE=InnoDB AUTO_INCREMENT=186506 DEFAULT CHARSET=utf8
```
Let's review the entry under the key 29199:

> select hex(sStringValue) from stringlookup where nStringLookupId = 29199\G
> *************************** 1. row ***************************
> hex(sStringValue): 03020106

What the mysql dumps:
> mysql -BNe 'SELECT sstringvalue FROM mydb.stringlookup WHERE nstringlookupid = 29199'
> \<shell fails to render>

**Comment by oakad** [comment]
After thinking about it a bit, may be it's an ok dump. The real problem may happen on load - it seems mysql "eats" invalid utf8 codepoints.

**Comment by druud** [comment]
If you need to store raw bytes, alter the column to varbinary.

In any case, dump+load should not (silently) hurt data, beyond what gets refused noisily by the destination.

**Comment by oakad** [comment]
As explained in the op post, the damage is already done.

The table contains malformed strings. I can not simply drop those, so I'm trying to find a way to copy them over.

**Comment by druud** [comment]
Indeed, that is why I suggested the alter to varbinary. My experience is that it conserves the data, so it can then be used more easily. You could then even rename the column, and add a virtual column with the old name, that produces the proper string for most cases (for if you don't control the application side).

**Comment by oakad** [comment]
Suppose, this means that the issue can be closed, as there's nothing mydumper can do. :-)
