### ISSUE TITLE
Need to manually symlink the libraries

### ISSUE THREAD

**Issue by michaeldg** [maxbube/mydumper#39]
Hi,

For mydumper to compile I needed to manually symlink the libraries:
[root@dbtst1 mydumper-0.9.1]# history|grep ln
  648  ln -s /usr/lib64/libpthread.so.0 /usr/lib64/libpthread.so
  658  ln -s /usr/lib64/libm.so.6 /usr/lib64/libm.so
  667  ln -s /usr/lib64/libdl.so.2 /usr/lib64/libdl.so

The other mysql libraries were detected.

I don't know if this is mydumper bug or MariaDB packaging bug, reporting on both places. I tried 0.9.1 and master branch from github.

I am running MariaDB 10.1.21 from the community edition repo:
[root@dbtst1 mydumper-0.9.1]# rpm -qa|grep -i mariadb
MariaDB-common-10.1.21-1.el7.centos.x86_64
MariaDB-shared-10.1.21-1.el7.centos.x86_64
MariaDB-devel-10.1.21-1.el7.centos.x86_64
MariaDB-compat-10.1.21-1.el7.centos.x86_64
MariaDB-client-10.1.21-1.el7.centos.x86_64

On this box, I reinstalled  various versions of various libraries (rhel mariadb, mariadb 10.1.9, percona 5.6, percona 5.7) a couple of times.

I hope this can be fixed, as said I don't know which project is to blame.

Thanks!

**Comment by michaeldg** [comment]
MariaDB JIRA issue: https://jira.mariadb.org/browse/MDEV-12065

**Comment by maxbube** [comment]
Hi, 

This is not a mydumper or MariaDB issue, is the system your are using to compile it :)

Try installing glibc-devel that must resolve all your problems.
