### ISSUE TITLE
Feature Request: Optimal Index Creation

### ISSUE THREAD

**Issue by SuperQ** [maxbube/mydumper#4]
Percona has an interesting trick for improving SQL dump restores[0](https://www.percona.com/doc/percona-server/5.6/management/innodb_expanded_fast_index_creation.html).  It removes the secondary keys from the table schema, restores the backup, and then does an `ALTER TABLE ADD KEY` for each of the secondary keys.

This has some restore performance, and key compactness improvements.
- Tables load more quickly because they do not need to keep secondary keys up to date while the primary key data is being written
- Secondary keys are created in a very optimal/compact way because all of the column data is available at the time of key block creation.

It would be nice if mydumper would create two schema files per table, one for the primary table schema, and one for the secondary keys.

Then myloader could process the table loading and apply the secondary key schema changes after all primary key rows are restored.

**Comment by maxbube** [comment]
Hi SuperQ, 

David Ducos did some work on it in the past, there is branch on lp with that code. I will work with him at some point to add some improvements and be able to merge it here as still needs to handle better FK and UNIQUE keys.

**Comment by pmkane** [comment]
I second the request to merge David's branch.  It makes a huge difference more multi-terabyte database restores.

We worked around this by post-processing the -schema files to remove secondary indices.  We write out ALTERs for the secondary indices in a second file and then run those after the myloader restore has completed.  It works well, but having it integrated would be fantastic.

**Comment by onethumb** [comment]
Any progress on this?

**Comment by kshcherban** [comment]
Also in this article https://www.percona.com/blog/2015/01/21/importing-big-tables-large-indexes-myloader/ there was an improvement developed to myloader.
Can you please advise if that code https://code.launchpad.net/~david-ducos/mydumper/ was merged into this repo?

**Comment by breisig** [comment]
Any update on this being merged?

**Comment by cyborg00222** [comment]
about 1 year later, and the code from david is not working anymore. (with libperconaserverclient20) I'll try to build a patch, but help would be appreciated :) - @maxbube is there a branch were you already implemented smth? or do i need to start from scratch?

**Comment by devhen** [comment]
Could really use this. With mysqldump the data is inserted and then the indexes are enabled afterward. Would love to see that sort of functionality added as an option. As it stands this myloader doesn't work for us because its much too slow on our largest tables. :cry:
