### ISSUE TITLE
[ Question ] About myloader support custom character sets

### ISSUE THREAD

**Issue by jackwener** [maxbube/mydumper#402]
Hi, I have some question about `database custom character sets`
I think that if we want to support it, we just modify the `-schema-create.sql` file in `myloader`.
Will the project support this feature later?
Maybe is there some difficulty I have not considered.

**Comment by davidducos** [comment]
Hi @jackwener 
Aren't you able to do it using: #370  ??
Please, let me know

**Comment by jackwener** [comment]
I am willing to do something for mydumper. However, I'm sorry that I am
busy on working and  I'm not familiar with c lanaguage programing.

**Comment by jackwener** [comment]
What' more, I found that the document of `mydumper and myloader` lack of some instruction and warning.
If project is in need of help at this point, I am happy to contribute.

**Comment by davidducos** [comment]
Hi @jackwener, yes! We need help! Feel free to send pull request about any change that you consider and I will give my opinion and approval. Thanks!!!
