### ISSUE TITLE
[BUG] mydumper against PS8 8.0.25 Error dumping create database ... Invalid utf8 character string:

### ISSUE THREAD

**Issue by hubiongithub** [maxbube/mydumper#405]
**Describe the bug**
updated mydumper to 0.11.1 (Ubuntu .deb from github)
multiple runs against Percona Server 8.0.25

show databases;                                                                                                                                     
+--------------------+                                                                                                                                                            
| Database           |                                                                                                                                                            
+--------------------+                                                                                                                                                            
| hubi               |                                                                                                                                                            
| information_schema |                                                                                                                                                            
| monitoring         |                                                                                                                                                            
| mysql              |                                                                                                                                                            
| performance_schema |                                                                                                                                                            
| sakila             |                                                                                                                                                            
| sys                |                                                                                                                                                            
| ttt                |                                                                                                                                                            
+--------------------+                                                                                                                                                            
8 rows in set (0,00 sec) 

**To Reproduce**
Command executed:
* mydumper with all the parameters
/usr/bin/mydumper --socket=... -t 1 -v 3 -o ./ttt -c -e -E -G -R -L ./ttt.log
2021-09-23 13:10:56 [INFO] - Thread 1 dumping db information for `sys`
2021-09-23 13:10:56 [INFO] - Thread 1 dumping schema create for `<90>K^B<B4>}^?`
2021-09-23 13:10:56 [ERROR] - Error dumping create database (<90>K^B<B4>}^?): Invalid utf8 character string: '\x90K\x02\xB4}\x7F'

/usr/bin/mydumper --socket=... -t 1 -v 3 -o ./ttt2 -c -e -E -G -R -L ./ttt2.log
2021-09-23 13:11:47 [INFO] - Thread 1 dumping db information for `sys`
2021-09-23 13:11:47 [INFO] - Thread 1 dumping schema create for `<90>K^B<D8>+^?`
2021-09-23 13:11:47 [ERROR] - Error dumping create database (<90>K^B<D8>+^?): Invalid utf8 character string: '\x90K\x02\xD8+\x7F'

/usr/bin/mydumper --socket=... -t 1 -v 3 -o ./ttt3 -L ./ttt3.log
2021-09-23 13:14:27 [INFO] - Thread 1 dumping db information for `hubi`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping schema create for `hubi`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping db information for `monitoring`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping schema create for `monitoring`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping db information for `mysql`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping schema create for `mysql`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping db information for `sakila`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping schema create for `sakila`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping db information for `sys`
2021-09-23 13:14:27 [INFO] - Thread 1 dumping schema create for `<A0><D9>^Aܚ^?`
2021-09-23 13:14:27 [ERROR] - Error dumping create database (<A0><D9>^Aܚ^?): Invalid utf8 character string: '\xA0\xD9\x01\xDC\x9A\x7F'

seems to be the sys database, which I think should be excluded like performance_schema ans information_schema

**Expected behavior**

**Log**
see above

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough
ls -al
total 622020
drwxr-x--- 10 mysql mysql      4096 Sep 17 10:39  .
drwxr-xr-x 11 root  root       4096 Sep 13 15:12  ..
-rw-r-----  1 mysql mysql        56 Jul  2 10:24  auto.cnf
-rw-r-----  1 mysql mysql         8 Sep 17 10:39  db-zzz-115-u.pid
drwxr-x---  2 mysql mysql      4096 Sep  6 14:23  hubi
-rw-r-----  1 mysql mysql    196608 Sep 23 13:45 '#ib_16384_0.dblwr'
-rw-r-----  1 mysql mysql   8585216 Jul 19 11:15 '#ib_16384_1.dblwr'
-rw-r-----  1 mysql mysql      4051 Sep 17 10:39  ib_buffer_pool
-rw-r-----  1 mysql mysql  12582912 Sep 23 13:45  ibdata1
-rw-r-----  1 mysql mysql 268435456 Sep 23 13:45  ib_logfile0
-rw-r-----  1 mysql mysql 268435456 Sep 23 13:45  ib_logfile1
-rw-r-----  1 mysql mysql  12582912 Sep 17 10:39  ibtmp1
drwxr-x---  2 mysql mysql      4096 Sep 17 10:39 '#innodb_temp'
drwxr-x---  2 mysql mysql      4096 Jul  2 10:25  monitoring
drwxr-x---  2 mysql mysql      4096 Jul 19 11:15  mysql
-rw-r-----  1 mysql mysql  32505856 Sep 23 13:45  mysql.ibd
-rw-r-----  1 mysql mysql         9 Jul 19 11:15  mysql_upgrade_info
drwxr-x---  2 mysql mysql      4096 Jul 19 11:15  performance_schema
-rw-------  1 mysql mysql      1676 Jul  2 10:24  private_key.pem
-rw-r--r--  1 mysql mysql       452 Jul  2 10:24  public_key.pem
drwxr-x---  2 mysql mysql      4096 Aug 24 13:31  sakila
drwxr-x---  2 mysql mysql      4096 Jul  2 10:24  sys
drwxr-x---  2 mysql mysql      4096 Sep  1 13:42  ttt
-rw-r-----  1 mysql mysql  16777216 Sep 23 13:45  undo_001
-rw-r-----  1 mysql mysql  16777216 Sep 23 13:45  undo_002

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04
 - MyDumper version: [ mydumper --version ] 0.11.1
 - Server version: 8.0.25-15 Percona Server (GPL), Release '15', Revision 'a558ec2'

**Additional context**

**Comment by hubiongithub** [comment]
mydumper --version
mydumper 0.10.7, built against MySQL 5.7.33-36

this Version does not have this error, but also operates on sys schema

**Comment by davidducos** [comment]
Hi @hubiongithub 
Error found, working on the fix.

**Comment by davidducos** [comment]
@hubiongithub, 

Thank you for reporting this bug, new release will be available later today

**Comment by davidducos** [comment]
Hi @hubiongithub,
Release: https://github.com/maxbube/mydumper/releases/tag/v0.11.1-2

**Comment by hubiongithub** [comment]
Hello 
as 0.11.1-3 was allready released I tried that version, confirm, error is gone.
