### ISSUE TITLE
[BUG][myloader] Fail to upload dump from v0.10.7x version

### ISSUE THREAD

**Issue by pbabilas** [maxbube/mydumper#418]
**Describe the bug**
As in topic when trying to upload dump from old version of mydumper it ends with error:

https://share.merce.com/files/MyYg_ifzd6.png

**To Reproduce**
Command executed:
* dump db older version
* import dump with newest mydumper

**Log**
- only from screen

**Environment (please complete the following information):**
 - Dumps are taken at centos 8, import at ubuntu, osx
 - MyDumper version: 0.10.7-2 <- old, 0.11.1-3 <- new

**Comment by davidducos** [comment]
Hi @pbabilas, take into consideration that new major version releases are not compatible with earlier version. So, this kind of error is expected. You could sort this issue out modifying the file name.

**Comment by davidducos** [comment]
Hi @dshorthouse, 
v0.11.1 has a unique format, that I need to document, but basically it is <db_name>[.<table_name>[.<number>|-schema-post|-schema-create|.metadata|.checksum]|-schema-create][.sql|.sql.gz] but you need to consider that when db_name or table_name has . or other not allowed char, it will be replaced by mydumper_<id>.

**Comment by pbabilas** [comment]
> @pbabilas, please let me know if you need anything else, if not, I will close this issue.

Answered, but not solved :( neet to support both version for a half year - it's time we store our daily backups.

**Comment by pbabilas** [comment]
> @pbabilas honestly, I didn't take into consideration your scenario, and that is my fault, but it is a lesson learned. In future releases I will consider compatibility with all backups, and leave the code to support it, for at least 1 major release or give the user the procedure to migrate their backups.

Thanks for understanding. And thanks for a good work!
