### ISSUE TITLE
[BUG] `--regex` will scan other databases that isn't matched

### ISSUE THREAD

**Issue by jackwener** [maxbube/mydumper#423]
**Describe the bug**
There are some databases `DB1`, `DB2`(big), `DB3`(big).

When I try backup `DB1` using ` --regex '^(DB1\.)'`,  the memory will increasing soon and I found mysql may scan(or scan scheme info maybe) `DB2`, `DB3` in `log` but `DB2`, `DB3` isn't backup, there isn't files about `DB2`, `DB3`.

If I use`-B 'DB1'`, there wouldn't be problem.

If I drop `DB2`, `DB3`,  the memory will not increasing soon. same with `-B 'DB1'`

**Expected behavior**
The result is same in between ` --regex '^(DB1\.)'`and `-B 'DB1'`.

**Environment**
OS version: Debian buster
MyDumper version: mydumper 0.10.7-2, built against MySQL 10.3.22

**Comment by davidducos** [comment]
Hi @jackwener,

I have a question and an explanation for you. 
First, the question: is the backup content the same on both cases? if the answer, is `yes, the backup has the same files`, then I would say that the problem that you are describing is related in how we get the data. 
Now, the second, `-B` and `--regex` are 2 very different features, I know that there is a gap in what MyDumper can do and what is documented, but actually, you described the differences:
- -B scan only the database set as parameter
- --regex select all the tables and the applies the regular expression. 

Makes sense now?

**Comment by jackwener** [comment]
Thanks for your reply @davidducos .

According to the result, I guess the implementation of `regex` is 
- Get all databases 
- Get all tables with `SHOW TABLE STATUS;`
- The name of databases + tables name  =>  all `db.table`
- match all `db.table` with `regex` 

instead of 
- Get all databases 
- match databases with `regex` 
- Get all tables from databases selected
- The name of databases + tables name  =>  `db.table`
- match `db.table` in the databases selected with `regex` 

If it is first implementation, when another database is large, the match will cost much memory

**Comment by jackwener** [comment]
> * -B scan only the database set as parameter
> * --regex select all the tables and the applies the regular expression.

Yes, backup content is same.

I think it is related with `how we get the data`, especially the process of matching `regex`

**Comment by davidducos** [comment]
@jackwener yes, it is the first! and there is no way that we could implement that 2 stages regex validation. We have also the -T option to filter tables (which currently have issues :D) that you could use if you want to, that is going to be "faster" than other options.

Can you confirm that there is no bug here and close it? or am I missing something?
