### ISSUE TITLE
Feature Request: Skip Databases greater than arbitrary size

### ISSUE THREAD

**Issue by ernstae** [maxbube/mydumper#43]
Today, it came up that maybe we would like to have a strategy where databases of a certain size should be excluded from a mydumper backup.

Could you implement a feature that would allow a user to specify `--exclude-db-sized=100M` for instance (meaning, any db's larger than 100MB)

This is somewhat ambiguous of a feature, but could do something like this to determine if the database is larger than the size:

(assuming bash -- and assuming dbsize is an integer in MB) 

```mysql --raw -e "
SELECT dbname FROM (
SELECT table_schema dbname, Round(Sum(data_length + index_length) / 1024 / 1024, 1) dbsize
FROM   information_schema.tables
GROUP  BY table_schema ) as derived_table WHERE dbsize <= ${dbsize} ;"```

**Comment by maxbube** [comment]
Hi @ernstae I don't think that this would be a good feature for a backup tool. I would suggest you to use a wrapper or some kind of automation to implement this outside mydumper.
