### ISSUE TITLE
support CSV format

### ISSUE THREAD

**Issue by ronylei** [maxbube/mydumper#436]
Support CSV format export and import

**Comment by davidducos** [comment]
After #307 is merged, you will be able to use:
```
./mydumper --load-data --fields-terminated-by=',' --fields-enclosed-by='"' --fields-escaped-by='\' --lines-terminated-by="\n"
```
to get CSV format.

**Comment by jkthedba** [comment]
can we have column header included in csv if need to use csv as independent file for ETL
