### ISSUE TITLE
SET GLOBAL sql_mode='';

### ISSUE THREAD

**Issue by str** [maxbube/mydumper#438]
From my understanding the idea is to use mydumper/myloader. To create a dump of a DB, and then import it as is, FAST.  The idea of running any validations could slow the data import.  BUT if the original data is broken, myloader should not care.

Because of the different mysql versions my DB has used, and different sql_modes used,  there are some inconsistencies, that should not be validaded, IMHO when loading the DB. 

`Invalid default value for 'dateField'`

is the most common error I get, and none of the data with that error gets imported.  I was able to get arround it using `SET GLOBAL sql_mode='';` but I think that mode should be set by default for myloader.

**Comment by str** [comment]
@davidducos , let me see if I understand it right.  I have to create a config file, something like this?

```
[myloader_variables] 
SET GLOBAL sql_mode='';
```

and load it via `myloader --config $pathToFile...` 

Did I understood it right?

What if it loads a default file by default, if exists, something like ~/.myloader.cnf? That way we will set it once and not need to define it or forget about it every time we run the loader

What if it uses the same ~/.my.cnf as the default mysql cli, and just reads the config defined in the `[myloader_variables]` block?

Just some ideas.

**Comment by davidducos** [comment]
Hi @str,
No, it follows the default mysql configuration structure:
```
[myloader_variables] 
sql_mode=''
```
The `--config $pathToFile` is correct


> What if it loads a default file by default, if exists, something like ~/.myloader.cnf? That way we will set it once and not need to define it or forget about it every time we run the loader
> What if it uses the same ~/.my.cnf as the default mysql cli, and just reads the config defined in the [myloader_variables] block?

We could implement something like that, or use mysql defaults files, and you will need to configure MyDumper as any other of the MySQL tools. We could discuss that in another issue as it will be a new feature request. Let's do that!

**Comment by str** [comment]
I'm creating a new issue then. Thank you.
