### ISSUE TITLE
Default config file

### ISSUE THREAD

**Issue by str** [maxbube/mydumper#440]
Being able to define a custom config file via the  --config flag is great, but having to remember setting it every time is something I will sooner or later forget.  Could mydumper/myloader use a default config file if exists?

What if it uses the same ~/.my.cnf as the default mysql cli, and just reads the config defined in the [mydumper] / [myloader] block?  

We could set both, mysql variables, like `sql_mode=''` as well as mydumper/myloader flags like 

```
[mydumper]
triggers=true
events=true
routines=true
views=true
compress=false
```

This way we can skip setting them every time

**Comment by davidducos** [comment]
@str I accept any proposal... but I think that will be nice to read from /etc/mydumper.cnf by default and then use --config for any other case.

**Comment by MJabirBaig** [comment]
Hi,

I am testing mydumper utility for mysql backups, i am getting the following errors while importing data using myloader
`myloader --user=dba --ask-password --socket=/database/mysql/mysql.sock --threads=10 --overwrite-tables --verbose=3 --defaults-file=/etc/my.cnf --directory=/database/backup/mydumper/fullbkp --logfile=/database/backup/mydumper/fullbkp_restore.log

(myloader:11335): GLib-CRITICAL **: 09:06:42.409: g_key_file_has_group: assertion 'key_file != NULL' failed
Enter MySQL Password:

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed

(myloader:11335): GLib-CRITICAL **: 09:06:50.590: g_key_file_get_keys: assertion 'key_file != NULL' failed
`
can some one help me with a solution

**Comment by davidducos** [comment]
Hi @MJabirBaig,

What is the content of /etc/my.cnf ?? I almost sure that it doesn't contain the groups that myloader needs. Anyways, we have a bug as it should not show those entries

**Comment by davidducos** [comment]
@MJabirBaig, please, check #1123
