### ISSUE TITLE
Need help in restoring the 700GB database using MyLoader

### ISSUE THREAD

**Issue by hasan505** [maxbube/mydumper#448]
Hi,
         I am using MyLoader to restore the 700GB database. I tried the import three time now. First I have got only one error, was able to import it without any errors second time. But however when I am running the MyLoader for third time from a similar capacity machine I am seeing multiple errors. My data dump is in Azure VM which is a 16vCore machine and I am exporting the dump into Azure managed MySQL (16vCore)

$ myloader --host=<servername> --user=<username> --password=<Password> --directory=./backup --queries-per-transaction=500 --threads=32 --compress-protocol --ssl --verbose=3 -e 2>myloader-logs.txt

The import into Azure MySQL is taking around 10hours, I am not worried about the time taken but I want a clean run of MyLoader

I am seeing two types of errors

(myloader:27208): CRITICAL **: 03:03:44.175: Error restoring cubic.bck_c5_job_candidate_30mar19 from file cubic.bck_c5_job_candidate_30mar19.sql.gz: Lost connection to MySQL server during query

(myloader:27208): CRITICAL **: 03:03:44.176: Error switching to database cubic whilst restoring table c5_tags

Below are the current values of destination system
max_allowed_packet: 1073741824
innodb_write_io_threads: 16
Scaled up Storage tier 1500 GB
connect_timeout: 240 seconds
net_write_timeout: 6000 seconds
net_read_timeout: 120 seconds
wait_timeout: 300 seconds

I am using mydumper 0.10.1, built against MySQL 5.7.32-35

Please guide me with this issue.

**Comment by davidducos** [comment]
@hasan505 
Let me know if you still have this issue. Closing it for now.
