### ISSUE TITLE
Incorrect Privilege Assignment

### ISSUE THREAD

**Issue by ihsinme** [maxbube/mydumper#451]
https://github.com/maxbube/mydumper/blob/e4efa3bd72a17578f3d43bebefc2ab61aedc5567/mydumper.c#L1281

Good afternoon.
I noticed that your code uses umask (0) with calls to open files without setting permissions.
then your program will work with files with wide enough permissions and can, which can lead to security problems.
I suggest to restrict access rights.

**Comment by ihsinme** [comment]
@davidducos
I apologize for the delay in answering.
I didn't notice your question.(
since we are talking about limiting files, this mask is correct.

**Comment by davidducos** [comment]
Perfect, I will be pushing this change on v0.11.5.
