### ISSUE TITLE
Cannot create a JSON value from a string with CHARACTER SET 'binary'.

### ISSUE THREAD

**Issue by mfrederico** [maxbube/mydumper#46]
Here is how I create a JSON CHARSET error (**Server version: 5.7.17-0ubuntu0.16.04.1**)

### Create the DB
```
CREATE DATABASE mydumper_love;
USE mydumper_love;
CREATE TABLE `love_this_project` (id int unsigned not null, json_data json not null);
INSERT INTO `love_this_project` VALUES (1,"{\"show\": false, \"value\": \"google store url\"}");
```
### Dump the DB
`mydumper <insert credentials here> -B mydumper_love -o ./mydumper_love`
### Next Load the DB
`myloader <insert credentials here>  -o -d mydumper_love/ mydumper_love`
```
Error restoring mydumper_love.love_this_project from file mydumper_love.love_this_project.sql: Cannot create a JSON value from a string with CHARACTER SET 'binary'.
```

_Am I doing something wrong as to why my JSON columns aren't working?_

I did find this:
[http://stackoverflow.com/questions/38078119/mysql-5-7-12-import-cannot-create-a-json-value-from-a-string-with-character-set](http://stackoverflow.com/questions/38078119/mysql-5-7-12-import-cannot-create-a-json-value-from-a-string-with-character-set
)

**Comment by mfrederico** [comment]
I found this will work with JSON:
```
INSERT INTO `love_this_project` VALUES (1,CONVERT("{\"show\": false, \"value\": \"google store url\"}" USING UTF8MB4);
```

Apparently it's a FEATURE of mysql and not a bug .. But you have to CONVERT json fields with UTFMB4 ..

**Comment by mfrederico** [comment]
This is all we'd need to start testing json dumps: 
```
diff --git a/mydumper.c b/mydumper.c
index b7f7f5e..fee41ed 100644
--- a/mydumper.c
+++ b/mydumper.c
@@ -2791,6 +2791,7 @@ guint64 dump_table_data(MYSQL * conn, FILE *file, char *database, char *table, c
                g_string_append(statement_row, "\n(");
 
                for (i = 0; i < num_fields; i++) {
+
                        /* Don't escape safe formats, saves some time */
                        if (!row[i]) {
                                g_string_append(statement_row, "NULL");
@@ -2800,9 +2801,11 @@ guint64 dump_table_data(MYSQL * conn, FILE *file, char *database, char *table, c
                                /* We reuse buffers for string escaping, growing is expensive just at the beginning */
                                g_string_set_size(escaped, lengths[i]*2+1);
                                mysql_real_escape_string(conn, escaped->str, row[i], lengths[i]);
+                               if (fields[i].type == MYSQL_TYPE_JSON) g_string_append(statement_row, "CONVERT(");
                                g_string_append_c(statement_row,'\"');
                                g_string_append(statement_row,escaped->str);
                                g_string_append_c(statement_row,'\"');
+                               if (fields[i].type == MYSQL_TYPE_JSON) g_string_append(statement_row, " USING UTF8MB4)");
                        }
                        if (i < num_fields - 1) {
                                g_string_append_c(statement_row,',');
```

**Comment by maxbube** [comment]
Hi mfederico, 

Thanks for the patch, I will review it and merge if it ok and will be available in the next release.

**Comment by vigo2** [comment]
For reimporting, simply adding an introducer like `_utf8mb4'...exported string...'` is enough, as the actual character data is correct, and MySQL simply doesn't want to guess (see https://bugs.mysql.com/bug.php?id=79066).

When using a table like
```
CREATE TABLE test (data JSON, a VARCHAR(255) AS (data->"$.a"));
INSERT INTO test (data) VALUES ('{"a":"b"}');
```
then mydumper fails, too, with `Error 3144: Cannot create a JSON value from a string with CHARACTER SET 'binary'` (even though all it seems to do is SELECTing).

Even weirder, while mydumper is running, other sessions (connected with non-binary charsets) fail to INSERT into the table as well, with error 3144. And to top it off, this behaviour sometimes persists until - mostly guessing here - the table's metadata is refreshed.

Tested on 5.7.19-0ubuntu0.16.04.1-log.

**Comment by vigo2** [comment]
As for the "weird" and "weirder" parts above, I've opened https://bugs.mysql.com/bug.php?id=88288 - it's most definitely a MySQL bug. I'm currently using "--no-locks" as the only available workaround.

**Comment by segedunum** [comment]
It appears that although this was fixed in mydumper, myloader is still throwing up this issue:

`Error restoring ias_production.ias_note from file table.sql: Cannot create a JSON value from a string with CHARACTER SET 'binary'.`

**Comment by segedunum** [comment]
I'm still getting this problem when restoring with 0.9.5.

`Error restoring ias_production.ias_note from file database.table.sql: Cannot create a JSON value from a string with CHARACTER SET 'binary'.`
