### ISSUE TITLE
[BUG] myloader:18733  can not myloader to the database.

### ISSUE THREAD

**Issue by zengpeng5281314** [maxbube/mydumper#462]
**Describe the bug**
The version of mysql I use is 5.6.44. The data is about 500G.when i exec myloader.Sometimes the inserter reports an error without a specific reason for the error. When I take out the insert statement and execute it, it can be executed successfully。

how can I myloader success？？？please tell me！！thanks

**To Reproduce**
Command executed:
* mydumper -u root -p ****** -P 3306 -h *****  -r 500000 -B mail  -t 10  -o /root/bak
* myloader -u root -p ****** -S /tmp/mysql.sock -B mail -t 10 -o -d /root/bak

**Log**
** (myloader:18733): CRITICAL **: 10:58:12.601: Error restoring: INSERT INTO `mail_user_email_sync_record` VALUES
('4254','14134677',14254251,'2021-09-03 12:20:47'),
('1366','14134679',14254252,'2021-09-03 12:20:47'),
('3767','14134678',14254253,'2021-09-03 12:20:47'),
('6983','14134680',14254254,'2021-09-03 12:21:28'),
('4365','14134681',14254255,'2021-09-03 12:21:29'),
('1254','14134682',14254256,'2021-09-03 12:21:44'),
('6900','14134683',14254257,'2021-09-03 12:22:05'),
('6048','14134684',14254258,'2021-09-03 12:22:08'),
...

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9]
 - MyDumper version: [ mydumper 0.11.1-3]

**Comment by davidducos** [comment]
Hi @zengpeng5281314, without the error number it is very difficult to guess. Can you use -v 3 and -L log to get more info?

**Comment by zengpeng5281314** [comment]
> Hi @zengpeng5281314, without the error number it is very difficult to guess. Can you use -v 3 and -L log to get more info?

Hello, davidducos! I added -v 3 and -L, the output just tells error, there is no specific reason. I took out the sql that reported the error. Execution can be [successful。]

the tip **2021-11-02 19:54:09 [ERROR] - Error restoring: INSERT INTO `mail_draft_auto_save_content` VALUES**

**Comment by davidducos** [comment]
@zengpeng5281314 can you test with latest version?

**Comment by zengpeng5281314** [comment]
hello，davidducos！i used dumper version 0.11.1-3。My server is 8C16G. I tried with 5 threads and no errors were reported. Probably because the original command used was 10 threads。But i don't understand why？

**Comment by zengpeng5281314** [comment]
@davidducos i used dumper version 0.11.1-3。My server is 8C16G. I tried with 5 threads and no errors were reported. Probably because the original command used was 10 threads。But i don't understand why？

**Comment by davidducos** [comment]
Hi @zengpeng5281314, oh good that you found a way to make it work, but it doesn't make sense to me. We need to get the error number. I'm working on a couple of tickets to have better logging but it will be available on the next release. I will let you know and we can test it again when it is available. What do you think?

**Comment by zengpeng5281314** [comment]
Hi @davidducos , this version really does not have any error information. So I have no way to locate the problem. Wait for your next release . I will try again. See what causes it ?
