### ISSUE TITLE
[ Enhancement ] Remove directory when stream is used and -o is not specified

### ISSUE THREAD

**Issue by str** [maxbube/mydumper#464]
**Describe the bug**
Stream creates export folder and leaves it there after streaming.

**To Reproduce**
Command executed:
mydumper -B my_database --stream > /tmp/my_database.mydump

**Expected behavior**
Should not see any files after I list the files in current folder.
I should also be able to run the command in a folder I don't have permissions, because I was not expecting to write in current folder.  

**Environment (please complete the following information):**
mydumper 0.11.3, built against MySQL 5.7.33-36

**Comment by davidducos** [comment]
Hi @str I was not able to reproduce the issue that you have. What OS are you using?

**Comment by str** [comment]
![image](https://user-images.githubusercontent.com/123817/139699805-286f5c77-0f31-4ac1-be62-cd01eb340713.png)

Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

**Comment by davidducos** [comment]
AAAHHH!!! yes the directory is not being removed!!! I never had the intention to remove it, but for sure it will be a good idea to remove it when it is not specified. This is not a bug, it will be enhancement. Thank you @str to point it out. I will be changing for v0.11.5.

**Comment by davidducos** [comment]
I'm thinking we could create the directory when -o is not specified on myloader... :D working on it...

**Comment by davidducos** [comment]
This:
```
if (-o is set)  write to the directory
if (-o is not set)  export as stream
```
Could be implemented when we do: https://github.com/maxbube/mydumper/issues/456
> I'm not a fan of "magic"/unknown-results, for example, the unique export folder destination. You can´t know it beforehand if you don´t set it. But that's just my opinion.
I understood... but mydumper needs a directory always, so if it is not set, you should know that we are going to create it. That has been decide long time ago. 
So, to implement this:
```
if (-o is not set)  export as stream
```
We need to do a huge announcement, it will be for v0.12.1, which will give us some time to stream to mature.  

> Is that a bug, or is that an enhancement? Should that be another issue?
neither of them, you are using the tool incorrectly, as the default behaviour is to create a directory in current path when -o is not set, this means that it will fail, even if you use --stream or not. The stream functionality is not sending the data as soon it gets it, it uses the output directory as a buffer, and when the file is closed, it is streamed.

**Comment by str** [comment]
> neither of them, you are using the tool incorrectly, as the default behaviour is to create a directory in current path when -o is not set, 

What about, if -o is not defined, to write to a temp folder, instead of current folder, before sending to stream?

**Comment by davidducos** [comment]
@str ,
that is why we have --stream...
currently we use --stream to tell mydumper that we are going to be streaming. If we start to use -o to determine if we are going to stream or not, then --stream will be point less and it will be deprecated. 
If you want to define a temp folder, where do we get that path? another variable? default place? we end up in the same scenario which we are trying to avoid. 
It is not easy... I know... we are not going to be able to cover every single scenario that we want, that is why we need to establish the best use case. BTW, we could keep --stream and you can use -o as the temp folder...

**Comment by str** [comment]
> If you want to define a temp folder, where do we get that path? another variable? default place? we end up in the same scenario which we are trying to avoid.

If the scenario we are trying to avoid is not being able to write to a folder:  most apps do use a [temp folder](https://stackoverflow.com/questions/8087805/how-to-get-system-or-user-temp-folder-in-unix-and-windows), defined by the OS, to write stuff to disk where they know they have perms to write.  

> if we start to use -o to determine if we are going to stream or not, then --stream will be point less and it will be deprecated.

`-- stream` is a new flag, that can be removed before more people get used to it. Again, IMHO there is no need for it. It should be by default if -o is not set.  

There is a famous quote about it:

> _There are two types of people in the world:_
> _1) Those who can extrapolate from incomplete data._

I do understand it breaks backwards compatibility for users who do not set -o expecting to have a random folder generated for them. I do understand that this has not to be easily applied without some plan, and document users about the change for multiple versions before rolling that change, but IMHO, it makes sense.

What does not make sense to me? Having both -o AND --stream set. Having neither of the flags set and generating a random output folder.  I'm not saying it's wrong, nor I disapprove current solution. I'm saying, for me, it was weird.

But again, thank you for your great work @davidducos
