### ISSUE TITLE
Error `Couldn't acquire global lock` when dumping

### ISSUE THREAD

**Issue by 64kramsystem** [maxbube/mydumper#467]
**Describe the bug**

When dumping a database residing on an RDS read replica, I get the following error:

```
# edited
** (mydumper:158459): CRITICAL **: 10:01:20.602: Couldn't acquire global lock, snapshots will not be consistent: Access denied for user '<root_user>'@'%' (using password: YES)
```

**To Reproduce**

Command executed:

```sh
# edited
mydumper \
    -h $db_host -u $root_user -p $pwd \
    --verbose 3 \
    --compress-protocol \
    --database $db \
    --nregex $a_long_regex \
    --where $condition
```

**Expected behavior**

It's not clear what the problem is, in particular, due to the `Access denied` warning, which is not correct (at least from a user perspective), since without correct credentials, the dump would not proceed at all.

**Log**

This is only the relevant part (top of the log), since after this, it's standard dump messages:

```
# edited
** Message: 10:59:03.344: Server version reported as: <mysql_version>
** Message: 10:59:03.421: Connected to a MySQL server

** (mydumper:241369): CRITICAL **: 10:59:03.574: Couldn't acquire global lock, snapshots will not be consistent: Access denied for user '<root_user>'@'%' (using password: YES)
** Message: 10:59:03.650: Started dump at: 2021-11-02 10:59:03
** Message: 10:59:03.728: Written master status
** Message: 10:59:03.807: Written slave status
```

**Backup**

The export works as intended; all the expected tables/data are present.

**Environment (please complete the following information):**

 - OS version: Client = 20.04, Server = Not known (RDS instance)
 - MyDumper version: current `regex` branch (commit 0b14ec3)

**Additional context**

Possibly, the issue may be related to the db server being an RDS read replica, but this is a shot in the dark :slightly_smiling_face:

**Comment by davidducos** [comment]
Hi @64kramsystem ,

I think that https://answers.launchpad.net/mydumper/+question/236273 will explains why your are not able to get the lock and provide a work around.

**Comment by 64kramsystem** [comment]
> Hi @64kramsystem ,
> 
> I think that https://answers.launchpad.net/mydumper/+question/236273 will explains why your are not able to get the lock and provide a work around.

Thanks. I'll try it, then close the issue :smiley:

**Comment by 64kramsystem** [comment]
> Hi @64kramsystem ,
> 
> I think that https://answers.launchpad.net/mydumper/+question/236273 will explains why your are not able to get the lock and provide a work around.

That did it. Thanks! :star_struck:

**Comment by kaykhan** [comment]
> > Hi, im also having this problem with aws rds mysql.
> > i read the related article but im still a little confused on what the solution was?
> > Im using
> > ```
> > mydumper --host <redacted> --user dba --password <redacted>  --verbose 3 --database <redacted>  --complete-insert --build-empty-files --compress --threads 16 --trx-consistency-only
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I read somewhere --trx-consistency-only is the same as --single-transaction
> 
> Either use `--lock-all-tables` or `--no-locks`, depending on the context/requirements. We use the former, for privileged users, and the latter for ones with less privileges; the latter produces a potentially inconsistent dump (which can be fine - it's all about requirements smile).

Doesen;t locking the tables cause disruption to live prod servers?
