### ISSUE TITLE
Save mydumper version somewhere

### ISSUE THREAD

**Issue by 3eka** [maxbube/mydumper#470]
Hi, 
I have tested several version of this tool, and could not  find case where mydumper writes (metadata?) version number used to dump (version 0.10.7 used here):
```
:; mydumper --set-names utf8 -v 3 -o /tmp/mydumper-test -u USER -p PASS -h HOST -B database
** Message: 12:17:28.520: Server version reported as: 5.7.19-log
** Message: 12:17:28.520: Connected to a MySQL server

** Message: 12:17:28.523: Started dump at: 2021-11-02 12:17:28
...
** Message: 12:17:40.994: Finished dump at: 2021-11-02 12:17:40
```
No version number is present in any file under /tmp/mydumper-test directory

It would be useful to have that info (for example to the log file, or metadata file), since it seems that there is no compatibility between some earlier versions and new ones

What do you think?
Did I missed that option?

Regards.

**Comment by davidducos** [comment]
Hi @3eka, 
The backup version should not be needed as it should be compatible, BUT as we saw on latest releases, we were not able to accomplish it. So, it will be a really good idea to keep track of it. The only issue is that we modify the information in the metadata file, it might break scripts that users had written based on that file. Do you think that will be enough in the log file? that will be much easier.

**Comment by 3eka** [comment]
Hi @davidducos ,

yes, log file (or stdout output) would help too, although not perfect (one has to remember to check it for version).
Thanks for considering this.
Regards.
