### ISSUE TITLE
add option to order rows by PK

### ISSUE THREAD

**Issue by igroene** [maxbube/mydumper#48]
Would  be useful to have mydumper implement the option similar to mysqldump.
Per mysqldump manual:
--order-by-primary

Dump each table's rows sorted by its primary key, or by its first unique index, if such an index exists. This is useful when dumping a MyISAM table to be loaded into an InnoDB table, but makes the dump operation take considerably longer.

**Comment by cr1st1p** [comment]
also useful for backups with data deduplication support (borg, restic) or rsync, in case not a lot of data is changing.
