### ISSUE TITLE
[BUG] Output dir from var

### ISSUE THREAD

**Issue by vadzimkaredzinkokoba** [maxbube/mydumper#480]
**Describe the bug**
When I'm using key [-o, --outputdir] it creates dir automatically, if it doesn't exist
But when I want to create a dump directory manually, write it to a variable to use, the dumper will create a default directory "export - ***". it ignores var in key -o

**To Reproduce**
```
DUMPDIR=$(mkdir -p /home/ubuntu/sql-dump) or DUMPDIR=$(/home/ubuntu/sql-dump)

mydumper \
--host=$DB_HOST_PROD_REPL \
--user $DB_USER_PROD_REPL \
--password ${DB_PASS_PROD_REPL} \
-B $DB_NAME_PROD_REPL \
--compress \
--compress-protocol \
--lock-all-tables \
-o $DUMPDIR \
--build-empty-files \
-G \
-E \
-R \
-L /home/ubuntu/mydumper-log.log \
-t 10 \
-v 3
```
**Expected behavior**
directory will not be created automatically when the o key is used
maybe this will fix the var problem

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04
 - MyDumper version: mydumper 0.11.3, built against MySQL 5.7.33-36

**Comment by davidducos** [comment]
Hi @vadzimkaredzinkokoba, I think that you are setting DUMPDIR incorrectly:
```
root@ubuntu-focal:/tmp/mydumper# DUMPDIR=$(mkdir -p /home/ubuntu/sql-dump) ; echo $DUMPDIR

root@ubuntu-focal:/tmp/mydumper# DUMPDIR=$(/home/ubuntu/sql-dump) ; echo $DUMPDIR
-bash: /home/ubuntu/sql-dump: Is a directory
```
You should do it like this:
```
DUMPDIR="/home/ubuntu/sql-dump"
```
BTW, I was not able to reproduce your issue.

**Comment by vadzimkaredzinkokoba** [comment]
ubuntu@bastion:~$ DUMPDIR="~/sql-dump/created-dump"
ubuntu@bastion:~$ echo $DUMPDIR
~/sql-dump/created-dump
ubuntu@productionbastion:~$


`
#!/bin/bash

mkdir -p ~/sql-dump/created-dump
DUMPDIR="~/sql-dump/created-dump"


DB_PASS_PROD=********************
DB_HOST_PROD=production-replica-mysql.***************.eu-west-1.rds.amazonaws.com
DB_USER_PROD=user
DB_NAME_PROD=production_database

mydumper \
--host=$DB_HOST_PROD \
--user $DB_USER_PROD \
--password ${DB_PASS_PROD} \
-B $DB_NAME_PROD \
--lock-all-tables \
-o $DUMPDIR \
-t 4 \
--build-empty-files \
-G \
-E \
-R \
-K \
-L ~/sql-dump/mydumper-replica-$(date '+%d_%m_%Y__%H_%M_%S').log \
-v 4
`
