### ISSUE TITLE
[BUG] Report ERROR[ It was not possible to process file: (null) ] when has only data file

### ISSUE THREAD

**Issue by yifei1024** [maxbube/mydumper#494]
step1:

/usr/bin/mydumper -h 127.0.0.1 -P 3306 -u root -p pwd-t 10 -F 256 --skip-tz-utc --no-schemas -B d1 -x "^(d1.t1)$" -o /home/t1/

step2:

 /usr/bin/myloader -h 127.0.0.1 -P 3306 -u root -p pwd  -d  /home/t1/

then report It was not possible to process file: (null) 

it means loss -schema-create.sql file

but why mydumper wont create it?

how can it resolve it？

**Comment by davidducos** [comment]
Hi @yifei1024, there is a bug report template, can you paste all the info requested there in  here?

**Comment by yifei1024** [comment]
> Hi @yifei1024, there is a bug report template, can you paste all the info requested there in here?

ok, i have create new
