### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by christianbundy** [maxbube/mydumper#5]
Would a Docker installation be within the scope of this project? I'd be happy to contribute code, and being able to spin up a Docker container without having to do a native install may make the project more accessible to use. Thanks for your work on this project!

**Comment by maxbube** [comment]
Hi Christian, I didn't have to time to think on that, what I know is that Andy Moore from percona did something related. You can read more here https://www.percona.com/blog/2015/09/21/containing-logical-backups-mydumper-docker/

**Comment by mprokopov** [comment]
Here is convenient docker image https://github.com/confirm/docker-mysql-backup

**Comment by pataquets** [comment]
@christianbundy et all: You're very welcome to test the PR at #567 which fixes building your image straight from source just pointing to the repo's URL in a convenient one-liner.

**Comment by pataquets** [comment]
Docker image building has been documented on #570.
