### ISSUE TITLE
Error while dumping from remote host (RDS instance)

### ISSUE THREAD

**Issue by ethicalmohit** [maxbube/mydumper#51]
Hey,

I am trying to take a dump of a DB inside an RDS instance from mydumper but getting below error. Its not picking up the host but taking the instance private ip.

Command: 
`mydumper --database=root --host=my-rds-host --user=root --port=3306 --password=PASS --outputdir=/home/ubuntu/mydump --rows=50000 --threads=6  --compress --build-empty-files --compress-protocol`

Error:
`** (mydumper:20329): CRITICAL **: Error connecting to database: Access denied for user 'root'@'172.31.24.205' (using password: YES)`

**Comment by wagnerbianchijr** [comment]
Mohit,

Are you able to connect to your RDS/MySQL Server from the same host where
you're executing mysqldump? You're pointing out the correct endpoint on
--host ?


--
*Wagner Bianchi*
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-07-05 9:23 GMT-03:00 Mohit Kumar <notifications@github.com>:

**Comment by wagnerbianchijr** [comment]
Sorry, I would say mydumper, not mysqldump


--
*Wagner Bianchi, +55.31.8654.9510*
Oracle ACE Director
<https://apex.oracle.com/pls/otn/f?p=19297:4:105567988301604::NO:4:P4_ID:4541>,
Oracle Certified Expert (OCE/MySQL)
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-07-05 9:54 GMT-03:00 Wagner Bianchi <wagnerbianchijr@gmail.com>:

**Comment by ethicalmohit** [comment]
I changed the password of the instance as it contains "$". Is there anyway we can pass password by standard tty. ?

**Comment by wagnerbianchijr** [comment]
are you explicitly mentioning the password on the command line or you have
a .my.cnf file, for example?


--
*Wagner Bianchi, +55.31.8654.9510*
Oracle ACE Director
<https://apex.oracle.com/pls/otn/f?p=19297:4:105567988301604::NO:4:P4_ID:4541>,
Oracle Certified Expert (OCE/MySQL)
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-07-05 10:39 GMT-03:00 Mohit Kumar <notifications@github.com>:

**Comment by ethicalmohit** [comment]
Yes, I was mentioning the password on the command line.

**Comment by wagnerbianchijr** [comment]
Is it OK now? How is it going?


--
*Wagner Bianchi, +55.31.8654.9510*
Oracle ACE Director
<https://apex.oracle.com/pls/otn/f?p=19297:4:105567988301604::NO:4:P4_ID:4541>,
Oracle Certified Expert (OCE/MySQL)
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-07-05 10:43 GMT-03:00 Mohit Kumar <notifications@github.com>:

**Comment by ethicalmohit** [comment]
@wagnerbianchijr It's working pretty fine. Thank you. I am closing the case.

**Comment by sridhar-zwayam** [comment]
> I changed the password of the instance as it contains "$". Is there anyway we can pass password by standard tty. ?

You can try enclosing the password within single quotes in the command 
--password='******$****'
