### ISSUE TITLE
--logfile option is not working with absolute path of the file.

### ISSUE THREAD

**Issue by ethicalmohit** [maxbube/mydumper#53]
Hey,

I am trying to store logs under a particular directory where it's dumping the data but I am not able to do so. Although it works if I use the direct filename and the file exists on the path from where I am trying to execute the script.

`
db_dumper.sh: line 24: --logfile=/opt/platform/newone/17-07-26-10-31/db_dumper.log: No such file or directory`

**Comment by maxbube** [comment]
Hi @ethicalmohit that error is from a shell script not mydumper binary. I will close this issue but please open a new one reporting the mydumper command line and error if this is a real bug.

BTW --logfile is working for me, of course if the user running mydumper has write privileges on the destination dir.
