### ISSUE TITLE
How to disable --long-query-guard ?

### ISSUE THREAD

**Issue by ethicalmohit** [maxbube/mydumper#54]
Hey,

I just don't want the dumper to KILL or to Define any time out for any query. I want it to complete the dump with all queries anyway.

Is there any solution to disable --long-query-guard and Also to complete all queried while dumping regardless of the time they take?

**Comment by maxbube** [comment]
Hi, 

There is no way to disable it but setting it to a high value, but if mydumper is doing a FTWRL I would not recommend that. 

In the only way you can increase it safely is if you are using PS with PBL or running mydumper with --no-locks or --lock-all-tables as in all those cases FTWRL is not used. And BTW I would need to disable that check when those are used.

**Comment by verwilst** [comment]
Maybe #295 is a step in the right direction?
