### ISSUE TITLE
How can I record myloader log？

### ISSUE THREAD

**Issue by oracle1521** [maxbube/mydumper#60]
@maxbube 
When I use myloader to loader the dumps, I add this job into a crontab,but I can't record the logs.Can you help me ? 
I recommend adding a parameter -L like mydumper to record the myloader's logs.

**Comment by wagnerbianchijr** [comment]
oracle1521, on your scripts you said you added to cron, can you redirect
the output to a log file?


--
*Wagner Bianchi, +55.31.8654.9510*
Oracle ACE Director
<https://apex.oracle.com/pls/otn/f?p=19297:4:105567988301604::NO:4:P4_ID:4541>,
Oracle Certified Expert (OCE/MySQL)
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-09-26 7:46 GMT-03:00 oracle1521 <notifications@github.com>:

**Comment by oracle1521** [comment]
@wagnerbianchijr 
I  run the myloader shell like this:
`/usr/local/bin/myloader -u root -p passwd -t 32 -S /tmp/mysql.sock -o -C -v 3 -d /home/backup/  > 1.log `
It doesn't record the log 
I  run the myloader shell like this:
`nohup /usr/local/bin/myloader -u root -p passwd -t 32 -S /tmp/mysql.sock -o -C -v 3 -d /home/backup/ > 1.log &`
It works.
But when I put the command into a shell, and I add this shell into a crontab like this:
```
# cat a.sh 
/usr/local/bin/myloader -u root -p passwd -t 32 -S /tmp/mysql.sock -o -C -v 3 -d /home/backup/
# crontab -l
00 3 * * * /home/mysql/a.sh > /home/mysql/new.log
```
It doesn't record the log
How can I record the myloader logs,I really need your help.thanks

**Comment by wagnerbianchijr** [comment]
oracle1521,

I did a small test and the results are below:

#: crontab
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR
sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed
*/2 * * * * root myloader -t 2 -o -C -v 3 -d /opt/backup/mydumper -v 3 >
/tmp/logfile 2>&1

#: log file
[root@mydumper01 mydumper]# cat /tmp/logfile
** Message: 2 threads created
** Message: Dropping table or view (if exists) `sakila`.`rental`
** Message: Creating table `sakila`.`rental`
** Message: Thread 2 restoring `sakila`.`rental` part 0
** Message: Thread 1 restoring `sakila`.`rental` part 1
** Message: Thread 1 restoring `sakila`.`rental` part 2
** Message: Thread 2 restoring `sakila`.`rental` part 9

Can you try to reproduce it?


--
*Wagner Bianchi, +55.31.8654.9510*
Oracle ACE Director
<https://apex.oracle.com/pls/otn/f?p=19297:4:105567988301604::NO:4:P4_ID:4541>,
Oracle Certified Expert (OCE/MySQL)
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-09-26 22:21 GMT-03:00 oracle1521 <notifications@github.com>:

**Comment by oracle1521** [comment]
@wagnerbianchijr 
Thank you vary much! I got it.
The log output of the myloader script is redirected in the error std.  
I did this test,and I got the output log in /tmp/2.log file.
`# ./myloader -t 2 -o -C -v 3 -d /opt/backup/ -v 3  1>/tmp/1.log  2>/tmp/2.log`
