### ISSUE TITLE
make error when compile with parameter -DWITH_BINLOG=ON 

### ISSUE THREAD

**Issue by oracle1521** [maxbube/mydumper#61]
@maxbube 
When I use cmake to compile with parameter  -DWITH_BINLOG=ON then execute make , I got an error like this:
`# cmake . -DWITH_BINLOG=ON `
`# make `

- Scanning dependencies of target mydumper
- [ 20%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
- /root/mydumper-master/mydumper.c: In function ‘binlog_thread’:
- /root/mydumper-master/mydumper.c:1028:17: error: ‘thrconn’ undeclared (first use in this function)
-    mysql_options(thrconn,MYSQL_READ_DEFAULT_FILE,defaults_file);
-                  ^
- /root/mydumper-master/mydumper.c:1028:17: note: each undeclared identifier is reported only once for each function it appears in
- make[2]: *** [CMakeFiles/mydumper.dir/mydumper.c.o] Error 1
- make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
- make: *** [all] Error 2

**Comment by wagnerbianchijr** [comment]
oracle1521, is it a fresh machine? what's the operational system you're
running this? did you setup all package's dependencies?


--
*Wagner Bianchi, +55.31.8654.9510*
Oracle ACE Director
<https://apex.oracle.com/pls/otn/f?p=19297:4:105567988301604::NO:4:P4_ID:4541>,
Oracle Certified Expert (OCE/MySQL)
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-09-26 7:55 GMT-03:00 oracle1521 <notifications@github.com>:

**Comment by oracle1521** [comment]
@wagnerbianchijr 
it is not a fresh machine, and I have install Mysql5.6.30 ,the operational system is CentOS.
```
# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)
```
I read the README ,and installed the package which CentOS need to install.but stall failed.
The packages I have installed:
`# yum -y install glib2-devel mysql-devel zlib-devel pcre-devel openssl-devel
`
Here is the cmake and make detail logs:
```
# cmake . -DWITH_BINLOG=ON
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using mysql-config: /home/mysql/mysql3306/bin/mysql_config
-- Found MySQL: /home/mysql/mysql3306/include, /home/mysql/mysql3306/lib/libmysqlclient.so;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/librt.so;/usr/lib64/libdl.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- checking for one of the modules 'glib-2.0'
-- checking for one of the modules 'gthread-2.0'
-- checking for module 'libpcre'
--   found libpcre, version 8.32
-- Found PCRE: /usr/include  

CMake Warning at docs/CMakeLists.txt:9 (message):
  Unable to find Sphinx documentation generator


-- ------------------------------------------------
-- MYSQL_CONFIG = /home/mysql/mysql3306/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = ON
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/mydumper-master

# echo $?
0

# make
Scanning dependencies of target mydumper
[ 20%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
/root/mydumper-master/mydumper.c: In function ‘binlog_thread’:
/root/mydumper-master/mydumper.c:1028:17: error: ‘thrconn’ undeclared (first use in this function)
   mysql_options(thrconn,MYSQL_READ_DEFAULT_FILE,defaults_file);
                 ^
/root/mydumper-master/mydumper.c:1028:17: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/mydumper.dir/mydumper.c.o] Error 1
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
make: *** [all] Error 2

# echo $?
2

```
thanks

**Comment by raulp** [comment]
same error here

**Comment by oracle1521** [comment]
@wagnerbianchijr @maxbube 
I need your help~~

**Comment by wagnerbianchijr** [comment]
oracle1521, can you install it with the rpm package meanwhile we're
checking what could be happening?

sudo yum install
https://github.com/maxbube/mydumper/releases/download/v0.9.3/mydumper-0.9.3-41.el7.x86_64.rpm


--
*Wagner Bianchi, +55.31.8654.9510*
Oracle ACE Director
<https://apex.oracle.com/pls/otn/f?p=19297:4:105567988301604::NO:4:P4_ID:4541>,
Oracle Certified Expert (OCE/MySQL)
Email: me@wagnerbianchi.com
Skype: wbianchijr

2017-09-28 22:25 GMT-03:00 oracle1521 <notifications@github.com>:

**Comment by maxbube** [comment]
Hi, 

DWITH_BINLOG=ON is deprecated and will be totally removed in some of the next releases. 

For binlog backups I would recommend to use mysqlbinlog > 5.6. 

Also as @wagnerbianchijr is mentioning you don't need to compile it yourself anymore as packages are now included in the release.

Please let me know if that works for you.
