### ISSUE TITLE
dependencies issues - unable to make with Percona-server-5.7

### ISSUE THREAD

**Issue by sonanchenko** [maxbube/mydumper#62]
Dear Colleagues,

I'm trying to build/install with Percona-server-5.7:

Preconditions:
CentOS Linux release 7.4.1708 (Core)
Percona-server-5.7

STR:
yum install glib2-devel mysql-devel zlib-devel pcre-devel openssl-devel
to build

Issue:
System trying to install Percona-Server-devel-56-5.6.37-rel82.2.el7.x86_64 :
Transaction check error:
  file /usr/bin/mysql_config from install of Percona-Server-devel-56-5.6.37-rel82.2.el7.x86_64 conflicts with file from package Percona-Server-client-57-5.7.19-17.1.el7.x86_64

Question/Issue:
How to install/build mydumper with percona-5.7 ?

I've also tried RPM from https://twindb.com/mydumper-rpm-for-centosrhel/ - same result.

Thank you for any help you can provide

**Comment by maxbube** [comment]
Hi @sonanchenko you use the packages from latest release, mysql libs are compiled static inside the binaries, so you can use it with any mysql release.

yum install https://github.com/maxbube/mydumper/releases/download/v0.9.3/mydumper-0.9.3-41.el7.x86_64.rpm

**Comment by sonanchenko** [comment]
hi @maxbube 
thank you a lot.
I've installed this version without any issues.
