### ISSUE TITLE
I can't specify multiple database

### ISSUE THREAD

**Issue by ajaajalee** [maxbube/mydumper#67]
I have db1,db2,db3.
mydumper -o /tmp/backup/ -B db1 -B db2 -B db3
It was not work option -B about serveral db.
Can I specify to dump serveral db not all database?

**Comment by maxbube** [comment]
Hi @ajaajalee you can use the regex option for that purpose. That would be something like

`mydumper -o /tmp/backup/ --regex='(db1\.|db2\.|db3\.)'`
