### ISSUE TITLE
Option in file and not on CLI ?

### ISSUE THREAD

**Issue by waghanza** [maxbube/mydumper#70]
Hi,

I've found this excellent tool to backup my database. 

However, to make a dump, I have to specify password on the command line.

Is there any configuration file that `mydumper` could read ?

Regards,

**Comment by maxbube** [comment]
Hi @waghanza, mydumper reads [client] defaults as any other mysql client, so you can set the credentials on ~/.my.cnf for the user running mydumper. Or create a creds file and set the path with --defaults-files=/path/to/file

here an example:

```
[client]
user=mydumper_user
password=mydumper_s3cr3t_pass
```

**Comment by waghanza** [comment]
thanks @maxbube 

can I put also `mydumper` specifics options (_threads_, _kill-long-queries_) ... in a *cnf* file ?

**Comment by maxbube** [comment]
Hi @waghanza 

no, mydumper just read them from command line
