### ISSUE TITLE
overwrite-tables option should drop and re-create table just before filling it.

### ISSUE THREAD

**Issue by fraff** [maxbube/mydumper#72]
I've used myloader on staging to restore and anonymize data from production, but myloader first drop and create all tables, then fills them.

As a result, devs are all waiting for tables to be populated.

I would suggest to drop/create/insert in same thread so we can still access "old" data while myloader is working.

Thanks.

**Comment by maxbube** [comment]
Hi @fraff , I don't think that that is good behavior for a general use backup tool. Also I do not consider accessing the data while restoring as good practice, if are also writing there the restore will certainly fail when it hits a duplicate key.

**Comment by fraff** [comment]
Hi @maxbube, I agree, this is not a good behaviour on a production system, but in a development environment that get overwritten with production data twice a week, it's ok.

**Comment by ChristopherSchultz** [comment]
In MySQL, DDL statements cause an implicit commit, so it doesn't matter which thread does the DROP, all connections will immediately see that change unless (1) they are in a REPEATABLE-READ transaction-isolation and (2) they have started a transaction and (3) they have performed a SELECT on the table. In these cases, the DROP TABLE will block until the pending transaction has completed. 

I believe this enhancement request is actually impossible to implement as requested.

Sure, the DROP/CREATE could be moved to another thread, but it's not going to allow you to do what you want to do here (which is to continue to use the "old version" of the table while the "new version" continues to load.

**Comment by fraff** [comment]
My first message was not clear, what myloader does [now](https://github.com/maxbube/mydumper/blob/master/myloader.c#L212) is:
```
for t in table-list
    drop (t)
    create (t)

for t in table-list
    load (t)
```
After the first loop, database is empty and people can't work, so, what
I'd like is:
```
for t in table-list
    drop (t)
    create (t)
    load (t)
```
At some point, table 't1' would contain new data, table 't2' would being loaded
and not accessible but table 't3' would still contain old data.

This is definitely not a good manner for production, but it could be
a nice option for staging.

**Comment by ChristopherSchultz** [comment]
It *could* be a nice option for staging, but the reality is that the database will be inconsistent if the loading algorithm is `repeat { drop, create, load-data }`. It should be very clear from the documentation that this is the case if the order or operations is to change.

**Comment by davidducos** [comment]
@fraff, sorry, but currently (and I don't think that this will change in the future), myloader has 2 stages:
- Schema import
- Data import
and changing it will add mutex and locking structures which are going to make harder to maintain the code for a very specific use case. If in the future, which means, when we have a better loading mechanism, I will be glad to add it, but for now, I will close it.
