### ISSUE TITLE
Isolation level is always REPEATABLE-READ?

### ISSUE THREAD

**Issue by matteraf** [maxbube/mydumper#76]
IMHO, mydumper seems to use always REPEATABLE-READ.
It is possible to choose tx_isolation?

**Comment by maxbube** [comment]
Hi @matteraf,

Its doing that as is the only way to get a consistent backup for innodb without blocking other transactions.

**Comment by matteraf** [comment]
Hi @maxbube 

first of all, thank you for support this tool.  The effort is highly valued. Very appreciated.

I tell you our problem.  When we run mydumper in our instances, wich haves serveral large tables (more than 20GB), this -> https://www.percona.com/blog/2014/10/17/innodb-transaction-history-often-hides-dangerous-debt/

This phenomenon, among other things, can cause the growth of the ibdata1 file (due to undo)  We have experience about this kind of issues.

In such case, I prefer to do "inconsistents" backups.  They are am xtrabackup complement in order to restore particular tables.  I found mydumper very useful to do this.

I don't understand (and excuse me for my ignorance) why READ-COMMITTED isolation level isn't suitable for consistent reads, it worst than REPEATABLE-READ?

Thank you so much.

**Comment by druud** [comment]
On a stopped slave, it can allow READ-COMMITTED.

**Comment by matteraf** [comment]
Hi @druud, how?

**Comment by druud** [comment]
Probably best by just accepting the current isolation level.
The code can check if the SQL_THREAD is off, and then not set REPEATABLE-READ.

**Comment by druud** [comment]
Mainly useful as that would need less grants.
