### ISSUE TITLE
Method to skip a very large number (hundreds of thousands) of tables?

### ISSUE THREAD

**Issue by waptaff** [maxbube/mydumper#77]
A single MySQL database I maintain has about 500K tables, holding almost 1.5TB of data, 99% InnoDB, configured as one file per table, setup as master-slave.

Performing a backup with `mydumper` on the slave needs about 24 hours to complete, and it takes around 6 hours for the slave to catch up with the master afterwards.  That backup is then rsync'd to another machine that takes care of daily/weekly/monthly rotations; so `mydumper` overwrites the previous run's backup each time it executes and that creates no problem.

The data inside that database is mostly static; by that I mean that at the most, perhaps 5% of the tables will have modifications in a given day.  So that means that on each backup, 95% of `mydumper`'s time is spent overwriting backup files… with the same data.  That creates lots of useless I/O, slows down the backup and adds master-slave replication lag.

As mentioned, that MySQL installation is configured as one file per table, and `mydumper` is also creating one file per table, making it a 1:1 relationship. So I started toying with the idea of comparing file modification dates between the MySQL files and the backup files, to determine which tables could safely be skipped during the backup (if a given backup file modification date is a week later than its corresponding MySQL file modification date, I can safely assume the database table has not been modified since the backup and that I can skip the backup of that table).

So to be on the safe side, I'd like to tell `mydumper` what tables I want to _skip_, but I fear using the `--regex` option with a 10MB long string that describes all the table names to skip (using regex forward references, yuck!) would be crazy.

So I wonder, is there a way for me to accomplish the above? perhaps adding an option to specify an external file that contains names of tables to skip, one per line? or maybe adding an option to skip backup of a table when its destination file in the output directory already exists? I'm really open to suggestions here.

(Obviously the ideal situation would be for `mydumper` to automagically take care of comparing the backup file modification dates with the MySQL dataset, by offering a “refresh backup” mode or something, but I understand this could potentially create many, many, many problems depending on the individual data models.)

Thanks for your feedback and for mydumper!

**Comment by maxbube** [comment]
Hi @waptaff, 

Is almost impossible to do that with logical backup for Innodb, you could have unchanged .ibd files just because updates were not still flushed from memory.

What mydumper has is --updated-since but only makes sense to use it for myisam or archive engines and this was an experimental last resource option to assist on some specific scenarios.

What I would recommend to you is to use xtrabackup which has support for incremental backups and with that DB size it will be a lot faster than mydumper.

**Comment by waptaff** [comment]
> Is almost impossible to do that with logical backup for Innodb, you could have unchanged .ibd files just because updates were not still flushed from memory.

I understand the caveats and I'm prepared to deal with them; I'd have for instance no problem with restarting the MySQL server before the backup happens to ensure commits are written to disk and filesystem modification dates are meaningful.

I have other means to restore in case of major failure; all I really want is the fastest logical backup available so it's easy for developers to pick a set of tables from the backup and work from them (our data model allows such “heresies”).

So, yeah, mydumper currently does everything we want, but it'd save us lots of resources to be able to specify a very large number of tables to skip.  Thanks for considering it.

**Comment by druud** [comment]
On a stopped slave, flush tables, then gather the names of the changed tables, and let mydumper dump those. Maybe use multiple runs and give it 100 per run?

I used
```
mydumper \
--outputdir         /mysql/foo/tmp/ \
--statement-size    4000000 \
--rows              1000000 \
--chunk-filesize    500 \
--build-empty-files \
--triggers   \
--events     \
--routines   \
--no-locks   \
--logfile    /mysql/foo/tmp/mydumper.log \
--threads    24 \
--verbose    3
```
to dump 2.5 TB on a stopped SSD-based slave, and it only took 2h30m.
