### ISSUE TITLE
Enhancement request:  myloader option to prioritize size

### ISSUE THREAD

**Issue by UnixRonin** [maxbube/mydumper#78]
Enhancement request:
Would it be possible to add a feature request to myloader to sort SQL data files by size and prioritize load order by decreasing size?  The goal of this would be to try to improve the load time of databases dominated by a few large tables by trying to parallelize the loading of those large tables as much as possible, so as to try to minimize the degenerate case in which there is a "long tail" with only one thread running loading one huge table.  I think this would result in better distributing the workload across the available threads and reduce net load time.

**Comment by maxbube** [comment]
Hi @UnixRonin did you try with chunks? using a good --rows value for chunking would help on this as the work will be fairly distributed across all threads.

**Comment by davidducos** [comment]
The linked PR is the best approach, we are not going to sort by file size, we are doing by a the amount of rows that is provided by mydumper.
