### ISSUE TITLE
Log less "Empty table" messages, for empty chunks.

### ISSUE THREAD

**Issue by druud** [maxbube/mydumper#85]
With a table with sparse ids, the empty chunks get logged as "Empty table".
Make that "Empty chunk(s)", and don't log so many of them.

**Comment by maxbube** [comment]
Hi @druud thanks for comment! I will keep this in mind.

**Comment by davidducos** [comment]
Not just messages also less empty files as @druud  mention in https://github.com/maxbube/mydumper/issues/84
