### ISSUE TITLE
Make releases with rpm and debs in github

### ISSUE THREAD

**Issue by grypyrg** [maxbube/mydumper#9]
It would be great to make `.rpm` and `.deb` packages and put them in releases here.

**Comment by maxbube** [comment]
Will do 👍 also as reference you can check this out to compile mydumper for different platforms

https://github.com/maxbube/mydumper_builder

I will add code later to create packages

**Comment by nkadel-skyhook** [comment]
You're very welcome to my code for precisely this, at https://github.com/nkadel-skyhook/mydumper-0.9.x-srpm/blob/nkadel-0.9.3/mydumper.spec 

There is also a "Makefile" there for doing "mock" based builds for different enrivonments.
