### ISSUE TITLE
Way mydumper store procedures/functions?

### ISSUE THREAD

**Issue by renatoakaboci** [maxbube/mydumper#94]
Hi, I´m getting some trouble using this feature. I got many syntax error while trying to manually restore a dump of database. I´ve made some testes in this stuff, and I got the point that if I use "mysqldump", on file it store, I can see some:

` -- Dumping routines for database 'sample'
--
/*!50003 DROP FUNCTION IF EXISTS `proximo_dia_util` */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = latin1 */ ;
/*!50003 SET character_set_results = latin1 */ ;
/*!50003 SET collation_connection  = latin1_swedish_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` FUNCTION `proximo_dia_util`(emp INTEGER, dti DATE) RETURNS date
    DETERMINISTIC
BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE id INT DEFAULT 0;
    DECLARE c INT DEFAULT 0;
...
`

While mydumper save as:
`SET @PREV_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @PREV_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @PREV_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET character_set_client = latin1;
SET character_set_results = latin1;
SET collation_connection = latin1_swedish_ci;
DROP FUNCTION IF EXISTS `proximo_dia_util`;
CREATE DEFINER=`root`@`localhost` FUNCTION `proximo_dia_util`(emp INTEGER, dti DATE) RETURNS date
    DETERMINISTIC
BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE id INT DEFAULT 0;
    DECLARE c INT DEFAULT 0;
...
`
Is is an issue or kind of? 
I really appreciate some help, since there is no version to windows environment.

Thanks in advance.

**Comment by renatoakaboci** [comment]
I got the point. The issue seems to be like there is no DELIMITER set on sql file, the mysql client got lost and start giving errors.
Is there anyway to make mydumper store with this "DELIMITER" ?

**Comment by maxbube** [comment]
Hi @renatoakaboci 

mydumper do not need delimiters as myloader is not restoring using a mysql cli, myloader is a client itself using the mysql libs, so if I add delimiters to the sql file it will fail.
