### ISSUE TITLE
Mydumper depends on libmysqlclient.so.18 / Maria DB 10.2

### ISSUE THREAD

**Issue by maxdwit** [maxbube/mydumper#96]
Using Maria DB 10.2 we have:

libmysqlclient.so.19
libmysqlclient.so.20

Workaround is in place for the moment.

**Comment by maxbube** [comment]
Hi @maxdwit 

Is this still a problem if you use the binaries on the release section?

**Comment by maxdwit** [comment]
As can see, this has been removed ( from jessie mydumper_0.6.1-1_amd64.deb )
	libmysqlclient.so.18 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 
And this added ( Release mydumper_0.9.3-41.ubuntu_amd64.deb )
	libesets_pac.so => /usr/lib/libesets_pac.so 

Everything else seems to be in place.

complete ldd output:
 ldd myloader |sort|cut -d\( -f1
	/lib64/ld-linux-x86-64.so.2 
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 
	libesets_pac.so => /usr/lib/libesets_pac.so 
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 
	linux-vdso.so.1 =>  

Will this version emerge into jessie?

**Comment by maxbube** [comment]
Hi @maxdwit next release will have jessie package. I trying to get it done by tomorrow, if not early next week

**Comment by maxdwit** [comment]
Nice. Thanks.

2018-05-03 16:52 GMT+02:00 Max Bubenick <notifications@github.com>:
