### ISSUE TITLE
MYSQL_LIBRARIES_mariadb-NOTFOUND

### ISSUE THREAD

**Issue by toddstoffel** [maxbube/mydumper#97]
cmake throws library error. Centos 7 with MariaDB 10.2

[root@node1 mydumper]# cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using mysql-config: /bin/mysql_config
-- Found MySQL: /usr/include/mysql, MYSQL_LIBRARIES_mariadb-NOTFOUND;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libpthread.so;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1")
-- checking for one of the modules 'glib-2.0'
-- checking for one of the modules 'gthread-2.0'
-- checking for module 'libpcre'
--   found libpcre, version 8.32
-- Found PCRE: /usr/include
1
-- ------------------------------------------------
-- MYSQL_CONFIG = /bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQL_LIBRARIES_mariadb
    linked by target "mydumper" in directory /tmp/mydumper
    linked by target "myloader" in directory /tmp/mydumper

-- Configuring incomplete, errors occurred!
See also "/tmp/mydumper/CMakeFiles/CMakeOutput.log".

**Comment by maxbube** [comment]
Try this
```
cmake . -DMYSQL_LIBRARIES_mariadb:FILEPATH=/usr/lib64/libmariadbclient.a -DWITH_SSL=OFF
make
```

From this PR #130

**Comment by toddstoffel** [comment]
Still no luck.


root@ip-172-31-44-195:/home/ubuntu/mydumper# cmake . -DMYSQL_LIBRARIES_mariadb:FILEPATH=/usr/lib64/libmariadbclient.a -DWITH_SSL=OFF
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/libmariadbclient.a;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for one of the modules 'glib-2.0'
-- Checking for one of the modules 'gthread-2.0'
-- Checking for module 'libpcre'
--   Found libpcre, version 8.38
-- Found PCRE: /usr/include

CMake Warning at docs/CMakeLists.txt:9 (message):
  Unable to find Sphinx documentation generator


-- ------------------------------------------------
-- MYSQL_CONFIG = /usr/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/mydumper
root@ip-172-31-44-195:/home/ubuntu/mydumper# make
Scanning dependencies of target mydumper
[ 10%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
[ 20%] Building C object CMakeFiles/mydumper.dir/server_detect.c.o
[ 30%] Building C object CMakeFiles/mydumper.dir/g_unix_signal.c.o
[ 40%] Building C object CMakeFiles/mydumper.dir/connection.c.o
[ 50%] Building C object CMakeFiles/mydumper.dir/getPassword.c.o
make[2]: *** No rule to make target '/usr/lib64/libmariadbclient.a', needed by 'mydumper'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mydumper.dir/all' failed
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
