### ISSUE TITLE
Double free or corruption

### ISSUE THREAD

**Issue by mfrederico** [maxbube/mydumper#98]
I'm opening a new issue to make sure you see this:
I believe I've found the solution for issue #44  .. In start_dump() it has a mysql_close(conn) on 1481 and then it attempts to mysql_close(conn) AGAIN on 1006 which throws that error.

Here is a diff to fix it from the master branch

```
diff --git a/mydumper.c b/mydumper.c
index 43dce6d..d0916c0 100644
--- a/mydumper.c
+++ b/mydumper.c
@@ -1003,7 +1003,7 @@ void *exec_thread(void *data) {
                clear_dump_directory();
                MYSQL *conn= create_main_connection();
                start_dump(conn);
-               mysql_close(conn);
+               //mysql_close(conn);
                mysql_thread_end();
 
                // Don't switch the symlink on shutdown because the dump is probably incomplete.
```

**Comment by maxbube** [comment]
Hi @mfrederico 

Thanks for the report, this is merged and will be released soon.
